import type { FontSpec, LookDef } from "./themes.ts";

const font = (family: string, pkg: string, weights: number[], fallback: string): FontSpec => ({ family, pkg, weights, fallback });
const SERIF = "Georgia, 'Times New Roman', serif";
const SANS = "system-ui, -apple-system, 'Segoe UI', Roboto, Arial, sans-serif";

/** Looks for print/sign/apparel shops and local retail (research/print-signs-apparel.md, research/retail-shops.md). */
export const SHOP_LOOKS: Record<string, LookDef> = {
  "print.press_check": {
    id: "print.press_check",
    layout: "split",
    name: "Press Check",
    category: "print",
    palette: {
      bg: "#FBFAF7", surface: "#FFFFFF", band: "#EEF2F4", text: "#16181D", muted: "#4B5260", heading: "#16181D",
      link: "#B0135A", primary: "#00668A", secondary: "#16181D", accent: "#FFD400", heroBg: "#EEF2F4", onHero: "#16181D",
      barBg: "#16181D", onBar: "#FFFFFF", footerBg: "#16181D", onFooter: "#EEF2F4", open: "#1F7A4D", closed: "#B0135A",
    },
    fonts: { heading: font("Red Hat Display", "red-hat-display", [700], SANS), body: font("Red Hat Text", "red-hat-text", [400, 700], SANS) },
    headingWeight: 700,
    radius: 2,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "ruled", badge: "plain", priceList: "leaders", spacing: "standard" },
    photoDirection: "Overhead flat-lays of cards, envelopes and swatches in daylight.",
  },
  "print.fresh_ink": {
    id: "print.fresh_ink",
    layout: "poster",
    name: "Fresh Ink",
    category: "print",
    palette: {
      bg: "#F4F1EA", surface: "#FFFFFF", band: "#E9E4D8", text: "#17161A", muted: "#4A4750", heading: "#17161A",
      link: "#0F6E64", primary: "#FF5A1F", secondary: "#17161A", accent: "#2BB3A3", heroBg: "#17161A", onHero: "#F4F1EA",
      barBg: "#17161A", onBar: "#F4F1EA", footerBg: "#17161A", onFooter: "#F4F1EA", open: "#0F6E64", closed: "#B3261E",
    },
    fonts: { heading: font("Anton", "anton", [400], SANS), body: font("Rubik", "rubik", [400, 700], SANS) },
    headingWeight: 400,
    radius: 4,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "dense" },
    photoDirection: "Shirts on real people, ink on the press, squeegee close-ups.",
  },
  "print.main_street_enamel": {
    id: "print.main_street_enamel",
    layout: "overlap",
    name: "Main Street Enamel",
    category: "print",
    palette: {
      bg: "#F5EEDD", surface: "#FFFBF2", band: "#EADFC6", text: "#14233C", muted: "#4A5468", heading: "#14233C",
      link: "#8F2F16", primary: "#B23A1C", secondary: "#14233C", accent: "#D8A93B", heroBg: "#14233C", onHero: "#F5EEDD",
      barBg: "#14233C", onBar: "#F5EEDD", footerBg: "#14233C", onFooter: "#F5EEDD", open: "#2E6B3A", closed: "#8F2F16",
    },
    fonts: { heading: font("Bungee", "bungee", [400], SANS), body: font("Hanken Grotesk", "hanken-grotesk", [400, 700], SANS) },
    headingWeight: 400,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "seal", priceList: "cards", spacing: "standard" },
    photoDirection: "Finished storefronts, lettered trucks and trailers, straight-on daylight.",
  },
  "print.thread_needle": {
    id: "print.thread_needle",
    layout: "soft",
    name: "Thread & Needle",
    category: "print",
    palette: {
      bg: "#F7F3EC", surface: "#FFFFFF", band: "#EFE6D8", text: "#1F2A44", muted: "#535866", heading: "#1F2A44",
      link: "#9E3B4E", primary: "#9E3B4E", secondary: "#1F2A44", accent: "#E3B95C", heroBg: "#EFE6D8", onHero: "#1F2A44",
      barBg: "#1F2A44", onBar: "#F7F3EC", footerBg: "#1F2A44", onFooter: "#F7F3EC", open: "#2E6B3A", closed: "#9E3B4E",
    },
    fonts: { heading: font("Young Serif", "young-serif", [400], SERIF), body: font("Instrument Sans", "instrument-sans", [400, 700], SANS) },
    headingWeight: 400,
    radius: 16,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "shadow", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Macro stitch detail, folded polos, hats on a table.",
  },

  "retail.shop_window": {
    id: "retail.shop_window",
    layout: "editorial",
    name: "Shop Window",
    category: "retail",
    palette: {
      bg: "#FBF8F6", surface: "#FFFFFF", band: "#F4E1DC", text: "#1C1A1A", muted: "#564C4C", heading: "#1C1A1A",
      link: "#9E3D52", primary: "#9E3D52", secondary: "#1C1A1A", accent: "#C9A96E", heroBg: "#F4E1DC", onHero: "#1C1A1A",
      barBg: "#1C1A1A", onBar: "#FBF8F6", footerBg: "#1C1A1A", onFooter: "#F4E1DC", open: "#2E6B3A", closed: "#9E3D52",
    },
    fonts: { heading: font("Cormorant Garamond", "cormorant-garamond", [600], SERIF), body: font("Jost", "jost", [400, 700], SANS) },
    headingWeight: 600,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "flat", badge: "plain", priceList: "cards", spacing: "airy" },
    photoDirection: "Tall portrait crops of styled racks and displays, soft daylight.",
  },
  "retail.mercantile": {
    id: "retail.mercantile",
    layout: "split",
    name: "Mercantile",
    category: "retail",
    palette: {
      bg: "#F7F1E3", surface: "#FFFCF5", band: "#EADBC0", text: "#2A2420", muted: "#544A40", heading: "#2E4A36",
      link: "#8E2C1F", primary: "#8E2C1F", secondary: "#2E4A36", accent: "#D8A23A", heroBg: "#2E4A36", onHero: "#F7F1E3",
      barBg: "#2E4A36", onBar: "#F7F1E3", footerBg: "#2A2420", onFooter: "#EADBC0", open: "#2E6B3A", closed: "#8E2C1F",
    },
    fonts: { heading: font("Rokkitt", "rokkitt", [700], SERIF), body: font("Karla", "karla", [400, 700], SANS) },
    headingWeight: 700,
    radius: 4,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Wood floors, shelves of goods, chalkboard signs, the front porch.",
  },
  "retail.bloom": {
    id: "retail.bloom",
    layout: "soft",
    name: "Bloom",
    category: "retail",
    palette: {
      bg: "#FFFBFA", surface: "#FFFFFF", band: "#FBE3EA", text: "#2B2230", muted: "#574A5B", heading: "#6B2D5C",
      link: "#6B2D5C", primary: "#6B2D5C", secondary: "#2F5D46", accent: "#7FA36B", heroBg: "#FBE3EA", onHero: "#2B2230",
      barBg: "#6B2D5C", onBar: "#FFFFFF", footerBg: "#2B2230", onFooter: "#FBE3EA", open: "#2F5D46", closed: "#9E2A3A",
    },
    fonts: { heading: font("Marcellus", "marcellus", [400], SERIF), body: font("Mulish", "mulish", [400, 700], SANS) },
    headingWeight: 400,
    radius: 24,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "flat", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Arrangements in soft light, buckets of stems, the cooler, hands at work.",
  },
  "retail.salvage_yard": {
    id: "retail.salvage_yard",
    layout: "poster",
    name: "Salvage Yard",
    category: "retail",
    palette: {
      bg: "#F3EEE4", surface: "#FBF8F2", band: "#DCD6CB", text: "#2B2B28", muted: "#4F4D46", heading: "#2B2B28",
      link: "#8F3E18", primary: "#A44A1F", secondary: "#2B2B28", accent: "#B08D57", heroBg: "#2B2B28", onHero: "#F3EEE4",
      barBg: "#2B2B28", onBar: "#F3EEE4", footerBg: "#2B2B28", onFooter: "#F3EEE4", open: "#2E6B3A", closed: "#8F3E18",
    },
    fonts: { heading: font("Old Standard TT", "old-standard-tt", [700], SERIF), body: font("IBM Plex Sans", "ibm-plex-sans", [400, 700], SANS) },
    headingWeight: 700,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "ruled", badge: "seal", priceList: "leaders", spacing: "dense" },
    photoDirection: "Booth tags, stacked chairs, glassware on old shelves, the shop sign.",
  },
};
