import type { FontSpec, LookDef } from "./themes.ts";

const font = (family: string, pkg: string, weights: number[], fallback: string): FontSpec => ({ family, pkg, weights, fallback });
const SERIF = "Georgia, 'Times New Roman', serif";
const SANS = "system-ui, -apple-system, 'Segoe UI', Roboto, Arial, sans-serif";

/** Looks for salons, auto repair, landscaping and cleaning. Contrast is checked at build by resolveTheme. */
export const MORE_LOOKS: Record<string, LookDef> = {
  "salon.porch_light": {
    id: "salon.porch_light",
    layout: "editorial",
    name: "Porch Light",
    category: "salon",
    palette: {
      bg: "#F7F1E8", surface: "#FFFDF9", band: "#EFE3D2", text: "#2E2420", muted: "#5B4D45", heading: "#2E2420",
      link: "#7A4332", primary: "#A05A45", secondary: "#4F5C45", accent: "#C9A88A", heroBg: "#EFE3D2", onHero: "#2E2420",
      barBg: "#2E2420", onBar: "#F7F1E8", footerBg: "#2E2420", onFooter: "#F7F1E8", open: "#3D6B44", closed: "#8E3B2A",
    },
    fonts: { heading: font("Fraunces", "fraunces", [600], SERIF), body: font("Karla", "karla", [400, 700], SANS) },
    headingWeight: 600,
    radius: 16,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "flat", badge: "plain", priceList: "cards", spacing: "airy" },
    photoDirection: "Natural window light, warm grade, close-ups of texture and hands, plants and wood in the shop.",
  },
  "salon.night_shift": {
    id: "salon.night_shift",
    layout: "poster",
    name: "Night Shift",
    category: "salon",
    palette: {
      bg: "#121212", surface: "#232323", band: "#1B1B1B", text: "#EEE9E0", muted: "#B3ADA4", heading: "#EEE9E0",
      link: "#E2C25A", primary: "#C9A227", secondary: "#EEE9E0", accent: "#C9A227", heroBg: "#121212", onHero: "#EEE9E0",
      barBg: "#0B0B0B", onBar: "#EEE9E0", footerBg: "#0B0B0B", onFooter: "#EEE9E0", open: "#7DDB97", closed: "#F2948A",
    },
    fonts: { heading: font("Oswald", "oswald", [600], SANS), body: font("Inter", "inter", [400, 700], SANS) },
    headingWeight: 600,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "leaders", spacing: "standard" },
    photoDirection: "High contrast, cool or desaturated grade, side-lit fades, razor and line-up detail, dark backgrounds.",
  },
  "salon.main_street": {
    id: "salon.main_street",
    layout: "overlap",
    name: "Main Street",
    category: "salon",
    palette: {
      bg: "#F4EFE4", surface: "#FFF9EE", band: "#EBE3D2", text: "#1B1B1B", muted: "#4F4A42", heading: "#1E3A5F",
      link: "#1E3A5F", primary: "#A63D2F", secondary: "#1E3A5F", accent: "#A63D2F", heroBg: "#1E3A5F", onHero: "#FFF9EE",
      barBg: "#1E3A5F", onBar: "#FFF9EE", footerBg: "#1B1B1B", onFooter: "#F4EFE4", open: "#2E6B3A", closed: "#A63D2F",
    },
    fonts: { heading: font("Zilla Slab", "zilla-slab", [700], SERIF), body: font("Libre Franklin", "libre-franklin", [400, 700], SANS) },
    headingWeight: 700,
    radius: 4,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "Candid and documentary: chairs, storefront, regulars, kids' first cut, slight warm film tone.",
  },
  "salon.color_bar": {
    id: "salon.color_bar",
    layout: "soft",
    name: "Color Bar",
    category: "salon",
    palette: {
      bg: "#FFFBF5", surface: "#FFFFFF", band: "#FDF0D5", text: "#3D1F3A", muted: "#664A63", heading: "#3D1F3A",
      link: "#8E2F5A", primary: "#F26B5B", secondary: "#3D1F3A", accent: "#A8D5C2", heroBg: "#FFE8E2", onHero: "#3D1F3A",
      barBg: "#3D1F3A", onBar: "#FFFBF5", footerBg: "#3D1F3A", onFooter: "#FFFBF5", open: "#1F6B4A", closed: "#A8322A",
    },
    fonts: { heading: font("DM Serif Display", "dm-serif-display", [400], SERIF), body: font("DM Sans", "dm-sans", [400, 700], SANS) },
    headingWeight: 400,
    radius: 18,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Saturated, clean backdrops, before/after pairs, color swatches, strong crops.",
  },

  "auto.shop_floor": {
    id: "auto.shop_floor",
    layout: "split",
    name: "Shop Floor",
    category: "auto",
    palette: {
      bg: "#F3F2EE", surface: "#FFFFFF", band: "#E6E4DE", text: "#1E2328", muted: "#4A5560", heading: "#1E2328",
      link: "#2F4C66", primary: "#F2B705", secondary: "#1E2328", accent: "#F2B705", heroBg: "#E6E4DE", onHero: "#1E2328",
      barBg: "#1E2328", onBar: "#FFFFFF", footerBg: "#1E2328", onFooter: "#E6E4DE", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: font("Oswald", "oswald", [600], SANS), body: font("Barlow", "barlow", [400, 700], SANS) },
    headingWeight: 600,
    radius: 2,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "cards", spacing: "dense" },
    photoDirection: "Real bays, lifts, tools laid out, a technician's hands at work. Cool, even light, slightly desaturated.",
  },
  "auto.main_street_garage": {
    id: "auto.main_street_garage",
    layout: "overlap",
    name: "Main Street Garage",
    category: "auto",
    palette: {
      bg: "#FBF6EC", surface: "#FFFFFF", band: "#EFE3CC", text: "#2A2622", muted: "#5A5048", heading: "#24384F",
      link: "#A23B2A", primary: "#A23B2A", secondary: "#24384F", accent: "#D8C3A0", heroBg: "#24384F", onHero: "#FBF6EC",
      barBg: "#24384F", onBar: "#FFFFFF", footerBg: "#24384F", onFooter: "#EFE3CC", open: "#2E6B3A", closed: "#A23B2A",
    },
    fonts: { heading: font("Arvo", "arvo", [700], SERIF), body: font("Source Sans 3", "source-sans-3", [400, 700], SANS) },
    headingWeight: 700,
    radius: 10,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "none", card: "shadow", badge: "seal", priceList: "cards", spacing: "airy" },
    photoDirection: "Owner and crew in front of the storefront, warm late-day light, a sign or the town in the background.",
  },
  "auto.clear_diagnostic": {
    id: "auto.clear_diagnostic",
    layout: "minimal",
    name: "Clear Diagnostic",
    category: "auto",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EEF3F7", text: "#151B26", muted: "#4A5566", heading: "#151B26",
      link: "#1557E0", primary: "#1557E0", secondary: "#151B26", accent: "#0E9F8A", heroBg: "#EEF3F7", onHero: "#151B26",
      barBg: "#151B26", onBar: "#FFFFFF", footerBg: "#151B26", onFooter: "#EEF3F7", open: "#0B7A6A", closed: "#B03A22",
    },
    fonts: { heading: font("Space Grotesk", "space-grotesk", [600], SANS), body: font("IBM Plex Sans", "ibm-plex-sans", [400, 700], SANS) },
    headingWeight: 600,
    radius: 14,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "shadow", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Bright, clean bays, a scan tool or tablet showing an inspection, close-ups of components. High key.",
  },
  "auto.night_road": {
    id: "auto.night_road",
    layout: "poster",
    name: "Night Road",
    category: "auto",
    palette: {
      bg: "#F4F1EA", surface: "#FFFFFF", band: "#E9E4D8", text: "#141414", muted: "#4A4A44", heading: "#141414",
      link: "#9A3A08", primary: "#FF6A13", secondary: "#141414", accent: "#FF6A13", heroBg: "#141414", onHero: "#F4F1EA",
      barBg: "#141414", onBar: "#F4F1EA", footerBg: "#141414", onFooter: "#F4F1EA", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: font("Archivo Black", "archivo-black", [400], SANS), body: font("Archivo", "archivo", [400, 700], SANS) },
    headingWeight: 400,
    radius: 4,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "A wrecker or truck on a rural road at dusk, tire tread close-ups. Real local shots, dramatic contrast.",
  },

  "landscaping.fresh_stripe": {
    id: "landscaping.fresh_stripe",
    layout: "soft",
    name: "Fresh Stripe",
    category: "landscaping",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F3F6EF", text: "#13201A", muted: "#46524B", heading: "#1E6B3A",
      link: "#1E6B3A", primary: "#F5C518", secondary: "#1E6B3A", accent: "#8CC63F", heroBg: "#1E6B3A", onHero: "#FFFFFF",
      barBg: "#13201A", onBar: "#FFFFFF", footerBg: "#13201A", onFooter: "#F3F6EF", open: "#1E6B3A", closed: "#A8322A",
    },
    fonts: { heading: font("Saira Condensed", "saira-condensed", [700], SANS), body: font("Mulish", "mulish", [400, 700], SANS) },
    headingWeight: 700,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "none", card: "bordered", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Bright mid-morning light, crisp mower stripes, low angle across the lawn, wide crops with sky.",
  },
  "landscaping.red_clay_pine": {
    id: "landscaping.red_clay_pine",
    layout: "editorial",
    name: "Red Clay & Pine",
    category: "landscaping",
    palette: {
      bg: "#FBF5EA", surface: "#FFFFFF", band: "#F2E7D3", text: "#2A2420", muted: "#5B5048", heading: "#2F4A3A",
      link: "#A8462C", primary: "#A8462C", secondary: "#2F4A3A", accent: "#D6AE62", heroBg: "#F2E7D3", onHero: "#2A2420",
      barBg: "#2F4A3A", onBar: "#FFFFFF", footerBg: "#2F4A3A", onFooter: "#F2E7D3", open: "#2E6B3A", closed: "#A8462C",
    },
    fonts: { heading: font("Bitter", "bitter", [700], SERIF), body: font("Hind", "hind", [400, 700], SANS) },
    headingWeight: 700,
    radius: 14,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "shadow", badge: "seal", priceList: "cards", spacing: "airy" },
    photoDirection: "Golden-hour light, fresh pine straw, mulch edges, brick borders, porches and mature trees.",
  },
  "landscaping.stone_garden": {
    id: "landscaping.stone_garden",
    layout: "minimal",
    name: "Stone & Garden",
    category: "landscaping",
    palette: {
      bg: "#EEEBE4", surface: "#FFFFFF", band: "#E3DFD5", text: "#2F3A40", muted: "#4E585D", heading: "#2F3A40",
      link: "#7A4D24", primary: "#8C5A2B", secondary: "#2F3A40", accent: "#7D8F6E", heroBg: "#2F3A40", onHero: "#EEEBE4",
      barBg: "#2F3A40", onBar: "#EEEBE4", footerBg: "#2F3A40", onFooter: "#EEEBE4", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: font("Newsreader", "newsreader", [600], SERIF), body: font("Plus Jakarta Sans", "plus-jakarta-sans", [400, 700], SANS) },
    headingWeight: 600,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "flat", badge: "plain", priceList: "cards", spacing: "airy" },
    photoDirection: "Wide finished-project shots, patios and walls at dusk with lighting on, natural stone texture.",
  },
  "landscaping.neighborhood_crew": {
    id: "landscaping.neighborhood_crew",
    layout: "overlap",
    name: "Neighborhood Crew",
    category: "landscaping",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EAF4F7", text: "#16283B", muted: "#44566A", heading: "#1B3A5C",
      link: "#1B5E9C", primary: "#C2531F", secondary: "#237A4B", accent: "#237A4B", heroBg: "#EAF4F7", onHero: "#1B3A5C",
      barBg: "#1B3A5C", onBar: "#FFFFFF", footerBg: "#1B3A5C", onFooter: "#EAF4F7", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: font("Lexend", "lexend", [700], SANS), body: font("Atkinson Hyperlegible", "atkinson-hyperlegible", [400, 700], SANS) },
    headingWeight: 700,
    radius: 20,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Candid crew-at-work shots, trailer and mower lineup, a smiling owner. Bright, natural grade.",
  },

  "cleaning.fresh_linen": {
    id: "cleaning.fresh_linen",
    layout: "editorial",
    name: "Fresh Linen",
    category: "cleaning",
    palette: {
      bg: "#FAF7F2", surface: "#FFFFFF", band: "#EEF3EE", text: "#1F2723", muted: "#4D5650", heading: "#2F4B3C",
      link: "#2F4B3C", primary: "#2F4B3C", secondary: "#3E6150", accent: "#F3D67A", heroBg: "#EEF3EE", onHero: "#1F2723",
      barBg: "#1F2723", onBar: "#FFFFFF", footerBg: "#1F2723", onFooter: "#EEF3EE", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: font("Fraunces", "fraunces", [600], SERIF), body: font("Nunito Sans", "nunito-sans", [400, 700], SANS) },
    headingWeight: 600,
    radius: 16,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "flat", badge: "plain", priceList: "cards", spacing: "airy" },
    photoDirection: "Bright natural light, folded towels, a wiped counter, a made bed. Lots of negative space.",
  },
  "cleaning.clear_blue": {
    id: "cleaning.clear_blue",
    layout: "split",
    name: "Clear Blue Professional",
    category: "cleaning",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EEF4FB", text: "#13263F", muted: "#45566B", heading: "#13263F",
      link: "#1D4FC4", primary: "#F59E0B", secondary: "#13263F", accent: "#2563EB", heroBg: "#13263F", onHero: "#FFFFFF",
      barBg: "#13263F", onBar: "#FFFFFF", footerBg: "#13263F", onFooter: "#EEF4FB", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: font("Plus Jakarta Sans", "plus-jakarta-sans", [700], SANS), body: font("Inter", "inter", [400, 700], SANS) },
    headingWeight: 700,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "bordered", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Uniformed team at work, branded vehicle, office and lobby shots, straight-on and evenly lit.",
  },
  "cleaning.magnolia_porch": {
    id: "cleaning.magnolia_porch",
    layout: "overlap",
    name: "Magnolia Porch",
    category: "cleaning",
    palette: {
      bg: "#FFF7EA", surface: "#FFFFFF", band: "#F7DCC4", text: "#2B211C", muted: "#5B4A40", heading: "#3D5A45",
      link: "#9E4330", primary: "#B5523B", secondary: "#3D5A45", accent: "#B5523B", heroBg: "#F7DCC4", onHero: "#2B211C",
      barBg: "#3D5A45", onBar: "#FFFFFF", footerBg: "#3D5A45", onFooter: "#FFF7EA", open: "#2E6B3A", closed: "#9E4330",
    },
    fonts: { heading: font("DM Serif Display", "dm-serif-display", [400], SERIF), body: font("Work Sans", "work-sans", [400, 700], SANS) },
    headingWeight: 400,
    radius: 14,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "seal", priceList: "cards", spacing: "airy" },
    photoDirection: "Owner and team portraits, real local homes and porches, warm tones, slightly candid.",
  },
  "cleaning.bright_bold": {
    id: "cleaning.bright_bold",
    layout: "soft",
    name: "Bright & Bold",
    category: "cleaning",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#DDF7F1", text: "#111827", muted: "#4B5563", heading: "#111827",
      link: "#0F766E", primary: "#0F766E", secondary: "#111827", accent: "#FFE14D", heroBg: "#DDF7F1", onHero: "#111827",
      barBg: "#111827", onBar: "#FFFFFF", footerBg: "#111827", onFooter: "#DDF7F1", open: "#0F766E", closed: "#B42318",
    },
    fonts: { heading: font("Sora", "sora", [700], SANS), body: font("DM Sans", "dm-sans", [400, 700], SANS) },
    headingWeight: 700,
    radius: 18,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Before/after splits, tight bold crops, overhead shots of clean surfaces, one bright prop color.",
  },
};
