import { f } from "../look-kit.ts";
import type { LookDef } from "../themes.ts";

/** More auto looks (colors + fonts). Contrast is checked at build by resolveTheme; see test/designs.test.ts. */
export const AUTO_LOOKS: Record<string, LookDef> = {
  // ---- dark ----
  "auto.pit_lane": {
    id: "auto.pit_lane",
    name: "Pit Lane",
    category: "auto",
    layout: "poster",
    palette: {
      bg: "#121212", surface: "#1C1C1C", band: "#232323", text: "#EDEDED", muted: "#B0B0B0", heading: "#FFFFFF",
      link: "#FF7A70", primary: "#E10600", secondary: "#F2F2F2", accent: "#E10600", heroBg: "#0A0A0A", onHero: "#FFFFFF",
      barBg: "#0A0A0A", onBar: "#FFFFFF", footerBg: "#0A0A0A", onFooter: "#BDBDBD", open: "#6EE7A0", closed: "#FF8A80",
    },
    fonts: { heading: f("saira-condensed", [800]), body: f("inter", [400, 700]) },
    headingWeight: 800,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "dense" },
    photoDirection: "Low angles on cars on the lift, red tool chests, motion blur; dark shop with hard spotlights.",
  },
  "auto.midnight_shine": {
    id: "auto.midnight_shine",
    name: "Midnight Shine",
    category: "auto",
    layout: "minimal",
    palette: {
      bg: "#0B1426", surface: "#121E36", band: "#172644", text: "#E6ECF5", muted: "#A6B4CA", heading: "#FFFFFF",
      link: "#8FD3FF", primary: "#8FD3FF", secondary: "#E6ECF5", accent: "#C0C8D4", heroBg: "#060C18", onHero: "#FFFFFF",
      barBg: "#060C18", onBar: "#FFFFFF", footerBg: "#060C18", onFooter: "#B9C6D9", open: "#7EE8B0", closed: "#FF9F94",
    },
    fonts: { heading: f("dm-serif-display", [400]), body: f("dm-sans", [400, 700]) },
    headingWeight: 400,
    radius: 16,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "small_caps", card: "flat", badge: "plain", priceList: "cards", spacing: "airy" },
    photoDirection: "Glossy paint reflecting studio lights, water beading on a hood, interiors after detail; deep blacks.",
  },
  "auto.motor_oil": {
    id: "auto.motor_oil",
    name: "Motor Oil",
    category: "auto",
    layout: "classic",
    palette: {
      bg: "#1E1A14", surface: "#28231B", band: "#302A21", text: "#EFE8DA", muted: "#BFB39E", heading: "#F7D774",
      link: "#F7D774", primary: "#F7B32B", secondary: "#EFE8DA", accent: "#F7B32B", heroBg: "#15120D", onHero: "#EFE8DA",
      barBg: "#15120D", onBar: "#EFE8DA", footerBg: "#15120D", onFooter: "#D2C7B3", open: "#A3E6A0", closed: "#FFA08F",
    },
    fonts: { heading: f("ultra", [400]), body: f("lato", [400, 700]) },
    headingWeight: 400,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Old-school garage: engines on stands, worn workbenches, amber work lights, grease-dark hands.",
  },
  "auto.gunmetal": {
    id: "auto.gunmetal",
    name: "Gunmetal",
    category: "auto",
    layout: "split",
    palette: {
      bg: "#24292E", surface: "#2D3339", band: "#343B42", text: "#E8EBEE", muted: "#AEB6BE", heading: "#FFFFFF",
      link: "#B6F36B", primary: "#9BE15D", secondary: "#3D8BFF", accent: "#9BE15D", heroBg: "#1B1F23", onHero: "#FFFFFF",
      barBg: "#1B1F23", onBar: "#FFFFFF", footerBg: "#1B1F23", onFooter: "#C5CCD3", open: "#9BE15D", closed: "#FF9A8A",
    },
    fonts: { heading: f("exo-2", [800]), body: f("hanken-grotesk", [400, 700]) },
    headingWeight: 800,
    radius: 10,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Modern diagnostics: laptops on fenders, scan tools, EV and hybrid components; cool steel tones.",
  },
  "auto.tow_line": {
    id: "auto.tow_line",
    name: "Tow Line",
    category: "auto",
    layout: "overlap",
    palette: {
      bg: "#102A22", surface: "#153429", band: "#1A3D31", text: "#EAF3EE", muted: "#A9C6B8", heading: "#FFFFFF",
      link: "#FFD24D", primary: "#FFD24D", secondary: "#FF8A4D", accent: "#FFD24D", heroBg: "#0A1D17", onHero: "#FFFFFF",
      barBg: "#0A1D17", onBar: "#FFFFFF", footerBg: "#0A1D17", onFooter: "#C6DDD2", open: "#8FF0B5", closed: "#FFA594",
    },
    fonts: { heading: f("bungee", [400]), body: f("atkinson-hyperlegible", [400, 700]) },
    headingWeight: 400,
    radius: 4,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "dense" },
    photoDirection: "Wreckers and rollbacks with lights on, roadside hookups at dusk, the driver by the truck.",
  },

  // ---- crisp white ----
  "auto.checkered_flag": {
    id: "auto.checkered_flag",
    name: "Checkered Flag",
    category: "auto",
    layout: "editorial",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F2F2F2", text: "#111111", muted: "#4F4F4F", heading: "#111111",
      link: "#C8102E", primary: "#C8102E", secondary: "#111111", accent: "#C8102E", heroBg: "#111111", onHero: "#FFFFFF",
      barBg: "#111111", onBar: "#FFFFFF", footerBg: "#111111", onFooter: "#E5E5E5", open: "#1F7A3F", closed: "#C8102E",
    },
    fonts: { heading: f("bebas-neue", [400]), body: f("work-sans", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "sticker", priceList: "cards", spacing: "dense" },
    photoDirection: "Black-and-white shop photos with one red accent, tires and wheels head-on, crisp graphic crops.",
  },
  "auto.tune_up": {
    id: "auto.tune_up",
    name: "Tune-Up",
    category: "auto",
    layout: "split",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F4F5F7", text: "#1D2129", muted: "#50565F", heading: "#1D2129",
      link: "#B54708", primary: "#F26A1B", secondary: "#1D2129", accent: "#F26A1B", heroBg: "#F4F5F7", onHero: "#1D2129",
      barBg: "#1D2129", onBar: "#FFFFFF", footerBg: "#1D2129", onFooter: "#E8EAED", open: "#1A7F44", closed: "#B42318",
    },
    fonts: { heading: f("red-hat-display", [800]), body: f("red-hat-text", [400, 700]) },
    headingWeight: 800,
    radius: 12,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Friendly service writer at the counter, oil changes and brake jobs in a bright, tidy bay.",
  },
  "auto.showroom": {
    id: "auto.showroom",
    name: "Showroom",
    category: "auto",
    layout: "classic",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F6F4F0", text: "#161616", muted: "#555150", heading: "#161616",
      link: "#7B5E2A", primary: "#7B5E2A", secondary: "#161616", accent: "#C2A15E", heroBg: "#161616", onHero: "#F6F4F0",
      barBg: "#161616", onBar: "#FFFFFF", footerBg: "#161616", onFooter: "#D8D2C4", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("playfair-display", [700]), body: f("instrument-sans", [400, 700]) },
    headingWeight: 700,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "none", label: "small_caps", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Detailed cars shot like a showroom: clean backdrops, reflections, leather and chrome close-ups.",
  },
  "auto.tread_right": {
    id: "auto.tread_right",
    name: "Tread Right",
    category: "auto",
    layout: "overlap",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EEF3FB", text: "#14213D", muted: "#45526B", heading: "#14213D",
      link: "#1F4FD1", primary: "#FFC300", secondary: "#1F4FD1", accent: "#FFC300", heroBg: "#1F4FD1", onHero: "#FFFFFF",
      barBg: "#14213D", onBar: "#FFFFFF", footerBg: "#14213D", onFooter: "#DCE5F5", open: "#1A7F44", closed: "#B42318",
    },
    fonts: { heading: f("montserrat", [800]), body: f("open-sans", [400, 700]) },
    headingWeight: 800,
    radius: 8,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "seal", priceList: "cards", spacing: "standard" },
    photoDirection: "Stacks of new tires, balancing and alignment rigs, tread close-ups; bright and clean with blue accents.",
  },
  "auto.pull_start": {
    id: "auto.pull_start",
    name: "Pull Start",
    category: "auto",
    layout: "classic",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F0F5EE", text: "#1C2419", muted: "#4C5A47", heading: "#1E5631",
      link: "#1E6B35", primary: "#1E6B35", secondary: "#F2C230", accent: "#F2C230", heroBg: "#F0F5EE", onHero: "#1C2419",
      barBg: "#F2C230", onBar: "#1C2419", footerBg: "#1C2419", onFooter: "#E3EBDF", open: "#1E6B35", closed: "#B3261E",
    },
    fonts: { heading: f("asap-condensed", [700]), body: f("karla", [400, 700]) },
    headingWeight: 700,
    radius: 6,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "leaders", spacing: "dense" },
    photoDirection: "Mowers, chainsaws and four-wheelers on the bench, carburetor parts laid out; daylight through a shop door.",
  },

  // ---- warm / tinted light ----
  "auto.route_31": {
    id: "auto.route_31",
    name: "Route 31",
    category: "auto",
    layout: "soft",
    palette: {
      bg: "#F6EEDC", surface: "#FFFAF0", band: "#EADDC1", text: "#2A2420", muted: "#5C5045", heading: "#1F5C5A",
      link: "#1F5C5A", primary: "#C8412D", secondary: "#1F5C5A", accent: "#E7B04B", heroBg: "#1F5C5A", onHero: "#F6EEDC",
      barBg: "#2A2420", onBar: "#FFFAF0", footerBg: "#2A2420", onFooter: "#EADDC1", open: "#2F6B33", closed: "#A3301A",
    },
    fonts: { heading: f("righteous", [400]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 400,
    radius: 14,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Classic cars and pickups, chrome and two-tone paint, a roadside shop sign; warm, nostalgic grade.",
  },
  "auto.steel_bay": {
    id: "auto.steel_bay",
    name: "Steel Bay",
    category: "auto",
    layout: "editorial",
    palette: {
      bg: "#EDF1F5", surface: "#FFFFFF", band: "#DCE4EC", text: "#1A2633", muted: "#46566A", heading: "#1A2633",
      link: "#23578C", primary: "#23578C", secondary: "#E05A2B", accent: "#E05A2B", heroBg: "#DCE4EC", onHero: "#1A2633",
      barBg: "#1A2633", onBar: "#FFFFFF", footerBg: "#23578C", onFooter: "#FFFFFF", open: "#1C6E45", closed: "#A93226",
    },
    fonts: { heading: f("chivo", [800]), body: f("public-sans", [400, 700]) },
    headingWeight: 800,
    radius: 4,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "flat", badge: "plain", priceList: "cards", spacing: "dense" },
    photoDirection: "Organized bays, lifts and wall-hung tools in cool fluorescent light; technicians in blue shirts.",
  },
  "auto.gravel_road": {
    id: "auto.gravel_road",
    name: "Gravel Road",
    category: "auto",
    layout: "poster",
    palette: {
      bg: "#F1E7D3", surface: "#FBF6EC", band: "#E4D5B8", text: "#2B2117", muted: "#5D4E3C", heading: "#2B2117",
      link: "#8A4B14", primary: "#B5651D", secondary: "#2B2117", accent: "#B5651D", heroBg: "#2B2117", onHero: "#F1E7D3",
      barBg: "#2B2117", onBar: "#F1E7D3", footerBg: "#2B2117", onFooter: "#E4D5B8", open: "#2F6B33", closed: "#A3301A",
    },
    fonts: { heading: f("kanit", [700]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 700,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Trucks and farm rigs on dirt roads, mud tires, lift kits; dusty golden light.",
  },
  "auto.country_service": {
    id: "auto.country_service",
    name: "Country Service",
    category: "auto",
    layout: "overlap",
    palette: {
      bg: "#EAEFE6", surface: "#FFFFFF", band: "#DAE3D3", text: "#1F2A22", muted: "#4A5A4E", heading: "#2C4A3A",
      link: "#2C5F7A", primary: "#2C4A3A", secondary: "#D96C3B", accent: "#D96C3B", heroBg: "#DAE3D3", onHero: "#1F2A22",
      barBg: "#DAE3D3", onBar: "#1F2A22", footerBg: "#2C4A3A", onFooter: "#DAE3D3", open: "#2C6B3A", closed: "#A3301A",
    },
    fonts: { heading: f("epilogue", [800]), body: f("figtree", [400, 700]) },
    headingWeight: 800,
    radius: 18,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "seal", priceList: "cards", spacing: "airy" },
    photoDirection: "A small-town shop with trees behind, customers chatting with the owner, family cars; soft natural light.",
  },
  "auto.copper_top": {
    id: "auto.copper_top",
    name: "Copper Top",
    category: "auto",
    layout: "split",
    palette: {
      bg: "#F6E8DF", surface: "#FFFAF6", band: "#ECD6C7", text: "#2D1E18", muted: "#5F4A3F", heading: "#2D1E18",
      link: "#9A3412", primary: "#9A3412", secondary: "#2D1E18", accent: "#E08A4F", heroBg: "#ECD6C7", onHero: "#2D1E18",
      barBg: "#2D1E18", onBar: "#FFFAF6", footerBg: "#9A3412", onFooter: "#FFF4EC", open: "#2F6B33", closed: "#9A2A16",
    },
    fonts: { heading: f("sora", [700]), body: f("mulish", [400, 700]) },
    headingWeight: 700,
    radius: 10,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "bordered", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Body work and paint: sanding, primer, a fresh coat under booth lights; warm copper and clay tones.",
  },
  "auto.fleet_service": {
    id: "auto.fleet_service",
    name: "Fleet Service",
    category: "auto",
    layout: "classic",
    palette: {
      bg: "#EFEEEA", surface: "#FAFAF8", band: "#E2E0DA", text: "#22252A", muted: "#53565C", heading: "#1D3557",
      link: "#1D3557", primary: "#F4C430", secondary: "#1D3557", accent: "#F4C430", heroBg: "#1D3557", onHero: "#FFFFFF",
      barBg: "#1D3557", onBar: "#FFFFFF", footerBg: "#22252A", onFooter: "#E2E0DA", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("familjen-grotesk", [700]), body: f("cabin", [400, 700]) },
    headingWeight: 700,
    radius: 8,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "bordered", badge: "plain", priceList: "cards", spacing: "standard" },
    photoDirection: "Work trucks and vans lined up, diesel service, a tech with a clipboard; even overcast light.",
  },

  // ---- bold / saturated ----
  "auto.hot_rod": {
    id: "auto.hot_rod",
    name: "Hot Rod",
    category: "auto",
    layout: "split",
    palette: {
      bg: "#B5121B", surface: "#9E1018", band: "#8A0E15", text: "#FFFFFF", muted: "#FFDCDC", heading: "#FFFFFF",
      link: "#FFE066", primary: "#FFE066", secondary: "#111111", accent: "#FFE066", heroBg: "#111111", onHero: "#FFFFFF",
      barBg: "#111111", onBar: "#FFFFFF", footerBg: "#111111", onFooter: "#F2C2C2", open: "#C9FFD5", closed: "#FFE3A3",
    },
    fonts: { heading: f("unbounded", [800]), body: f("barlow", [400, 700]) },
    headingWeight: 800,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Muscle cars and performance builds, exhaust and headers, burnout smoke; saturated, high contrast.",
  },
  "auto.foam_cannon": {
    id: "auto.foam_cannon",
    name: "Foam Cannon",
    category: "auto",
    layout: "soft",
    palette: {
      bg: "#0050EC", surface: "#0046CF", band: "#003DB3", text: "#FFFFFF", muted: "#E4EBFF", heading: "#FFFFFF",
      link: "#B8FF7A", primary: "#9CFF57", secondary: "#0A1A3F", accent: "#9CFF57", heroBg: "#002C80", onHero: "#FFFFFF",
      barBg: "#0A1A3F", onBar: "#FFFFFF", footerBg: "#0A1A3F", onFooter: "#CFDBFF", open: "#B5FFC9", closed: "#FFD0C7",
    },
    fonts: { heading: f("rubik", [800]), body: f("plus-jakarta-sans", [400, 700]) },
    headingWeight: 800,
    radius: 24,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "none", card: "flat", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Suds and foam on paint, pressure-washer spray backlit by sun, gleaming wheels; bright and splashy.",
  },
  "auto.green_light": {
    id: "auto.green_light",
    name: "Green Light",
    category: "auto",
    layout: "overlap",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#D4F53C", text: "#141A0B", muted: "#3E4A26", heading: "#141A0B",
      link: "#3C6E00", primary: "#141A0B", secondary: "#D4F53C", accent: "#141A0B", heroBg: "#D4F53C", onHero: "#141A0B",
      barBg: "#D4F53C", onBar: "#141A0B", footerBg: "#141A0B", onFooter: "#D4F53C", open: "#2A7A1E", closed: "#B3261E",
    },
    fonts: { heading: f("outfit", [800]), body: f("onest", [400, 700]) },
    headingWeight: 800,
    radius: 12,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Inspection-ready cars rolling out of the bay, green check marks, smiling customers with keys; punchy daylight.",
  },
  "auto.orange_crush": {
    id: "auto.orange_crush",
    name: "Orange Crush",
    category: "auto",
    layout: "poster",
    palette: {
      bg: "#FF6B1A", surface: "#FFFFFF", band: "#FF8C42", text: "#111111", muted: "#3A1600", heading: "#111111",
      link: "#3A1600", primary: "#1846E8", secondary: "#111111", accent: "#111111", heroBg: "#111111", onHero: "#FF6B1A",
      barBg: "#111111", onBar: "#FF8C42", footerBg: "#111111", onFooter: "#FFB380", open: "#1A6B32", closed: "#B3261E",
    },
    fonts: { heading: f("archivo", [900]), body: f("asap", [400, 700]) },
    headingWeight: 900,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "flat", badge: "stamp", priceList: "cards", spacing: "dense" },
    photoDirection: "Bold, colorful shop shots: orange jacks and lifts, tools hung on pegboard, sparks from a grinder.",
  },
  "auto.teal_turbo": {
    id: "auto.teal_turbo",
    name: "Teal Turbo",
    category: "auto",
    layout: "minimal",
    palette: {
      bg: "#00646D", surface: "#005860", band: "#004C53", text: "#FFFFFF", muted: "#D2F0F2", heading: "#FFFFFF",
      link: "#FFDA80", primary: "#FFD166", secondary: "#EF476F", accent: "#FFD166", heroBg: "#00393F", onHero: "#FFFFFF",
      barBg: "#00393F", onBar: "#FFFFFF", footerBg: "#00393F", onFooter: "#BFE6E9", open: "#B8FFD9", closed: "#FFD1C9",
    },
    fonts: { heading: f("josefin-sans", [700]), body: f("albert-sans", [400, 700]) },
    headingWeight: 700,
    radius: 14,
    button: "pill",
    knobs: { hero: "dark", divider: "rule", label: "small_caps", card: "shadow", badge: "seal", priceList: "cards", spacing: "standard" },
    photoDirection: "Imports and tuners, turbo and intake close-ups, wheels and wraps; cool teal shadows with warm highlights.",
  },
};
