import { f } from "../look-kit.ts";
import type { LookDef } from "../themes.ts";

/** Churches & nonprofits looks (colors + fonts). Contrast is checked at build by resolveTheme; see test/designs.test.ts. */
export const CHURCH_LOOKS: Record<string, LookDef> = {
  // ── The four from research/churches-nonprofits.md §11 ─────────────────
  "church.hymnal": {
    id: "church.hymnal",
    name: "Hymnal",
    category: "church",
    layout: "split",
    palette: {
      bg: "#F5F2EA", surface: "#FFFDF8", band: "#E8E0D2", text: "#22252B", muted: "#4F535A", heading: "#1E3A5C",
      link: "#1E3A5C", primary: "#1E3A5C", secondary: "#DCCCA8", accent: "#B8964E", heroBg: "#E8E0D2", onHero: "#22252B",
      barBg: "#FFFDF8", onBar: "#1E3A5C", footerBg: "#1E3A5C", onFooter: "#F5F2EA", open: "#2E6B3A", closed: "#7A2E2E",
    },
    fonts: { heading: f("crimson-pro", [600]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 600,
    radius: 2,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "ruled", badge: "seal", priceList: "leaders", spacing: "airy" },
    photoDirection: "The church itself in soft morning light: brick or stone, the front doors and steps, the steeple against the sky, the empty sanctuary with light through the windows. No people.",
  },
  "church.country_chapel": {
    id: "church.country_chapel",
    name: "Country Chapel",
    category: "church",
    layout: "classic",
    palette: {
      bg: "#FFFDF8", surface: "#FFFFFF", band: "#F3EADB", text: "#2A2522", muted: "#5A514B", heading: "#2F4F3A",
      link: "#8C2F39", primary: "#8C2F39", secondary: "#DDE7DC", accent: "#B5803A", heroBg: "#F3EADB", onHero: "#2A2522",
      barBg: "#F3EADB", onBar: "#2F4F3A", footerBg: "#2F4F3A", onFooter: "#F3EADB", open: "#2E6B3A", closed: "#8C2F39",
    },
    fonts: { heading: f("lora", [700]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 700,
    radius: 8,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "none", card: "bordered", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "The white chapel from the road: clapboard, the red front door, the gravel lot and the oaks around it, the fellowship hall, the empty pews. No people.",
  },
  "church.open_doors": {
    id: "church.open_doors",
    name: "Open Doors",
    category: "church",
    layout: "poster",
    palette: {
      bg: "#FCFBF8", surface: "#FFFFFF", band: "#EEF2F1", text: "#18181B", muted: "#4B4F55", heading: "#18181B",
      link: "#0E5C63", primary: "#157A84", secondary: "#F2B544", accent: "#F2B544", heroBg: "#1E2430", onHero: "#F5F3EE",
      barBg: "#FFFFFF", onBar: "#18181B", footerBg: "#1E2430", onFooter: "#F5F3EE", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("plus-jakarta-sans", [800]), body: f("inter", [400, 700]) },
    headingWeight: 800,
    radius: 16,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "The building at dusk with the lights on, the stage and room before a service, open doors from the parking lot. Real and unstaged; no people.",
  },
  "church.meeting_hall": {
    id: "church.meeting_hall",
    name: "Meeting Hall",
    category: "church",
    layout: "overlap",
    palette: {
      bg: "#F7F6F2", surface: "#FFFFFF", band: "#E6E9EE", text: "#1F2933", muted: "#4A5561", heading: "#1D3557",
      link: "#1D3557", primary: "#1D3557", secondary: "#F1E6CC", accent: "#E07A5F", heroBg: "#E6E9EE", onHero: "#1F2933",
      barBg: "#E6E9EE", onBar: "#1D3557", footerBg: "#1D3557", onFooter: "#F7F6F2", open: "#2F6B3B", closed: "#A63A2A",
    },
    fonts: { heading: f("zilla-slab", [700]), body: f("public-sans", [400, 700]) },
    headingWeight: 700,
    radius: 4,
    button: "square",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "The post, club hall or pantry building with its sign, the hall set up with tables and chairs, the pantry shelves stocked. No people.",
  },

  // ── Traditional / stately ─────────────────────────────────────────────
  "church.steeple_hill": {
    id: "church.steeple_hill",
    name: "Steeple Hill",
    category: "church",
    layout: "poster",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EEF1F5", text: "#1D232B", muted: "#4C5560", heading: "#23324A",
      link: "#2D4F7C", primary: "#C8922F", secondary: "#23324A", accent: "#C8922F", heroBg: "#23324A", onHero: "#F7F4EC",
      barBg: "#23324A", onBar: "#F7F4EC", footerBg: "#23324A", onFooter: "#EEF1F5", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("playfair-display", [700]), body: f("lato", [400, 700]) },
    headingWeight: 700,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "The white steeple against a clear blue sky, shot from below; the front of the church from across the lawn. No people.",
  },
  "church.evensong": {
    id: "church.evensong",
    name: "Evensong",
    category: "church",
    layout: "editorial",
    palette: {
      bg: "#15201B", surface: "#1E2B25", band: "#1A2620", text: "#EEE9DC", muted: "#BCC2B6", heading: "#EBD49A",
      link: "#E6C673", primary: "#E2BC5E", secondary: "#2F4A3C", accent: "#C9A24A", heroBg: "#0F1714", onHero: "#F3EEE1",
      barBg: "#0F1714", onBar: "#F3EEE1", footerBg: "#0C1310", onFooter: "#DCD7C9", open: "#8FD3A2", closed: "#F2A08F",
    },
    fonts: { heading: f("marcellus", [400]), body: f("spectral", [400, 700]) },
    headingWeight: 400,
    radius: 4,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "small_caps", card: "bordered", badge: "seal", priceList: "leaders", spacing: "airy" },
    photoDirection: "The sanctuary in the evening: lamps lit, stained glass glowing from inside, the building at dusk against dark trees. No people.",
  },
  "church.bell_tower": {
    id: "church.bell_tower",
    name: "Bell Tower",
    category: "church",
    layout: "overlap",
    palette: {
      bg: "#FAF6F0", surface: "#FFFFFF", band: "#F0E5DC", text: "#2A2220", muted: "#5C4F4A", heading: "#5C1D22",
      link: "#7A2430", primary: "#7A2430", secondary: "#E6D2B5", accent: "#B48A4A", heroBg: "#F0E5DC", onHero: "#2A2220",
      barBg: "#FFFFFF", onBar: "#5C1D22", footerBg: "#2A2220", onFooter: "#F0E5DC", open: "#2E6B3A", closed: "#7A2430",
    },
    fonts: { heading: f("libre-baskerville", [700]), body: f("mulish", [400, 700]) },
    headingWeight: 700,
    radius: 6,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "shadow", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Red brick and the bell tower in late-afternoon light, arched windows, the front doors open to the street. No people.",
  },
  "church.cornerstone": {
    id: "church.cornerstone",
    name: "Cornerstone",
    category: "church",
    layout: "classic",
    palette: {
      bg: "#F1F0EC", surface: "#FBFAF8", band: "#E2E0DA", text: "#22272C", muted: "#4E545A", heading: "#2B3138",
      link: "#3A4E63", primary: "#3A4651", secondary: "#D8C29A", accent: "#9C7A4C", heroBg: "#E2E0DA", onHero: "#22272C",
      barBg: "#FBFAF8", onBar: "#2B3138", footerBg: "#2B3138", onFooter: "#E2E0DA", open: "#2E6B3A", closed: "#A03A2A",
    },
    fonts: { heading: f("eb-garamond", [600]), body: f("work-sans", [400, 700]) },
    headingWeight: 600,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Gray stone walls and the carved cornerstone, the arched entry, quiet overcast light. No people.",
  },
  "church.rose_window": {
    id: "church.rose_window",
    name: "Rose Window",
    category: "church",
    layout: "minimal",
    palette: {
      bg: "#FBF9F4", surface: "#FFFFFF", band: "#E9EDF6", text: "#1F2430", muted: "#4C5262", heading: "#22386A",
      link: "#2A4D8F", primary: "#2A4D8F", secondary: "#EED6D9", accent: "#B23A48", heroBg: "#E9EDF6", onHero: "#1F2430",
      barBg: "#E9EDF6", onBar: "#22386A", footerBg: "#22386A", onFooter: "#E9EDF6", open: "#2E6B3A", closed: "#9E2E3B",
    },
    fonts: { heading: f("cormorant-garamond", [700]), body: f("open-sans", [400, 700]) },
    headingWeight: 700,
    radius: 12,
    button: "pill",
    knobs: { hero: "light", divider: "thick_rule", label: "small_caps", card: "flat", badge: "seal", priceList: "cards", spacing: "airy" },
    photoDirection: "Stained glass from inside with sun coming through, the nave and altar rail, color falling on the pews. No people.",
  },
  "church.walnut_pew": {
    id: "church.walnut_pew",
    name: "Walnut Pew",
    category: "church",
    layout: "editorial",
    palette: {
      bg: "#FAF5EE", surface: "#FFFDF9", band: "#EFE3D0", text: "#2B221C", muted: "#5B4E44", heading: "#3B2A1E",
      link: "#7A4A26", primary: "#6B4226", secondary: "#CBD5C0", accent: "#A8763E", heroBg: "#EFE3D0", onHero: "#2B221C",
      barBg: "#EFE3D0", onBar: "#3B2A1E", footerBg: "#3B2A1E", onFooter: "#EFE3D0", open: "#2E6B3A", closed: "#9A3424",
    },
    fonts: { heading: f("old-standard-tt", [700]), body: f("libre-franklin", [400, 700]) },
    headingWeight: 700,
    radius: 3,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "ruled", badge: "plain", priceList: "leaders", spacing: "standard" },
    photoDirection: "Warm wood inside: rows of pews, the pulpit, hymnals in the racks, window light on old floorboards. No people.",
  },

  // ── Warm country ──────────────────────────────────────────────────────
  "church.clapboard": {
    id: "church.clapboard",
    name: "Clapboard",
    category: "church",
    layout: "split",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#E8F2F3", text: "#22303C", muted: "#4C5A66", heading: "#22303C",
      link: "#2C5F8A", primary: "#2C5F8A", secondary: "#A9D6DA", accent: "#9FCFD3", heroBg: "#E1EFF1", onHero: "#22303C",
      barBg: "#FFFFFF", onBar: "#22303C", footerBg: "#22303C", onFooter: "#E8F2F3", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("bitter", [700]), body: f("open-sans", [400, 700]) },
    headingWeight: 700,
    radius: 12,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "White clapboard siding and blue shutters in bright daylight, the porch and front steps, the churchyard. No people.",
  },
  "church.homecoming": {
    id: "church.homecoming",
    name: "Homecoming",
    category: "church",
    layout: "split",
    palette: {
      bg: "#FBF4EA", surface: "#FFFCF6", band: "#F1E2C6", text: "#2D221C", muted: "#5E4E43", heading: "#5A2A1F",
      link: "#9A3A26", primary: "#C0502F", secondary: "#F1D9A8", accent: "#D9A441", heroBg: "#3A2A20", onHero: "#FBF4EA",
      barBg: "#3A2A20", onBar: "#FBF4EA", footerBg: "#3A2A20", onFooter: "#F1E2C6", open: "#2E6B3A", closed: "#9A3A26",
    },
    fonts: { heading: f("arvo", [700]), body: f("cabin", [400, 700]) },
    headingWeight: 700,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "standard" },
    photoDirection: "The church grounds set for dinner on the grounds: long tables under the trees, the pavilion, the old bell. No people.",
  },
  "church.wheat_field": {
    id: "church.wheat_field",
    name: "Wheat Field",
    category: "church",
    layout: "overlap",
    palette: {
      bg: "#FBF7EC", surface: "#FFFDF7", band: "#F2E7C9", text: "#2B2414", muted: "#5A4E35", heading: "#4A3A18",
      link: "#4E5C18", primary: "#56651C", secondary: "#E3BE5C", accent: "#C98E1E", heroBg: "#F2E7C9", onHero: "#2B2414",
      barBg: "#F2E7C9", onBar: "#3A4512", footerBg: "#4A3A18", onFooter: "#F2E7C9", open: "#2E6B3A", closed: "#9A3A26",
    },
    fonts: { heading: f("young-serif", [400]), body: f("karla", [400, 700]) },
    headingWeight: 400,
    radius: 14,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "flat", badge: "sticker", priceList: "cards", spacing: "airy" },
    photoDirection: "The church across an open field in golden late light, fence rows and hay bales, the gravel drive. No people.",
  },
  "church.lantern_light": {
    id: "church.lantern_light",
    name: "Lantern Light",
    category: "church",
    layout: "classic",
    palette: {
      bg: "#211915", surface: "#2C221C", band: "#291F19", text: "#F1E8DA", muted: "#C8BBA8", heading: "#F3C77A",
      link: "#F0B865", primary: "#E8A54B", secondary: "#5A3A28", accent: "#E8A54B", heroBg: "#17110E", onHero: "#F6EEE2",
      barBg: "#17110E", onBar: "#F6EEE2", footerBg: "#140F0C", onFooter: "#E3D8C6", open: "#93D49E", closed: "#F2A08F",
    },
    fonts: { heading: f("domine", [700]), body: f("hind", [400, 700]) },
    headingWeight: 700,
    radius: 8,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "none", card: "bordered", badge: "plain", priceList: "leaders", spacing: "standard" },
    photoDirection: "The church at night with the porch light and windows glowing, a lantern-lit path, the sanctuary lit for an evening service. No people.",
  },
  "church.sunday_supper": {
    id: "church.sunday_supper",
    name: "Sunday Supper",
    category: "church",
    layout: "soft",
    palette: {
      bg: "#FFFDF6", surface: "#FFFFFF", band: "#FAEFC8", text: "#26291F", muted: "#545746", heading: "#2F4A38",
      link: "#2F5D46", primary: "#2F5D46", secondary: "#F2C94C", accent: "#E7B93E", heroBg: "#FAEFC8", onHero: "#26291F",
      barBg: "#FAEFC8", onBar: "#2F4A38", footerBg: "#2F4A38", onFooter: "#FAEFC8", open: "#2E6B3A", closed: "#A33A22",
    },
    fonts: { heading: f("bree-serif", [400]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 400,
    radius: 20,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "flat", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "The fellowship hall ready for Wednesday supper: tables set, the kitchen pass-through, a covered-dish spread before anyone arrives. No people.",
  },

  // ── Modern / young ────────────────────────────────────────────────────
  "church.first_light": {
    id: "church.first_light",
    name: "First Light",
    category: "church",
    layout: "editorial",
    palette: {
      bg: "#12151D", surface: "#1B2030", band: "#181C28", text: "#EEF0F5", muted: "#B3B9C7", heading: "#FFFFFF",
      link: "#F7A866", primary: "#F28C45", secondary: "#2E3A57", accent: "#F2B544", heroBg: "#0B0D13", onHero: "#F5F6FA",
      barBg: "#0B0D13", onBar: "#F5F6FA", footerBg: "#0B0D13", onFooter: "#D6DAE3", open: "#7FD69A", closed: "#F59A8C",
    },
    fonts: { heading: f("outfit", [800]), body: f("dm-sans", [400, 700]) },
    headingWeight: 800,
    radius: 14,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "flat", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Sunrise behind the building, the stage lit before a service, string lights over the patio. Wide, moody, no people.",
  },
  "church.upper_room": {
    id: "church.upper_room",
    name: "Upper Room",
    category: "church",
    layout: "split",
    palette: {
      bg: "#1D1424", surface: "#281C31", band: "#24192C", text: "#F4ECFA", muted: "#C8B9D4", heading: "#F4ECFA",
      link: "#F7A9A1", primary: "#F28B82", secondary: "#4A2E5C", accent: "#C7A3F5", heroBg: "#150E1B", onHero: "#F7F0FB",
      barBg: "#150E1B", onBar: "#F7F0FB", footerBg: "#120C17", onFooter: "#DCCFE6", open: "#8FD8A8", closed: "#F7A9A1",
    },
    fonts: { heading: f("sora", [700]), body: f("figtree", [400, 700]) },
    headingWeight: 700,
    radius: 22,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "none", card: "shadow", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "The worship room lit low in purple and warm light, chairs set out, the room upstairs or the youth space before a service. No people.",
  },
  "church.new_song": {
    id: "church.new_song",
    name: "New Song",
    category: "church",
    layout: "minimal",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EEF3FF", text: "#141A2B", muted: "#4A5268", heading: "#141A2B",
      link: "#1F55D1", primary: "#2563EB", secondary: "#141A2B", accent: "#FFB547", heroBg: "#E3ECFF", onHero: "#141A2B",
      barBg: "#141A2B", onBar: "#FFFFFF", footerBg: "#141A2B", onFooter: "#E3ECFF", open: "#1F6B3A", closed: "#B42318",
    },
    fonts: { heading: f("unbounded", [700]), body: f("instrument-sans", [400, 700]) },
    headingWeight: 700,
    radius: 10,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "bordered", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Clean daylight shots of the building, a bright lobby and coffee bar, the room set for Sunday. No people.",
  },
  "church.open_range": {
    id: "church.open_range",
    name: "Open Range",
    category: "church",
    layout: "poster",
    palette: {
      bg: "#F5EFE4", surface: "#FFFBF4", band: "#EADFCB", text: "#2A2018", muted: "#5A4C3E", heading: "#1F2833",
      link: "#9A4318", primary: "#BD5629", secondary: "#1F2833", accent: "#C2582A", heroBg: "#1F2833", onHero: "#F5EFE4",
      barBg: "#1F2833", onBar: "#F5EFE4", footerBg: "#1F2833", onFooter: "#EADFCB", open: "#2E6B3A", closed: "#9A3A26",
    },
    fonts: { heading: f("staatliches", [400]), body: f("barlow", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "cards", spacing: "dense" },
    photoDirection: "The metal building or arena with pasture around it, the barn doors open, the riding pen and big sky. No people.",
  },

  // ── Civic: posts, clubs, pantries, community centers ─────────────────
  "church.honor_roll": {
    id: "church.honor_roll",
    name: "Honor Roll",
    category: "church",
    layout: "classic",
    palette: {
      bg: "#121B29", surface: "#1B2638", band: "#172233", text: "#EDEFF2", muted: "#B5BDC9", heading: "#FFFFFF",
      link: "#F0937A", primary: "#E07A5F", secondary: "#2B3F5E", accent: "#E07A5F", heroBg: "#0C131E", onHero: "#F3F5F8",
      barBg: "#0C131E", onBar: "#F3F5F8", footerBg: "#0A1019", onFooter: "#D5DAE2", open: "#85D49C", closed: "#F59A8C",
    },
    fonts: { heading: f("oswald", [600]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 600,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "The post home or hall at dusk with its sign lit, the memorial stone or flagpole base, the meeting room set up. No people.",
  },
  "church.harvest_table": {
    id: "church.harvest_table",
    name: "Harvest Table",
    category: "church",
    layout: "split",
    palette: {
      bg: "#FAF6EC", surface: "#FFFFFF", band: "#F1E6CC", text: "#232A20", muted: "#525A48", heading: "#24502E",
      link: "#2F6B3B", primary: "#2F6B3B", secondary: "#E2C26E", accent: "#D9A441", heroBg: "#F1E6CC", onHero: "#232A20",
      barBg: "#FFFFFF", onBar: "#24502E", footerBg: "#24502E", onFooter: "#F1E6CC", open: "#2F6B3B", closed: "#9A3A26",
    },
    fonts: { heading: f("rokkitt", [700]), body: f("libre-franklin", [400, 700]) },
    headingWeight: 700,
    radius: 8,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Stocked pantry shelves, crates of produce, the community garden, the building's front door with the hours sign. No people.",
  },
  "church.field_jacket": {
    id: "church.field_jacket",
    name: "Field Jacket",
    category: "church",
    layout: "overlap",
    palette: {
      bg: "#F1EDE0", surface: "#FBF9F2", band: "#E2DBC4", text: "#23271E", muted: "#4F5444", heading: "#33402A",
      link: "#4A5A2C", primary: "#C98420", secondary: "#33402A", accent: "#C98420", heroBg: "#2F3824", onHero: "#F1EDE0",
      barBg: "#2F3824", onBar: "#F1EDE0", footerBg: "#2F3824", onFooter: "#E2DBC4", open: "#2E6B3A", closed: "#9A3A26",
    },
    fonts: { heading: f("saira-condensed", [700]), body: f("ibm-plex-sans", [400, 700]) },
    headingWeight: 700,
    radius: 4,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "The lodge or club building with its sign, the hall with long tables and folding chairs, the grill pavilion out back. No people.",
  },

  // ── Soft / gentle ─────────────────────────────────────────────────────
  "church.still_waters": {
    id: "church.still_waters",
    name: "Still Waters",
    category: "church",
    layout: "soft",
    palette: {
      bg: "#F7FAFC", surface: "#FFFFFF", band: "#E4EFF7", text: "#1B2A38", muted: "#4A5866", heading: "#1E4566",
      link: "#22608E", primary: "#4F98CF", secondary: "#1E4566", accent: "#9CC8E6", heroBg: "#E4EFF7", onHero: "#1B2A38",
      barBg: "#1E4566", onBar: "#FFFFFF", footerBg: "#1E4566", onFooter: "#E4EFF7", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("quicksand", [700]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 700,
    radius: 24,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Calm and open: the church by a pond or creek, soft blue sky, light through tall clear windows. No people.",
  },
  "church.lilac_lane": {
    id: "church.lilac_lane",
    name: "Lilac Lane",
    category: "church",
    layout: "editorial",
    palette: {
      bg: "#FCFAFF", surface: "#FFFFFF", band: "#F0EAF8", text: "#2A2338", muted: "#585068", heading: "#44336B",
      link: "#5E4596", primary: "#6A4FA3", secondary: "#DCCBF2", accent: "#C9B3EA", heroBg: "#F0EAF8", onHero: "#2A2338",
      barBg: "#FFFFFF", onBar: "#44336B", footerBg: "#44336B", onFooter: "#F0EAF8", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("josefin-sans", [600]), body: f("mulish", [400, 700]) },
    headingWeight: 600,
    radius: 20,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "flat", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Spring at the church: blooming shrubs along the walk, the chapel doorway, soft overcast light on the sanctuary. No people.",
  },
  "church.quiet_meadow": {
    id: "church.quiet_meadow",
    name: "Quiet Meadow",
    category: "church",
    layout: "minimal",
    palette: {
      bg: "#F8F9F4", surface: "#FFFFFF", band: "#E9EFE4", text: "#232B24", muted: "#505A51", heading: "#2F4A3A",
      link: "#3D6650", primary: "#4E7A5E", secondary: "#D5E2CC", accent: "#A9C2A0", heroBg: "#E9EFE4", onHero: "#232B24",
      barBg: "#FFFFFF", onBar: "#2F4A3A", footerBg: "#2F4A3A", onFooter: "#E9EFE4", open: "#2E6B3A", closed: "#A33A22",
    },
    fonts: { heading: f("fraunces", [500]), body: f("figtree", [400, 700]) },
    headingWeight: 500,
    radius: 18,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Green lawns and old trees around the church, the prayer garden or cemetery path in soft light, a bench by the walk. No people.",
  },
};
