import { f } from "../look-kit.ts";
import type { LookDef } from "../themes.ts";

/** More cleaning looks (colors + fonts). Contrast is checked at build by resolveTheme; see test/designs.test.ts. */
export const CLEANING_LOOKS: Record<string, LookDef> = {
  // ── Dark ──────────────────────────────────────────────────────────────
  "cleaning.midnight_shine": {
    id: "cleaning.midnight_shine",
    name: "Midnight Shine",
    category: "cleaning",
    layout: "split",
    palette: {
      bg: "#0F1B2D", surface: "#182840", band: "#132237", text: "#EEF3F9", muted: "#A9B7C9", heading: "#FFFFFF",
      link: "#7FE0D6", primary: "#4FD1C5", secondary: "#EEF3F9", accent: "#4FD1C5", heroBg: "#0A1424", onHero: "#FFFFFF",
      barBg: "#0A1424", onBar: "#FFFFFF", footerBg: "#08101C", onFooter: "#CBD6E4", open: "#86E3A8", closed: "#FFA8A0",
    },
    fonts: { heading: f("montserrat", [800]), body: f("open-sans", [400, 700]) },
    headingWeight: 800,
    radius: 10,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "bordered", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "After-hours commercial cleaning: gleaming lobby floors and offices at night, cool blue grade.",
  },
  "cleaning.evergreen_crew": {
    id: "cleaning.evergreen_crew",
    name: "Evergreen Crew",
    category: "cleaning",
    layout: "classic",
    palette: {
      bg: "#13281F", surface: "#1D3529", band: "#182F24", text: "#EEF4EE", muted: "#B0C3B6", heading: "#F4C95D",
      link: "#F4C95D", primary: "#F4C95D", secondary: "#EEF4EE", accent: "#F4C95D", heroBg: "#0E1F17", onHero: "#EEF4EE",
      barBg: "#0E1F17", onBar: "#EEF4EE", footerBg: "#0B1912", onFooter: "#D0DDD3", open: "#9BE0AE", closed: "#F7AFA4",
    },
    fonts: { heading: f("roboto-slab", [700]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 700,
    radius: 4,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "The crew in matching shirts by the van, eco products lined up, warm late-afternoon light.",
  },
  "cleaning.charcoal_pro": {
    id: "cleaning.charcoal_pro",
    name: "Charcoal Pro",
    category: "cleaning",
    layout: "poster",
    palette: {
      bg: "#1A1D21", surface: "#24282E", band: "#202328", text: "#F1F2F4", muted: "#AEB4BC", heading: "#FFFFFF",
      link: "#FFD84D", primary: "#FFD400", secondary: "#F1F2F4", accent: "#FFD400", heroBg: "#111316", onHero: "#FFFFFF",
      barBg: "#111316", onBar: "#FFFFFF", footerBg: "#0C0D0F", onFooter: "#D2D6DB", open: "#8FE3A5", closed: "#FF9E94",
    },
    fonts: { heading: f("barlow-condensed", [800]), body: f("barlow", [400, 700]) },
    headingWeight: 800,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "dense" },
    photoDirection: "Pressure-washing action: the clean stripe across a dirty driveway, spray mist, rigs and hoses.",
  },
  "cleaning.deep_sea": {
    id: "cleaning.deep_sea",
    name: "Deep Sea",
    category: "cleaning",
    layout: "soft",
    palette: {
      bg: "#0B2E33", surface: "#12404A", band: "#0F3840", text: "#E8F6F5", muted: "#A6C9C8", heading: "#E8F6F5",
      link: "#8FEADF", primary: "#7FE3D6", secondary: "#FFD6A5", accent: "#7FE3D6", heroBg: "#082428", onHero: "#E8F6F5",
      barBg: "#072024", onBar: "#E8F6F5", footerBg: "#061B1E", onFooter: "#C8E2E0", open: "#9BE7B2", closed: "#FFB3A8",
    },
    fonts: { heading: f("outfit", [600]), body: f("atkinson-hyperlegible", [400, 700]) },
    headingWeight: 600,
    radius: 22,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "none", card: "flat", badge: "plain", priceList: "cards", spacing: "airy" },
    photoDirection: "Calm and spotless: water beading on glass, sparkling tile and fixtures, cool teal tones.",
  },
  "cleaning.plum_polish": {
    id: "cleaning.plum_polish",
    name: "Plum Polish",
    category: "cleaning",
    layout: "overlap",
    palette: {
      bg: "#24152B", surface: "#33203C", band: "#2C1A34", text: "#F5ECF6", muted: "#C8B4CB", heading: "#F7C6E3",
      link: "#F7A8D8", primary: "#F7A8D8", secondary: "#F5ECF6", accent: "#B7E4C7", heroBg: "#1B0F21", onHero: "#F5ECF6",
      barBg: "#1B0F21", onBar: "#F5ECF6", footerBg: "#160C1B", onFooter: "#E2D2E4", open: "#9FE3B5", closed: "#FFB2B2",
    },
    fonts: { heading: f("kanit", [600]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 600,
    radius: 16,
    button: "pill",
    knobs: { hero: "dark", divider: "rule", label: "small_caps", card: "bordered", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Owner-led and personal: styled shelves, fresh flowers on a clean table, moody evening interiors.",
  },

  // ── Crisp white ───────────────────────────────────────────────────────
  "cleaning.spring_rain": {
    id: "cleaning.spring_rain",
    name: "Spring Rain",
    category: "cleaning",
    layout: "minimal",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EEF5FC", text: "#16253A", muted: "#4A5A6E", heading: "#16253A",
      link: "#1D5FD1", primary: "#1D5FD1", secondary: "#DDEBFB", accent: "#7DB8F5", heroBg: "#EEF5FC", onHero: "#16253A",
      barBg: "#16253A", onBar: "#FFFFFF", footerBg: "#EEF5FC", onFooter: "#16253A", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("lexend", [600]), body: f("dm-sans", [400, 700]) },
    headingWeight: 600,
    radius: 12,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "flat", badge: "plain", priceList: "cards", spacing: "airy" },
    photoDirection: "Light and airy rooms, open windows, sheer curtains, pale blue and white with lots of space.",
  },
  "cleaning.squeaky_clean": {
    id: "cleaning.squeaky_clean",
    name: "Squeaky Clean",
    category: "cleaning",
    layout: "soft",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#E7F8F1", text: "#14281F", muted: "#46594F", heading: "#14281F",
      link: "#0B7A55", primary: "#12B886", secondary: "#14281F", accent: "#FFD43B", heroBg: "#E7F8F1", onHero: "#14281F",
      barBg: "#14281F", onBar: "#FFFFFF", footerBg: "#0B4A36", onFooter: "#E7F8F1", open: "#0B7A55", closed: "#B42318",
    },
    fonts: { heading: f("rubik", [700]), body: f("karla", [400, 700]) },
    headingWeight: 700,
    radius: 20,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Friendly and bright: smiling cleaners, gloves and caddies, shiny sinks, cheerful daylight.",
  },
  "cleaning.office_hours": {
    id: "cleaning.office_hours",
    name: "Office Hours",
    category: "cleaning",
    layout: "minimal",
    palette: {
      bg: "#FFFFFF", surface: "#F6F8FA", band: "#EBEFF4", text: "#1A2433", muted: "#4B5768", heading: "#0B3D91",
      link: "#0B3D91", primary: "#17784A", secondary: "#0B3D91", accent: "#00A3AD", heroBg: "#0B3D91", onHero: "#FFFFFF",
      barBg: "#0B3D91", onBar: "#FFFFFF", footerBg: "#1A2433", onFooter: "#E3E8EF", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("ibm-plex-sans", [600]), body: f("public-sans", [400, 700]) },
    headingWeight: 600,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "leaders", spacing: "dense" },
    photoDirection: "Offices, clinics, churches and showrooms, straight-on and evenly lit, uniformed staff at work.",
  },
  "cleaning.crisp_cotton": {
    id: "cleaning.crisp_cotton",
    name: "Crisp Cotton",
    category: "cleaning",
    layout: "editorial",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F5F3EF", text: "#23292F", muted: "#59616A", heading: "#2C3E50",
      link: "#2C5A7A", primary: "#2C3E50", secondary: "#E7E2D8", accent: "#B9A88C", heroBg: "#F5F3EF", onHero: "#23292F",
      barBg: "#F5F3EF", onBar: "#23292F", footerBg: "#2C3E50", onFooter: "#F5F3EF", open: "#2E6B3A", closed: "#9E3B2C",
    },
    fonts: { heading: f("libre-baskerville", [700]), body: f("lato", [400, 700]) },
    headingWeight: 700,
    radius: 6,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "ruled", badge: "seal", priceList: "leaders", spacing: "airy" },
    photoDirection: "Tidy, well-kept homes: crisp bedding, polished wood, neat pantries, soft neutral daylight.",
  },
  "cleaning.morning_fresh": {
    id: "cleaning.morning_fresh",
    name: "Morning Fresh",
    category: "cleaning",
    layout: "classic",
    palette: {
      bg: "#FFFFFF", surface: "#FFFDF5", band: "#FFF7D6", text: "#1B2B22", muted: "#4D5A52", heading: "#1B4332",
      link: "#1B6B45", primary: "#FFD23F", secondary: "#1B4332", accent: "#FFD23F", heroBg: "#1B4332", onHero: "#FFFFFF",
      barBg: "#1B4332", onBar: "#FFFFFF", footerBg: "#1B4332", onFooter: "#FFF7D6", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("poppins", [700]), body: f("mulish", [400, 700]) },
    headingWeight: 700,
    radius: 8,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Sunny kitchens and lemon-fresh counters, green plants, cleaners mid-task in morning light.",
  },

  // ── Warm and tinted light ─────────────────────────────────────────────
  "cleaning.clear_skies": {
    id: "cleaning.clear_skies",
    name: "Clear Skies",
    category: "cleaning",
    layout: "overlap",
    palette: {
      bg: "#EAF4FB", surface: "#FFFFFF", band: "#D7EAF7", text: "#142838", muted: "#44596B", heading: "#0E4F7A",
      link: "#0E5E91", primary: "#0E6BA8", secondary: "#FFB86B", accent: "#FFB86B", heroBg: "#D7EAF7", onHero: "#142838",
      barBg: "#142838", onBar: "#FFFFFF", footerBg: "#142838", onFooter: "#D7EAF7", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("red-hat-display", [800]), body: f("red-hat-text", [400, 700]) },
    headingWeight: 800,
    radius: 14,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "shadow", badge: "seal", priceList: "cards", spacing: "standard" },
    photoDirection: "Streak-free windows with blue sky behind, bright glass and screens, outdoor daylight.",
  },
  "cleaning.sage_soap": {
    id: "cleaning.sage_soap",
    name: "Sage & Soap",
    category: "cleaning",
    layout: "editorial",
    palette: {
      bg: "#EEF3EC", surface: "#FBFCFA", band: "#DFE8DB", text: "#212B24", muted: "#4E5B52", heading: "#2F5440",
      link: "#2F6B4A", primary: "#3F6B4F", secondary: "#212B24", accent: "#9DBB9A", heroBg: "#DFE8DB", onHero: "#212B24",
      barBg: "#212B24", onBar: "#FFFFFF", footerBg: "#2F5440", onFooter: "#EEF3EC", open: "#2E6B3A", closed: "#9E3B2C",
    },
    fonts: { heading: f("young-serif", [400]), body: f("cabin", [400, 700]) },
    headingWeight: 400,
    radius: 20,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Green cleaning: glass spray bottles, eucalyptus, cotton cloths and plants in soft daylight.",
  },
  "cleaning.lavender_fields": {
    id: "cleaning.lavender_fields",
    name: "Lavender Fields",
    category: "cleaning",
    layout: "split",
    palette: {
      bg: "#F2EFFA", surface: "#FFFFFF", band: "#E4DEF5", text: "#221C3A", muted: "#554D6E", heading: "#3E2A82",
      link: "#5B3FA8", primary: "#5B3FA8", secondary: "#CFE9D9", accent: "#A792E0", heroBg: "#E4DEF5", onHero: "#221C3A",
      barBg: "#221C3A", onBar: "#FFFFFF", footerBg: "#3E2A82", onFooter: "#F2EFFA", open: "#1F6B4A", closed: "#A8322A",
    },
    fonts: { heading: f("urbanist", [800]), body: f("figtree", [400, 700]) },
    headingWeight: 800,
    radius: 10,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "bordered", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Fresh laundry and folded linens, lavender sprigs, calm bedrooms in soft cool light.",
  },
  "cleaning.mint_condition": {
    id: "cleaning.mint_condition",
    name: "Mint Condition",
    category: "cleaning",
    layout: "overlap",
    palette: {
      bg: "#E8F7F1", surface: "#FFFFFF", band: "#D2EFE3", text: "#12302A", muted: "#43625A", heading: "#0B5C47",
      link: "#0B6B53", primary: "#FF9B85", secondary: "#0B7A5E", accent: "#FF9B85", heroBg: "#0B5C47", onHero: "#E8F7F1",
      barBg: "#12302A", onBar: "#FFFFFF", footerBg: "#12302A", onFooter: "#D2EFE3", open: "#0B6B53", closed: "#A8322A",
    },
    fonts: { heading: f("quicksand", [700]), body: f("hanken-grotesk", [400, 700]) },
    headingWeight: 700,
    radius: 24,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "none", card: "shadow", badge: "sticker", priceList: "cards", spacing: "airy" },
    photoDirection: "Move-out ready: empty rooms with gleaming floors, spotless appliances, keys on a clean counter.",
  },
  "cleaning.sweet_tea": {
    id: "cleaning.sweet_tea",
    name: "Sweet Tea",
    category: "cleaning",
    layout: "classic",
    palette: {
      bg: "#F7EEDC", surface: "#FFFBF2", band: "#EEDFC2", text: "#2A2118", muted: "#5B4D3E", heading: "#6E3A16",
      link: "#8A4B1F", primary: "#8A4B1F", secondary: "#2A2118", accent: "#D9A44A", heroBg: "#EEDFC2", onHero: "#2A2118",
      barBg: "#2A2118", onBar: "#F7EEDC", footerBg: "#2A2118", onFooter: "#EEDFC2", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("bitter", [700]), body: f("libre-franklin", [400, 700]) },
    headingWeight: 700,
    radius: 6,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "small_caps", card: "bordered", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "Southern homes and porches, warm wood floors, a family-run team, golden afternoon light.",
  },
  "cleaning.rosewater": {
    id: "cleaning.rosewater",
    name: "Rosewater",
    category: "cleaning",
    layout: "minimal",
    palette: {
      bg: "#FCEEE8", surface: "#FFFFFF", band: "#F7DDD3", text: "#33201C", muted: "#664A44", heading: "#8C3B33",
      link: "#A8473A", primary: "#A8473A", secondary: "#33201C", accent: "#E8A598", heroBg: "#F7DDD3", onHero: "#33201C",
      barBg: "#33201C", onBar: "#FCEEE8", footerBg: "#8C3B33", onFooter: "#FCEEE8", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("spectral", [600]), body: f("work-sans", [400, 700]) },
    headingWeight: 600,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Gentle and homey: bathrooms with fresh towels, rose-toned walls, soft window light.",
  },

  // ── Bold and pastel ───────────────────────────────────────────────────
  "cleaning.bubble_bath": {
    id: "cleaning.bubble_bath",
    name: "Bubble Bath",
    category: "cleaning",
    layout: "soft",
    palette: {
      bg: "#E6F4FF", surface: "#FFFFFF", band: "#FFE3F1", text: "#1E2350", muted: "#4D5280", heading: "#1E2350",
      link: "#3B3FC4", primary: "#3B3FC4", secondary: "#FF8CC6", accent: "#FF8CC6", heroBg: "#CDE9FF", onHero: "#1E2350",
      barBg: "#1E2350", onBar: "#FFFFFF", footerBg: "#1E2350", onFooter: "#E6F4FF", open: "#1F6B4A", closed: "#A8322A",
    },
    fonts: { heading: f("righteous", [400]), body: f("outfit", [400, 700]) },
    headingWeight: 400,
    radius: 28,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Playful pastel shots: suds and bubbles, bright gloves and sponges, spotless tubs from above.",
  },
  "cleaning.power_wash": {
    id: "cleaning.power_wash",
    name: "Power Wash",
    category: "cleaning",
    layout: "poster",
    palette: {
      bg: "#F2F6FF", surface: "#FFFFFF", band: "#DCE6FF", text: "#0D1633", muted: "#3F4A6B", heading: "#0047FF",
      link: "#0038CC", primary: "#FF5A1F", secondary: "#0047FF", accent: "#FF5A1F", heroBg: "#0047FF", onHero: "#FFFFFF",
      barBg: "#0D1633", onBar: "#FFFFFF", footerBg: "#0D1633", onFooter: "#DCE6FF", open: "#1F6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("bebas-neue", [400]), body: f("roboto-condensed", [400, 700]) },
    headingWeight: 400,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "dense" },
    photoDirection: "Before/after splits of siding, decks and roofs, high-pressure spray against blue sky, punchy color.",
  },
  "cleaning.lime_twist": {
    id: "cleaning.lime_twist",
    name: "Lime Twist",
    category: "cleaning",
    layout: "split",
    palette: {
      bg: "#D8F57A", surface: "#FFFFFF", band: "#ECFBB8", text: "#142010", muted: "#3A4A20", heading: "#142010",
      link: "#2B4E00", primary: "#142010", secondary: "#2F6B2F", accent: "#FF6B6B", heroBg: "#D8F57A", onHero: "#142010",
      barBg: "#2F6B2F", onBar: "#FFFFFF", footerBg: "#142010", onFooter: "#D8F57A", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("bricolage-grotesque", [800]), body: f("manrope", [400, 700]) },
    headingWeight: 800,
    radius: 14,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Zesty and modern: citrus, green bottles and microfiber on white counters, bright flat light.",
  },
  "cleaning.mop_bucket": {
    id: "cleaning.mop_bucket",
    name: "Mop & Bucket",
    category: "cleaning",
    layout: "poster",
    palette: {
      bg: "#FFCF33", surface: "#FFFFFF", band: "#FFE27A", text: "#14213D", muted: "#3D3A26", heading: "#14213D",
      link: "#14213D", primary: "#C62A1A", secondary: "#FFFFFF", accent: "#14213D", heroBg: "#14213D", onHero: "#FFCF33",
      barBg: "#14213D", onBar: "#FFFFFF", footerBg: "#14213D", onFooter: "#FFE27A", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("archivo-black", [400]), body: f("archivo", [400, 700]) },
    headingWeight: 400,
    radius: 4,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "Hard-working and dependable: yellow carts and wet-floor signs, crews at work, direct even light.",
  },
  "cleaning.retro_suds": {
    id: "cleaning.retro_suds",
    name: "Retro Suds",
    category: "cleaning",
    layout: "editorial",
    palette: {
      bg: "#CFEFEA", surface: "#FFFDF7", band: "#FCE3D5", text: "#1F2B2E", muted: "#4A5759", heading: "#A82D38",
      link: "#A82D38", primary: "#F7A072", secondary: "#A82D38", accent: "#E8505B", heroBg: "#CFEFEA", onHero: "#1F2B2E",
      barBg: "#1F2B2E", onBar: "#FFFDF7", footerBg: "#A82D38", onFooter: "#FFFDF7", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("patua-one", [400]), body: f("asap", [400, 700]) },
    headingWeight: 400,
    radius: 18,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "bordered", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "Retro charm: checkered floors, chrome and pastel appliances, vintage-styled props, warm film tone.",
  },
};
