import { f } from "../look-kit.ts";
import type { LookDef } from "../themes.ts";

/** More contractor looks (colors + fonts). Contrast is checked at build by resolveTheme; see test/designs.test.ts. */
export const CONTRACTOR_LOOKS: Record<string, LookDef> = {
  // ---- dark ----
  "contractor.iron_works": {
    id: "contractor.iron_works",
    name: "Iron Works",
    category: "contractor",
    layout: "poster",
    palette: {
      bg: "#1C1E21", surface: "#26292D", band: "#2E3236", text: "#ECEDEE", muted: "#B4B9BE", heading: "#FFFFFF",
      link: "#FFB547", primary: "#FF8A1F", secondary: "#F2F0EA", accent: "#FF8A1F", heroBg: "#111214", onHero: "#FFFFFF",
      barBg: "#111214", onBar: "#FFFFFF", footerBg: "#111214", onFooter: "#C9CDD1", open: "#7BD88F", closed: "#FF8F80",
    },
    fonts: { heading: f("staatliches", [400]), body: f("public-sans", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "dense" },
    photoDirection: "Welds, steel beams and heavy equipment in hard side light; sparks, grit and gloved hands, dark backgrounds.",
  },
  "contractor.night_call": {
    id: "contractor.night_call",
    name: "Night Call",
    category: "contractor",
    layout: "split",
    palette: {
      bg: "#0F1B2D", surface: "#16253B", band: "#1B2D47", text: "#E8EEF6", muted: "#A9B8CC", heading: "#FFFFFF",
      link: "#7CC4FF", primary: "#38B6FF", secondary: "#F5C542", accent: "#38B6FF", heroBg: "#0A1322", onHero: "#FFFFFF",
      barBg: "#0A1322", onBar: "#FFFFFF", footerBg: "#0A1322", onFooter: "#C5D2E3", open: "#6FE0A8", closed: "#FF9C8A",
    },
    fonts: { heading: f("roboto-condensed", [700]), body: f("inter", [400, 700]) },
    headingWeight: 700,
    radius: 8,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "flat", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Service van under a porch light at night, a tech with a headlamp under a sink; cool blue tones, warm practical lights.",
  },
  "contractor.deep_timber": {
    id: "contractor.deep_timber",
    name: "Deep Timber",
    category: "contractor",
    layout: "editorial",
    palette: {
      bg: "#14231C", surface: "#1B2E25", band: "#213A2E", text: "#EAF0E8", muted: "#AFC2B4", heading: "#F4EFD9",
      link: "#E8C26A", primary: "#E8C26A", secondary: "#F4EFD9", accent: "#8BBF6A", heroBg: "#0E1913", onHero: "#F4EFD9",
      barBg: "#0E1913", onBar: "#F4EFD9", footerBg: "#0E1913", onFooter: "#CFDCCF", open: "#8FE3A0", closed: "#FF9F8F",
    },
    fonts: { heading: f("young-serif", [400]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 400,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "small_caps", card: "ruled", badge: "seal", priceList: "leaders", spacing: "airy" },
    photoDirection: "Tall pines and hardwoods, climbers and bucket trucks, cut rounds and split rails; deep greens, morning haze.",
  },
  "contractor.live_wire": {
    id: "contractor.live_wire",
    name: "Live Wire",
    category: "contractor",
    layout: "overlap",
    palette: {
      bg: "#22272E", surface: "#2B313A", band: "#323944", text: "#E6E9ED", muted: "#ADB5BF", heading: "#FFFFFF",
      link: "#FFE14D", primary: "#FFE14D", secondary: "#4DA3FF", accent: "#FFE14D", heroBg: "#1A1E24", onHero: "#FFFFFF",
      barBg: "#1A1E24", onBar: "#FFFFFF", footerBg: "#1A1E24", onFooter: "#C8CED6", open: "#7EE2A0", closed: "#FF9A8B",
    },
    fonts: { heading: f("teko", [600]), body: f("ibm-plex-sans", [400, 700]) },
    headingWeight: 600,
    radius: 4,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "dense" },
    photoDirection: "Panels, breakers and neat wire runs close up, a meter in hand, lit fixtures glowing in a dim room.",
  },
  "contractor.brick_mortar": {
    id: "contractor.brick_mortar",
    name: "Brick & Mortar",
    category: "contractor",
    layout: "classic",
    palette: {
      bg: "#2A1414", surface: "#351B1B", band: "#3F2120", text: "#F3E9E4", muted: "#CDB5AD", heading: "#FFF5EE",
      link: "#F2B38A", primary: "#F2B38A", secondary: "#F3E9E4", accent: "#C8553D", heroBg: "#1E0E0E", onHero: "#FFF5EE",
      barBg: "#1E0E0E", onBar: "#FFF5EE", footerBg: "#1E0E0E", onFooter: "#E0CBC3", open: "#9BE3A8", closed: "#FFA494",
    },
    fonts: { heading: f("bitter", [800]), body: f("lato", [400, 700]) },
    headingWeight: 800,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "small_caps", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Brick, block and stone texture in raking light, trowels and fresh joints, finished steps and chimneys.",
  },

  // ---- crisp white ----
  "contractor.blue_collar": {
    id: "contractor.blue_collar",
    name: "Blue Collar",
    category: "contractor",
    layout: "split",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EEF1F6", text: "#16202C", muted: "#475467", heading: "#0B3A75",
      link: "#0B4FA8", primary: "#F59E0B", secondary: "#16202C", accent: "#F59E0B", heroBg: "#0B3A75", onHero: "#FFFFFF",
      barBg: "#0B3A75", onBar: "#FFFFFF", footerBg: "#16202C", onFooter: "#DCE3EC", open: "#1A7F44", closed: "#B42318",
    },
    fonts: { heading: f("libre-franklin", [800]), body: f("hind", [400, 700]) },
    headingWeight: 800,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "The crew in work shirts beside the trucks, a handshake at a front door; clean daylight, true colors.",
  },
  "contractor.plumb_line": {
    id: "contractor.plumb_line",
    name: "Plumb Line",
    category: "contractor",
    layout: "editorial",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F6F3F1", text: "#1E1B1A", muted: "#57504C", heading: "#1E1B1A",
      link: "#B3261E", primary: "#C8102E", secondary: "#1E1B1A", accent: "#C8102E", heroBg: "#F6F3F1", onHero: "#1E1B1A",
      barBg: "#1E1B1A", onBar: "#FFFFFF", footerBg: "#1E1B1A", onFooter: "#F6F3F1", open: "#1F6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("archivo-black", [400]), body: f("karla", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "plain", priceList: "cards", spacing: "standard" },
    photoDirection: "Graphic, straight-on shots: copper and PEX runs, levels on finished work, white walls and sharp shadows.",
  },
  "contractor.fresh_coat": {
    id: "contractor.fresh_coat",
    name: "Fresh Coat",
    category: "contractor",
    layout: "soft",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F1F5F9", text: "#1A202C", muted: "#4A5568", heading: "#1A202C",
      link: "#C2410C", primary: "#C2410C", secondary: "#1E3A5F", accent: "#F6AD55", heroBg: "#F1F5F9", onHero: "#1A202C",
      barBg: "#1E3A5F", onBar: "#FFFFFF", footerBg: "#1E3A5F", onFooter: "#E2E8F0", open: "#1F7A4A", closed: "#B42318",
    },
    fonts: { heading: f("league-spartan", [700]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 700,
    radius: 20,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "sticker", priceList: "cards", spacing: "airy" },
    photoDirection: "Bright rooms just painted, rollers mid-stroke, color swatches and crisp cut lines; airy and cheerful.",
  },
  "contractor.square_deal": {
    id: "contractor.square_deal",
    name: "Square Deal",
    category: "contractor",
    layout: "classic",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EFEFEC", text: "#222222", muted: "#555555", heading: "#222222",
      link: "#2D6A2D", primary: "#2F7D32", secondary: "#222222", accent: "#9CCC65", heroBg: "#222222", onHero: "#FFFFFF",
      barBg: "#222222", onBar: "#FFFFFF", footerBg: "#2F7D32", onFooter: "#FFFFFF", open: "#2F7D32", closed: "#B3261E",
    },
    fonts: { heading: f("fjalla-one", [400]), body: f("open-sans", [400, 700]) },
    headingWeight: 400,
    radius: 3,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "leaders", spacing: "dense" },
    photoDirection: "Plain before-and-after pairs, fresh concrete and fence lines, the owner on site; honest, unfiltered daylight.",
  },
  "contractor.fine_finish": {
    id: "contractor.fine_finish",
    name: "Fine Finish",
    category: "contractor",
    layout: "minimal",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F5F3EF", text: "#1F1F1F", muted: "#59544E", heading: "#1F1F1F",
      link: "#7A5A2E", primary: "#1F1F1F", secondary: "#7A5A2E", accent: "#B8945A", heroBg: "#F5F3EF", onHero: "#1F1F1F",
      barBg: "#7A5A2E", onBar: "#FFFFFF", footerBg: "#1F1F1F", onFooter: "#F5F3EF", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("dm-serif-display", [400]), body: f("lora", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Finished kitchens and baths styled like a magazine: soft window light, wood grain, tile and trim details.",
  },

  // ---- warm / tinted light ----
  "contractor.sawdust": {
    id: "contractor.sawdust",
    name: "Sawdust",
    category: "contractor",
    layout: "split",
    palette: {
      bg: "#F5EDE0", surface: "#FFFDF8", band: "#EADFCB", text: "#2B241D", muted: "#5E5246", heading: "#3A2A1C",
      link: "#A0461A", primary: "#B84E1C", secondary: "#3A2A1C", accent: "#D9A441", heroBg: "#3A2A1C", onHero: "#F5EDE0",
      barBg: "#3A2A1C", onBar: "#F5EDE0", footerBg: "#3A2A1C", onFooter: "#EADFCB", open: "#2F6B33", closed: "#A3301A",
    },
    fonts: { heading: f("rokkitt", [700]), body: f("work-sans", [400, 700]) },
    headingWeight: 700,
    radius: 4,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Framing lumber, sawhorses and shavings in warm afternoon light; carpenters measuring and cutting.",
  },
  "contractor.cold_front": {
    id: "contractor.cold_front",
    name: "Cold Front",
    category: "contractor",
    layout: "classic",
    palette: {
      bg: "#EEF2F6", surface: "#FFFFFF", band: "#DFE6EE", text: "#1C2733", muted: "#47566A", heading: "#1F3B57",
      link: "#1F5A8A", primary: "#1F5A8A", secondary: "#E8A33D", accent: "#E8A33D", heroBg: "#DFE6EE", onHero: "#1C2733",
      barBg: "#1F3B57", onBar: "#FFFFFF", footerBg: "#1F3B57", onFooter: "#DFE6EE", open: "#1C6E45", closed: "#A93226",
    },
    fonts: { heading: f("roboto-slab", [700]), body: f("figtree", [400, 700]) },
    headingWeight: 700,
    radius: 10,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "shadow", badge: "seal", priceList: "cards", spacing: "standard" },
    photoDirection: "Condensers beside brick homes, a tech reading gauges, thermostats and vents; cool, even, slightly blue light.",
  },
  "contractor.split_rail": {
    id: "contractor.split_rail",
    name: "Split Rail",
    category: "contractor",
    layout: "soft",
    palette: {
      bg: "#EEF1E8", surface: "#FFFFFF", band: "#E0E6D6", text: "#23291F", muted: "#4F5A48", heading: "#2F4A2A",
      link: "#7A4A1E", primary: "#2F4A2A", secondary: "#8C5A2B", accent: "#A3B18A", heroBg: "#E0E6D6", onHero: "#23291F",
      barBg: "#8C5A2B", onBar: "#FFFFFF", footerBg: "#23291F", onFooter: "#E0E6D6", open: "#2F6B33", closed: "#A3301A",
    },
    fonts: { heading: f("bree-serif", [400]), body: f("cabin", [400, 700]) },
    headingWeight: 400,
    radius: 14,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "flat", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Fence lines across pasture, gates and decks in soft overcast light; grass, cedar and a big Alabama sky.",
  },
  "contractor.red_clay": {
    id: "contractor.red_clay",
    name: "Red Clay",
    category: "contractor",
    layout: "overlap",
    palette: {
      bg: "#F7E9E1", surface: "#FFF9F5", band: "#EFD8CA", text: "#2E1F1A", muted: "#614A40", heading: "#7A2E1B",
      link: "#8F3A22", primary: "#7A2E1B", secondary: "#2E1F1A", accent: "#D98B5F", heroBg: "#EFD8CA", onHero: "#2E1F1A",
      barBg: "#2E1F1A", onBar: "#FFF9F5", footerBg: "#2E1F1A", onFooter: "#EFD8CA", open: "#2F6B33", closed: "#9C2A16",
    },
    fonts: { heading: f("patua-one", [400]), body: f("mulish", [400, 700]) },
    headingWeight: 400,
    radius: 8,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "small_caps", card: "shadow", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "Dirt work and grading, red clay and gravel, excavators and finished driveways at golden hour.",
  },
  "contractor.limestone": {
    id: "contractor.limestone",
    name: "Limestone",
    category: "contractor",
    layout: "editorial",
    palette: {
      bg: "#EFEDE8", surface: "#FAF9F6", band: "#E2DFD7", text: "#262522", muted: "#55524B", heading: "#262522",
      link: "#3E5C76", primary: "#3E5C76", secondary: "#262522", accent: "#C9A66B", heroBg: "#262522", onHero: "#EFEDE8",
      barBg: "#262522", onBar: "#EFEDE8", footerBg: "#3E5C76", onFooter: "#FFFFFF", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("cabin-condensed", [700]), body: f("dm-sans", [400, 700]) },
    headingWeight: 700,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "cards", spacing: "dense" },
    photoDirection: "Stone, concrete and pavers in flat overcast light; texture close-ups and clean wide shots of patios and walls.",
  },
  "contractor.honey_do": {
    id: "contractor.honey_do",
    name: "Honey Do",
    category: "contractor",
    layout: "overlap",
    palette: {
      bg: "#FBF4D9", surface: "#FFFDF2", band: "#F3E7B5", text: "#26231A", muted: "#57513C", heading: "#26231A",
      link: "#2F5285", primary: "#26231A", secondary: "#2F5285", accent: "#E0B92E", heroBg: "#F3E7B5", onHero: "#26231A",
      barBg: "#2F5285", onBar: "#FFFFFF", footerBg: "#26231A", onFooter: "#F3E7B5", open: "#2F6B33", closed: "#A3301A",
    },
    fonts: { heading: f("sanchez", [400]), body: f("atkinson-hyperlegible", [400, 700]) },
    headingWeight: 400,
    radius: 6,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Friendly handyman at a front door with a toolbag, small fixes up close: hinges, faucets, a fresh shelf. Warm light.",
  },

  // ---- bold / saturated ----
  "contractor.caution_tape": {
    id: "contractor.caution_tape",
    name: "Caution Tape",
    category: "contractor",
    layout: "poster",
    palette: {
      bg: "#FFD100", surface: "#FFFFFF", band: "#FFE45C", text: "#111111", muted: "#3D3500", heading: "#111111",
      link: "#5A2D00", primary: "#D62300", secondary: "#111111", accent: "#111111", heroBg: "#111111", onHero: "#FFD100",
      barBg: "#111111", onBar: "#FFD100", footerBg: "#111111", onFooter: "#FFD100", open: "#1A6B32", closed: "#B3261E",
    },
    fonts: { heading: f("anton", [400]), body: f("roboto-condensed", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "dense" },
    photoDirection: "High-contrast job-site shots: hard hats, cones, machines mid-work; punchy color, black shadows.",
  },
  "contractor.hi_vis": {
    id: "contractor.hi_vis",
    name: "Hi-Vis",
    category: "contractor",
    layout: "split",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#FF7A1A", text: "#1A1A1A", muted: "#3B2A1E", heading: "#1A1A1A",
      link: "#A63F00", primary: "#1A1A1A", secondary: "#FF7A1A", accent: "#1A1A1A", heroBg: "#FF7A1A", onHero: "#1A1A1A",
      barBg: "#FF7A1A", onBar: "#1A1A1A", footerBg: "#1A1A1A", onFooter: "#FF9A4D", open: "#1F6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("alfa-slab-one", [400]), body: f("libre-franklin", [400, 700]) },
    headingWeight: 400,
    radius: 10,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Crews in hi-vis vests on roofs and in trenches, bold blue skies; saturated, sunny and energetic.",
  },
  "contractor.volt_blue": {
    id: "contractor.volt_blue",
    name: "Volt Blue",
    category: "contractor",
    layout: "minimal",
    palette: {
      bg: "#1446E0", surface: "#1B3FC4", band: "#0F35B0", text: "#FFFFFF", muted: "#D6E0FF", heading: "#FFFFFF",
      link: "#FFE24D", primary: "#FFE24D", secondary: "#FFFFFF", accent: "#FFE24D", heroBg: "#0B2A8F", onHero: "#FFFFFF",
      barBg: "#0B2A8F", onBar: "#FFFFFF", footerBg: "#0A1F66", onFooter: "#D6E0FF", open: "#9CF0B8", closed: "#FFC9C0",
    },
    fonts: { heading: f("work-sans", [800]), body: f("figtree", [400, 700]) },
    headingWeight: 800,
    radius: 12,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "flat", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Clean, modern installs: solar, generators, EV chargers, lit panels; crisp light with a cool blue cast.",
  },
  "contractor.barn_red": {
    id: "contractor.barn_red",
    name: "Barn Red",
    category: "contractor",
    layout: "classic",
    palette: {
      bg: "#A3201B", surface: "#8E1B17", band: "#7F1814", text: "#FFFFFF", muted: "#F8DCD8", heading: "#FFFFFF",
      link: "#FFD9A0", primary: "#FFD9A0", secondary: "#1E1A1A", accent: "#FFD9A0", heroBg: "#6E1411", onHero: "#FFFFFF",
      barBg: "#1E1A1A", onBar: "#FFFFFF", footerBg: "#1E1A1A", onFooter: "#F6D3CE", open: "#B8F5C4", closed: "#FFE0A8",
    },
    fonts: { heading: f("oswald", [600]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 600,
    radius: 4,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Metal roofs, barns and shops going up in the country; wide rural scenes, red and white, strong sun.",
  },
  "contractor.blue_sky": {
    id: "contractor.blue_sky",
    name: "Blue Sky",
    category: "contractor",
    layout: "soft",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#3EC1F3", text: "#0E2433", muted: "#263D4D", heading: "#0E2433",
      link: "#0B5C8A", primary: "#0E2433", secondary: "#F9C80E", accent: "#F9C80E", heroBg: "#3EC1F3", onHero: "#0E2433",
      barBg: "#3EC1F3", onBar: "#0E2433", footerBg: "#0E2433", onFooter: "#BFE9FA", open: "#1A7A44", closed: "#B42318",
    },
    fonts: { heading: f("kanit", [600]), body: f("dm-sans", [400, 700]) },
    headingWeight: 600,
    radius: 24,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Rooflines, gutters and windows against bright blue sky; upbeat, high-key, lots of open air.",
  },
};
