import { f } from "../look-kit.ts";
import type { LookDef } from "../themes.ts";

/** Tax & finance looks (colors + fonts). Contrast is checked at build by resolveTheme; see test/designs.test.ts. */
export const FINANCE_LOOKS: Record<string, LookDef> = {
  // ── The four from research/tax-finance.md §11 ─────────────────────────
  "finance.ledger_linen": {
    id: "finance.ledger_linen",
    name: "Ledger & Linen",
    category: "finance",
    layout: "editorial",
    palette: {
      bg: "#F8F5EE", surface: "#FFFDF8", band: "#E7EEE7", text: "#1F2A24", muted: "#4C5850", heading: "#1F3A2E",
      link: "#2F5D4A", primary: "#2F5D4A", secondary: "#DEC48A", accent: "#B8862B", heroBg: "#E7EEE7", onHero: "#1F2A24",
      barBg: "#FFFDF8", onBar: "#1F3A2E", footerBg: "#1F3A2E", onFooter: "#E7EEE7", open: "#2E6B3A", closed: "#7A3E2B",
    },
    fonts: { heading: f("literata", [600]), body: f("public-sans", [400, 700]) },
    headingWeight: 600,
    radius: 4,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "ruled", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "The office as it is: a tidy desk by a window, the preparer with a client going over papers, warm daylight on wood and linen.",
  },
  "finance.main_street_agency": {
    id: "finance.main_street_agency",
    name: "Main Street Agency",
    category: "finance",
    layout: "classic",
    palette: {
      bg: "#FBFAF7", surface: "#FFFFFF", band: "#E2EFF0", text: "#1E2530", muted: "#4A5460", heading: "#163F48",
      link: "#1C5C68", primary: "#1C5C68", secondary: "#E3A33B", accent: "#E3A33B", heroBg: "#E2EFF0", onHero: "#163F48",
      barBg: "#E3A33B", onBar: "#1E2530", footerBg: "#163F48", onFooter: "#E2EFF0", open: "#1F6B3A", closed: "#9A3B26",
    },
    fonts: { heading: f("bitter", [700]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 700,
    radius: 10,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "bordered", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "The storefront on the square with its sign and porch light, the agent at the counter with a customer, homes, trucks and farms nearby.",
  },
  "finance.long_view": {
    id: "finance.long_view",
    name: "Long View",
    category: "finance",
    layout: "minimal",
    palette: {
      bg: "#F6F4EF", surface: "#FFFFFF", band: "#ECE5DA", text: "#26292B", muted: "#555A5D", heading: "#2F3E46",
      link: "#3E5A6E", primary: "#8E4428", secondary: "#B9CBBE", accent: "#9DB0A3", heroBg: "#ECE5DA", onHero: "#26292B",
      barBg: "#FFFFFF", onBar: "#2F3E46", footerBg: "#2F3E46", onFooter: "#ECE5DA", open: "#2E6B3A", closed: "#8E4428",
    },
    fonts: { heading: f("newsreader", [500]), body: f("figtree", [400, 700]) },
    headingWeight: 500,
    radius: 6,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Calm and unhurried: a still lake at morning, the advisor at a round table with a couple, natural light, nothing staged.",
  },
  "finance.bright_desk": {
    id: "finance.bright_desk",
    name: "Bright Desk",
    category: "finance",
    layout: "split",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#FFF3D1", text: "#1B1D2A", muted: "#4A4D5E", heading: "#1B1D2A",
      link: "#2347B5", primary: "#2347B5", secondary: "#F2B705", accent: "#F2B705", heroBg: "#FFF3D1", onHero: "#1B1D2A",
      barBg: "#F2B705", onBar: "#1B1D2A", footerBg: "#1B1D2A", onFooter: "#FFF3D1", open: "#1F6B3A", closed: "#B02E4C",
    },
    fonts: { heading: f("bricolage-grotesque", [800]), body: f("atkinson-hyperlegible", [400, 700]) },
    headingWeight: 800,
    radius: 12,
    button: "pill",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "A busy, friendly tax-season office: the team smiling at the front desk, a family going over forms, bright daylight.",
  },

  // ── Dark ──────────────────────────────────────────────────────────────
  "finance.pine_brass": {
    id: "finance.pine_brass",
    name: "Pine & Brass",
    category: "finance",
    layout: "classic",
    palette: {
      bg: "#14281F", surface: "#1C3529", band: "#182F24", text: "#EEF2EC", muted: "#B3C4B8", heading: "#F1E3C0",
      link: "#E8C468", primary: "#E8C468", secondary: "#2F6048", accent: "#E8C468", heroBg: "#0F1F18", onHero: "#EEF2EC",
      barBg: "#0F1F18", onBar: "#EEF2EC", footerBg: "#0B1812", onFooter: "#CFDCD2", open: "#9BE0AE", closed: "#F7AFA4",
    },
    fonts: { heading: f("libre-baskerville", [700]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 700,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "small_caps", card: "ruled", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "An established office: the partners at a conference table, framed credentials, brass lamps and evening window light.",
  },
  "finance.chalk_charcoal": {
    id: "finance.chalk_charcoal",
    name: "Chalk & Charcoal",
    category: "finance",
    layout: "split",
    palette: {
      bg: "#1E2124", surface: "#282C30", band: "#23272B", text: "#F0F1F2", muted: "#AEB4BA", heading: "#FFFFFF",
      link: "#7FE0CB", primary: "#5ED3C0", secondary: "#3D454D", accent: "#5ED3C0", heroBg: "#16181B", onHero: "#FFFFFF",
      barBg: "#16181B", onBar: "#FFFFFF", footerBg: "#111315", onFooter: "#D0D4D8", open: "#8FE3A5", closed: "#FF9E94",
    },
    fonts: { heading: f("hanken-grotesk", [800]), body: f("inter", [400, 700]) },
    headingWeight: 800,
    radius: 8,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "bordered", badge: "plain", priceList: "cards", spacing: "dense" },
    photoDirection: "Modern bookkeeping: the owner at a laptop with a client's business on screen, clean desks, cool light, a local storefront outside.",
  },
  "finance.plum_study": {
    id: "finance.plum_study",
    name: "Plum Study",
    category: "finance",
    layout: "overlap",
    palette: {
      bg: "#2A1730", surface: "#36203D", band: "#311B37", text: "#F6EEF7", muted: "#CDB9D0", heading: "#F8D9C8",
      link: "#F4B8A0", primary: "#F4B8A0", secondary: "#5A3566", accent: "#C9A0DC", heroBg: "#21102A", onHero: "#F6EEF7",
      barBg: "#21102A", onBar: "#F6EEF7", footerBg: "#1A0C20", onFooter: "#E2D3E5", open: "#9FE3B5", closed: "#FFB2B2",
    },
    fonts: { heading: f("dm-serif-display", [400]), body: f("work-sans", [400, 700]) },
    headingWeight: 400,
    radius: 14,
    button: "pill",
    knobs: { hero: "dark", divider: "rule", label: "small_caps", card: "flat", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "A quiet study: the advisor in conversation over coffee, bookshelves and a reading lamp, soft evening tones.",
  },
  "finance.ink_sky": {
    id: "finance.ink_sky",
    name: "Ink & Sky",
    category: "finance",
    layout: "poster",
    palette: {
      bg: "#121826", surface: "#1B2335", band: "#161E2E", text: "#EDF1F7", muted: "#A8B3C5", heading: "#FFFFFF",
      link: "#8FD3FF", primary: "#8FD3FF", secondary: "#2C3B5E", accent: "#FFCF5C", heroBg: "#0C111C", onHero: "#FFFFFF",
      barBg: "#0C111C", onBar: "#FFFFFF", footerBg: "#090D16", onFooter: "#C9D2E0", open: "#8FE3A5", closed: "#FFA8A0",
    },
    fonts: { heading: f("sora", [700]), body: f("ibm-plex-sans", [400, 700]) },
    headingWeight: 700,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "dense" },
    photoDirection: "Late-night season energy: the office lit up at dusk, preparers at their screens, a client signing at the counter.",
  },
  "finance.walnut_cream": {
    id: "finance.walnut_cream",
    name: "Walnut & Cream",
    category: "finance",
    layout: "editorial",
    palette: {
      bg: "#2B1E17", surface: "#3A2A21", band: "#33241C", text: "#F5EDE3", muted: "#C9B8A6", heading: "#F3DDBF",
      link: "#EDB57E", primary: "#E9A86B", secondary: "#5C4030", accent: "#C98A4B", heroBg: "#221711", onHero: "#F5EDE3",
      barBg: "#221711", onBar: "#F5EDE3", footerBg: "#1B120D", onFooter: "#E2D3C2", open: "#A6E0B0", closed: "#FFB0A0",
    },
    fonts: { heading: f("vollkorn", [700]), body: f("figtree", [400, 700]) },
    headingWeight: 700,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "none", card: "flat", badge: "plain", priceList: "leaders", spacing: "standard" },
    photoDirection: "Warm wood office in an old downtown building: walnut desk, a cup of coffee by the paperwork, the owner shaking a client's hand.",
  },

  // ── Crisp white ───────────────────────────────────────────────────────
  "finance.clear_column": {
    id: "finance.clear_column",
    name: "Clear Column",
    category: "finance",
    layout: "minimal",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EEF4FA", text: "#1B2430", muted: "#4D5866", heading: "#13304F",
      link: "#1769AA", primary: "#1769AA", secondary: "#B5D3EE", accent: "#F2A93B", heroBg: "#EEF4FA", onHero: "#13304F",
      barBg: "#EEF4FA", onBar: "#13304F", footerBg: "#13304F", onFooter: "#EEF4FA", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("manrope", [800]), body: f("inter", [400, 700]) },
    headingWeight: 800,
    radius: 12,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "shadow", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Bright, uncluttered office: the bookkeeper at a standing desk, a client reviewing numbers on a tablet, white walls and plants.",
  },
  "finance.courthouse_square": {
    id: "finance.courthouse_square",
    name: "Courthouse Square",
    category: "finance",
    layout: "split",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F3EEE7", text: "#1C2733", muted: "#4E5763", heading: "#1C2733",
      link: "#A83A1C", primary: "#C8441F", secondary: "#EEC497", accent: "#C8441F", heroBg: "#F3EEE7", onHero: "#1C2733",
      barBg: "#141C25", onBar: "#FFFFFF", footerBg: "#1C2733", onFooter: "#E6E9EC", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("libre-franklin", [800]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 800,
    radius: 2,
    button: "square",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "standard" },
    photoDirection: "Downtown brick storefront with the name on the glass, the owner in the doorway, the square and courthouse in the background.",
  },
  "finance.fresh_page": {
    id: "finance.fresh_page",
    name: "Fresh Page",
    category: "finance",
    layout: "soft",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F3EEFA", text: "#221A33", muted: "#544B66", heading: "#3B2366",
      link: "#6B3FA0", primary: "#6B3FA0", secondary: "#CDBAEA", accent: "#F5B83D", heroBg: "#F3EEFA", onHero: "#221A33",
      barBg: "#FFFFFF", onBar: "#3B2366", footerBg: "#2A1D45", onFooter: "#ECE5F7", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("plus-jakarta-sans", [800]), body: f("figtree", [400, 700]) },
    headingWeight: 800,
    radius: 16,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "A fresh start: a young owner opening the office, clean desk with a laptop and planner, a client smiling across the table.",
  },
  "finance.green_light": {
    id: "finance.green_light",
    name: "Green Light",
    category: "finance",
    layout: "overlap",
    palette: {
      bg: "#FFFFFF", surface: "#F7FBF8", band: "#E6F4EC", text: "#17261E", muted: "#46574D", heading: "#0F3F2A",
      link: "#127A4F", primary: "#12825A", secondary: "#FFD66B", accent: "#FFD66B", heroBg: "#E6F4EC", onHero: "#0F3F2A",
      barBg: "#E6F4EC", onBar: "#0F3F2A", footerBg: "#0F3F2A", onFooter: "#E6F4EC", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("lexend", [600]), body: f("atkinson-hyperlegible", [400, 700]) },
    headingWeight: 600,
    radius: 20,
    button: "pill",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Friendly and quick: the preparer handing back a finished return, a small-business owner at the counter, green plants and daylight.",
  },

  // ── Warm and tinted light ─────────────────────────────────────────────
  "finance.sage_counter": {
    id: "finance.sage_counter",
    name: "Sage Counter",
    category: "finance",
    layout: "classic",
    palette: {
      bg: "#EEF2EA", surface: "#FAFCF8", band: "#E1E9DC", text: "#1F2A22", muted: "#4A574D", heading: "#2E4634",
      link: "#9A4320", primary: "#A0461F", secondary: "#E8C49C", accent: "#8FA98F", heroBg: "#E1E9DC", onHero: "#1F2A22",
      barBg: "#FAFCF8", onBar: "#2E4634", footerBg: "#2E4634", onFooter: "#E1E9DC", open: "#2E6B3A", closed: "#9A3B26",
    },
    fonts: { heading: f("domine", [700]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 700,
    radius: 8,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "none", card: "shadow", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "A homey front counter with plants and a bowl of candy, the preparer greeting a neighbor, soft green walls and daylight.",
  },
  "finance.sand_lake": {
    id: "finance.sand_lake",
    name: "Sand & Lake",
    category: "finance",
    layout: "split",
    palette: {
      bg: "#F4ECDF", surface: "#FFFBF4", band: "#EADFCB", text: "#2A2622", muted: "#5A5148", heading: "#1E4A63",
      link: "#1E5A7A", primary: "#1E5A7A", secondary: "#E9B872", accent: "#C98B3E", heroBg: "#EADFCB", onHero: "#2A2622",
      barBg: "#E9B872", onBar: "#2A2622", footerBg: "#1E3D52", onFooter: "#EADFCB", open: "#2E6B3A", closed: "#9A3B26",
    },
    fonts: { heading: f("zilla-slab", [700]), body: f("work-sans", [400, 700]) },
    headingWeight: 700,
    radius: 4,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "leaders", spacing: "standard" },
    photoDirection: "Lake-country friendly: the agent outside the office in the afternoon sun, a family by their truck and boat, warm sandy tones.",
  },
  "finance.clear_skies": {
    id: "finance.clear_skies",
    name: "Clear Skies",
    category: "finance",
    layout: "poster",
    palette: {
      bg: "#EAF3FA", surface: "#FFFFFF", band: "#DCEAF5", text: "#1A2733", muted: "#47566A", heading: "#17344F",
      link: "#A62F45", primary: "#C93852", secondary: "#0E1F30", accent: "#7FB3DA", heroBg: "#FFFFFF", onHero: "#17344F",
      barBg: "#0E1F30", onBar: "#FFFFFF", footerBg: "#17344F", onFooter: "#DCEAF5", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("cabin", [700]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 700,
    radius: 14,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "none", card: "flat", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Open blue-sky day: the office front with clouds overhead, a retiree going over a policy with the agent, light and airy rooms.",
  },
  "finance.blush_wine": {
    id: "finance.blush_wine",
    name: "Blush & Wine",
    category: "finance",
    layout: "soft",
    palette: {
      bg: "#FAEFEC", surface: "#FFFAF8", band: "#F3E0DB", text: "#2B1F22", muted: "#5E4B50", heading: "#6E2440",
      link: "#8A2E4E", primary: "#8A2E4E", secondary: "#EBB49A", accent: "#D99A8A", heroBg: "#F3E0DB", onHero: "#2B1F22",
      barBg: "#FFFAF8", onBar: "#6E2440", footerBg: "#3A1C27", onFooter: "#F3E0DB", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("fraunces", [600]), body: f("dm-sans", [400, 700]) },
    headingWeight: 600,
    radius: 22,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Warm and personal: the owner at her desk with fresh flowers, a client relaxed in a comfortable chair, soft afternoon light.",
  },
  "finance.river_stone": {
    id: "finance.river_stone",
    name: "River Stone",
    category: "finance",
    layout: "overlap",
    palette: {
      bg: "#EFEEEA", surface: "#FAF9F6", band: "#E3E1DA", text: "#24262A", muted: "#50545A", heading: "#24262A",
      link: "#7A4F0A", primary: "#AA5E0C", secondary: "#1F2226", accent: "#AA5E0C", heroBg: "#E3E1DA", onHero: "#24262A",
      barBg: "#1F2226", onBar: "#FFFFFF", footerBg: "#1F2226", onFooter: "#E3E1DA", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("red-hat-display", [800]), body: f("red-hat-text", [400, 700]) },
    headingWeight: 800,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "dense" },
    photoDirection: "Solid and practical: a stone-front office building, the bookkeeper with ledgers and a laptop, natural gray and ochre tones.",
  },
  "finance.peach_orchard": {
    id: "finance.peach_orchard",
    name: "Peach Orchard",
    category: "finance",
    layout: "soft",
    palette: {
      bg: "#FBF1E6", surface: "#FFFAF4", band: "#F5E2CF", text: "#2A2124", muted: "#5C4D50", heading: "#6A2C5A",
      link: "#6A2C5A", primary: "#6A2C5A", secondary: "#F2B48C", accent: "#E8946A", heroBg: "#F5E2CF", onHero: "#2A2124",
      barBg: "#F2B48C", onBar: "#2A2124", footerBg: "#3E1A35", onFooter: "#F5E2CF", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("alegreya", [700]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 700,
    radius: 18,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "none", card: "shadow", badge: "seal", priceList: "cards", spacing: "standard" },
    photoDirection: "Small-town warmth: a family-run office in a converted house, the owner with a farm family at the kitchen-style table, golden light.",
  },

  // ── Cheerful tax season ───────────────────────────────────────────────
  "finance.coral_teal": {
    id: "finance.coral_teal",
    name: "Coral & Teal",
    category: "finance",
    layout: "soft",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#E4F2F2", text: "#1E2A2E", muted: "#4C5A5E", heading: "#12434B",
      link: "#B23A22", primary: "#F2643F", secondary: "#12434B", accent: "#F2643F", heroBg: "#12434B", onHero: "#FFFFFF",
      barBg: "#12434B", onBar: "#FFFFFF", footerBg: "#0D3238", onFooter: "#E2F0F1", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("outfit", [800]), body: f("atkinson-hyperlegible", [400, 700]) },
    headingWeight: 800,
    radius: 24,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Season in full swing: a smiling bilingual team at the front desk, families waiting with folders, bright colors and daylight.",
  },
  "finance.orange_folder": {
    id: "finance.orange_folder",
    name: "Orange Folder",
    category: "finance",
    layout: "poster",
    palette: {
      bg: "#FFFDF7", surface: "#FFFFFF", band: "#FFF0DC", text: "#1F2420", muted: "#4F5650", heading: "#0E4D3A",
      link: "#0E5E46", primary: "#0E5E46", secondary: "#FF8A3D", accent: "#FF8A3D", heroBg: "#FF8A3D", onHero: "#1F2420",
      barBg: "#FF8A3D", onBar: "#1F2420", footerBg: "#0E3B2E", onFooter: "#FFF0DC", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("barlow-condensed", [700]), body: f("public-sans", [400, 700]) },
    headingWeight: 700,
    radius: 6,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "cards", spacing: "dense" },
    photoDirection: "Walk-ins welcome: the open sign in the window, a preparer helping a customer at the counter, folders and forms in hand.",
  },
  "finance.turquoise_door": {
    id: "finance.turquoise_door",
    name: "Turquoise Door",
    category: "finance",
    layout: "classic",
    palette: {
      bg: "#F2FBFA", surface: "#FFFFFF", band: "#DDF3F1", text: "#13292C", muted: "#3F5659", heading: "#0D4A4E",
      link: "#A6245E", primary: "#D2306A", secondary: "#FFD25E", accent: "#19A7A0", heroBg: "#BFEDEA", onHero: "#0D3A3E",
      barBg: "#0F2F33", onBar: "#FFFFFF", footerBg: "#0D4A4E", onFooter: "#DDF3F1", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("rubik", [700]), body: f("figtree", [400, 700]) },
    headingWeight: 700,
    radius: 16,
    button: "pill",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "A colorful storefront office with a painted door, the owner helping a family in English and Spanish, cheerful daylight.",
  },

  // ── Quiet editorial ───────────────────────────────────────────────────
  "finance.quiet_hours": {
    id: "finance.quiet_hours",
    name: "Quiet Hours",
    category: "finance",
    layout: "editorial",
    palette: {
      bg: "#FAFAF8", surface: "#FFFFFF", band: "#EFEFEB", text: "#1D1D1F", muted: "#55555A", heading: "#1D1D1F",
      link: "#5A4A2A", primary: "#1D1D1F", secondary: "#D6CCB2", accent: "#B89B5E", heroBg: "#EFEFEB", onHero: "#1D1D1F",
      barBg: "#FFFFFF", onBar: "#1D1D1F", footerBg: "#1D1D1F", onFooter: "#E8E8E4", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("cormorant-garamond", [600]), body: f("inter", [400, 700]) },
    headingWeight: 600,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "ruled", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Black-and-white or muted portraits of the advisor, a quiet office corner with a window and a notebook, no props.",
  },
  "finance.steady_hand": {
    id: "finance.steady_hand",
    name: "Steady Hand",
    category: "finance",
    layout: "classic",
    palette: {
      bg: "#F1F4F6", surface: "#FFFFFF", band: "#DDE6EC", text: "#23272A", muted: "#4F575D", heading: "#2E5266",
      link: "#2E5266", primary: "#2E5266", secondary: "#B7CAD5", accent: "#A9B8A0", heroBg: "#DDE6EC", onHero: "#1F3442",
      barBg: "#FFFFFF", onBar: "#2E5266", footerBg: "#22323C", onFooter: "#DDE6EC", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("crimson-pro", [600]), body: f("ibm-plex-sans", [400, 700]) },
    headingWeight: 600,
    radius: 10,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "none", card: "bordered", badge: "plain", priceList: "leaders", spacing: "standard" },
    photoDirection: "Steady and reassuring: the advisor walking a retired couple through a plan, a cool gray-blue office, overcast window light.",
  },
  "finance.open_book": {
    id: "finance.open_book",
    name: "Open Book",
    category: "finance",
    layout: "minimal",
    palette: {
      bg: "#FDFBF7", surface: "#FFFFFF", band: "#F4EEE4", text: "#2A2421", muted: "#5A514C", heading: "#2A2421",
      link: "#6E2F2A", primary: "#6E2F2A", secondary: "#DCC59E", accent: "#C4A57A", heroBg: "#FDFBF7", onHero: "#2A2421",
      barBg: "#F4EEE4", onBar: "#2A2421", footerBg: "#2A2421", onFooter: "#F4EEE4", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("instrument-serif", [400]), body: f("instrument-sans", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Plain and honest: the planner's desk with an open notebook, a portrait by a window, cream walls and a single plant.",
  },
};
