import { f } from "../look-kit.ts";
import type { LookDef } from "../themes.ts";

/** More landscaping looks (colors + fonts). Contrast is checked at build by resolveTheme; see test/designs.test.ts. */
export const LANDSCAPING_LOOKS: Record<string, LookDef> = {
  "landscaping.deep_woods": {
    id: "landscaping.deep_woods",
    layout: "editorial",
    name: "Deep Woods",
    category: "landscaping",
    palette: {
      bg: "#10241A", surface: "#163020", band: "#1B3826", text: "#EAF2E6", muted: "#B5C7B4", heading: "#F4F1E4",
      link: "#B9E07A", primary: "#B9E07A", secondary: "#EAF2E6", accent: "#D9A94A", heroBg: "#0B1A12", onHero: "#F4F1E4",
      barBg: "#0B1A12", onBar: "#F4F1E4", footerBg: "#08130D", onFooter: "#CFDCCB", open: "#8FE0A0", closed: "#FF9C8A",
    },
    fonts: { heading: f("alegreya", [800]), body: f("lato", [400, 700]) },
    headingWeight: 800,
    radius: 10,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "small_caps", card: "flat", badge: "seal", priceList: "leaders", spacing: "airy" },
    photoDirection: "Shaded wooded lots, ferns and mature hardwoods, late-afternoon light filtering through the leaves.",
  },
  "landscaping.lantern_patio": {
    id: "landscaping.lantern_patio",
    layout: "poster",
    name: "Lantern Patio",
    category: "landscaping",
    palette: {
      bg: "#1B1D1F", surface: "#24272A", band: "#2A2D30", text: "#ECE8E1", muted: "#B3ADA4", heading: "#FFFFFF",
      link: "#F2B544", primary: "#F2B544", secondary: "#ECE8E1", accent: "#F2B544", heroBg: "#121314", onHero: "#ECE8E1",
      barBg: "#121314", onBar: "#ECE8E1", footerBg: "#121314", onFooter: "#C9C3BA", open: "#8FD9A8", closed: "#FF9E8F",
    },
    fonts: { heading: f("big-shoulders-display", [900]), body: f("ibm-plex-sans", [400, 700]) },
    headingWeight: 900,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "standard" },
    photoDirection: "Patios, walls and fire pits at dusk with the landscape lighting on; warm glow against deep shadow.",
  },
  "landscaping.rich_soil": {
    id: "landscaping.rich_soil",
    layout: "split",
    name: "Rich Soil",
    category: "landscaping",
    palette: {
      bg: "#2A1E16", surface: "#34261C", band: "#3A2B20", text: "#F3E9DC", muted: "#CDBBA6", heading: "#F3C98B",
      link: "#F3B26B", primary: "#E8913F", secondary: "#F3E9DC", accent: "#8DB255", heroBg: "#1F160F", onHero: "#F3E9DC",
      barBg: "#1F160F", onBar: "#F3E9DC", footerBg: "#1A120C", onFooter: "#DCCBB5", open: "#A6DB8A", closed: "#FF9B85",
    },
    fonts: { heading: f("rokkitt", [800]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 800,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "ruled", badge: "sticker", priceList: "leaders", spacing: "standard" },
    photoDirection: "Fresh-turned beds and dark mulch, wheelbarrows and gloved hands in the soil, warm earthy grade.",
  },
  "landscaping.moonlit_lawn": {
    id: "landscaping.moonlit_lawn",
    layout: "minimal",
    name: "Moonlit Lawn",
    category: "landscaping",
    palette: {
      bg: "#0F1E33", surface: "#152842", band: "#13253D", text: "#E6EEF7", muted: "#A9BBD0", heading: "#FFFFFF",
      link: "#7FD9AE", primary: "#7FD9AE", secondary: "#E6EEF7", accent: "#4FB3E8", heroBg: "#0A1626", onHero: "#E6EEF7",
      barBg: "#0A1626", onBar: "#E6EEF7", footerBg: "#081221", onFooter: "#C3D1E2", open: "#8BE3B0", closed: "#FFA39A",
    },
    fonts: { heading: f("space-grotesk", [700]), body: f("inter", [400, 700]) },
    headingWeight: 700,
    radius: 14,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "bordered", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Sprinkler heads mid-spray at dawn, beaded water on blades of grass, cool blue early light.",
  },
  "landscaping.tree_line": {
    id: "landscaping.tree_line",
    layout: "overlap",
    name: "Tree Line",
    category: "landscaping",
    palette: {
      bg: "#121412", surface: "#1B1E1B", band: "#1F231F", text: "#EDEDE6", muted: "#B2B5AC", heading: "#FFFFFF",
      link: "#FF8A5C", primary: "#FF6A2B", secondary: "#EDEDE6", accent: "#FF6A2B", heroBg: "#0A0B0A", onHero: "#EDEDE6",
      barBg: "#0A0B0A", onBar: "#EDEDE6", footerBg: "#0A0B0A", onFooter: "#C8CAC2", open: "#8FD9A0", closed: "#FF9C8F",
    },
    fonts: { heading: f("oswald", [700]), body: f("work-sans", [400, 700]) },
    headingWeight: 700,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "flat", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "Climbers in harness up big oaks, bucket trucks and chippers, low angles against the sky.",
  },
  "landscaping.clover_field": {
    id: "landscaping.clover_field",
    layout: "soft",
    name: "Clover Field",
    category: "landscaping",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EEF7EC", text: "#18261C", muted: "#4A5A4E", heading: "#1E5C2E",
      link: "#1E7A3A", primary: "#23823A", secondary: "#0F3B22", accent: "#8CC63F", heroBg: "#EEF7EC", onHero: "#18261C",
      barBg: "#18261C", onBar: "#FFFFFF", footerBg: "#1E5C2E", onFooter: "#FFFFFF", open: "#1E7A3A", closed: "#B3261E",
    },
    fonts: { heading: f("poppins", [800]), body: f("figtree", [400, 700]) },
    headingWeight: 800,
    radius: 24,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Bright, friendly yards with kids and dogs on the grass, clover and fresh-cut green, soft midday light.",
  },
  "landscaping.sprinkler_blue": {
    id: "landscaping.sprinkler_blue",
    layout: "classic",
    name: "Sprinkler Blue",
    category: "landscaping",
    palette: {
      bg: "#FFFFFF", surface: "#F7FAFC", band: "#E8F3FA", text: "#142433", muted: "#46586A", heading: "#0B4F82",
      link: "#0B62A8", primary: "#37B28C", secondary: "#0B6FB8", accent: "#6CC7EE", heroBg: "#0B4F82", onHero: "#FFFFFF",
      barBg: "#0B4F82", onBar: "#FFFFFF", footerBg: "#0A2236", onFooter: "#D6E6F2", open: "#18704A", closed: "#B3261E",
    },
    fonts: { heading: f("sora", [700]), body: f("open-sans", [400, 700]) },
    headingWeight: 700,
    radius: 8,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "cards", spacing: "standard" },
    photoDirection: "Clean shots of rotors and drip lines at work, valve boxes and controllers, crisp morning light.",
  },
  "landscaping.clean_edge": {
    id: "landscaping.clean_edge",
    layout: "poster",
    name: "Clean Edge",
    category: "landscaping",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F2F2EE", text: "#111111", muted: "#4F4F4A", heading: "#111111",
      link: "#2F6B1F", primary: "#9BD33F", secondary: "#111111", accent: "#9BD33F", heroBg: "#111111", onHero: "#FFFFFF",
      barBg: "#111111", onBar: "#FFFFFF", footerBg: "#111111", onFooter: "#E6E6E0", open: "#2F6B1F", closed: "#B3261E",
    },
    fonts: { heading: f("archivo-black", [400]), body: f("archivo", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "sticker", priceList: "cards", spacing: "dense" },
    photoDirection: "High-contrast close-ups of sharp bed edges and trimmed curbs, straight lines, bold shadows.",
  },
  "landscaping.seed_catalog": {
    id: "landscaping.seed_catalog",
    layout: "editorial",
    name: "Seed Catalog",
    category: "landscaping",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F6F1E9", text: "#24211D", muted: "#5A544C", heading: "#24211D",
      link: "#9A4A2C", primary: "#2D5A3D", secondary: "#A9502F", accent: "#D9B44A", heroBg: "#F6F1E9", onHero: "#24211D",
      barBg: "#2D5A3D", onBar: "#FFFFFF", footerBg: "#24211D", onFooter: "#F6F1E9", open: "#2D6B3D", closed: "#A33A22",
    },
    fonts: { heading: f("playfair-display", [800]), body: f("karla", [400, 700]) },
    headingWeight: 800,
    radius: 4,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Designed garden beds in bloom, overhead planting plans, perennials and textures shot like a catalog.",
  },
  "landscaping.bright_acre": {
    id: "landscaping.bright_acre",
    layout: "split",
    name: "Bright Acre",
    category: "landscaping",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#FFF2E6", text: "#1C2A22", muted: "#4F5B53", heading: "#1C3B2B",
      link: "#B4440F", primary: "#F26B1D", secondary: "#1C3B2B", accent: "#F9B233", heroBg: "#1C3B2B", onHero: "#FFFFFF",
      barBg: "#1C3B2B", onBar: "#FFFFFF", footerBg: "#1C3B2B", onFooter: "#E8F0EA", open: "#1F6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("montserrat", [800]), body: f("rubik", [400, 700]) },
    headingWeight: 800,
    radius: 12,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Wide sunny lawns on big lots, zero-turn mowers and trailers, bright saturated summer color.",
  },
  "landscaping.sage_stone": {
    id: "landscaping.sage_stone",
    layout: "minimal",
    name: "Sage & Stone",
    category: "landscaping",
    palette: {
      bg: "#E8EDE4", surface: "#F7F9F5", band: "#DCE4D6", text: "#26302A", muted: "#4C5850", heading: "#2E4434",
      link: "#3F5E46", primary: "#3F5A44", secondary: "#7A6145", accent: "#A3B49A", heroBg: "#DCE4D6", onHero: "#26302A",
      barBg: "#2E4434", onBar: "#F7F9F5", footerBg: "#2E4434", onFooter: "#E8EDE4", open: "#2E6B3A", closed: "#9E3324",
    },
    fonts: { heading: f("cormorant-garamond", [700]), body: f("instrument-sans", [400, 700]) },
    headingWeight: 700,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Quiet designed gardens: gravel paths, ornamental grasses, sage and silver foliage, overcast soft light.",
  },
  "landscaping.wheat_field": {
    id: "landscaping.wheat_field",
    layout: "classic",
    name: "Wheat Field",
    category: "landscaping",
    palette: {
      bg: "#F5ECD7", surface: "#FFFBF1", band: "#ECDDBD", text: "#2C2416", muted: "#5C4F38", heading: "#3B3A1E",
      link: "#8A4E14", primary: "#9B5B1E", secondary: "#3B3A1E", accent: "#D6A642", heroBg: "#3B3A1E", onHero: "#F5ECD7",
      barBg: "#3B3A1E", onBar: "#F5ECD7", footerBg: "#2C2416", onFooter: "#ECDDBD", open: "#3F6B2A", closed: "#9E3324",
    },
    fonts: { heading: f("arvo", [700]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 700,
    radius: 4,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "standard" },
    photoDirection: "Country properties and pastures, hay-colored fields, fence lines and big skies in golden light.",
  },
  "landscaping.river_rock": {
    id: "landscaping.river_rock",
    layout: "overlap",
    name: "River Rock",
    category: "landscaping",
    palette: {
      bg: "#E9EDF0", surface: "#FAFBFC", band: "#DCE2E7", text: "#232B33", muted: "#4C5764", heading: "#263746",
      link: "#3D5A73", primary: "#B5541F", secondary: "#263746", accent: "#8C99A6", heroBg: "#263746", onHero: "#F2F4F6",
      barBg: "#263746", onBar: "#F2F4F6", footerBg: "#1C2733", onFooter: "#DCE2E7", open: "#2E6B3A", closed: "#A3301E",
    },
    fonts: { heading: f("teko", [600]), body: f("barlow", [400, 700]) },
    headingWeight: 600,
    radius: 3,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "cards", spacing: "dense" },
    photoDirection: "Retaining walls, river-rock beds and paver patios in even daylight; texture of stone up close.",
  },
  "landscaping.sky_meadow": {
    id: "landscaping.sky_meadow",
    layout: "soft",
    name: "Sky Meadow",
    category: "landscaping",
    palette: {
      bg: "#EAF3FA", surface: "#FFFFFF", band: "#DCEBF6", text: "#1A2B3A", muted: "#475A6B", heading: "#1D4F7A",
      link: "#1D5F96", primary: "#2E7D4F", secondary: "#1D4F7A", accent: "#F4C542", heroBg: "#DCEBF6", onHero: "#1A2B3A",
      barBg: "#1D4F7A", onBar: "#FFFFFF", footerBg: "#1A2B3A", onFooter: "#DCEBF6", open: "#1F6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("quicksand", [700]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 700,
    radius: 28,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Open lawns under blue sky, wide horizons and puffy clouds, light and airy grade.",
  },
  "landscaping.magnolia": {
    id: "landscaping.magnolia",
    layout: "classic",
    name: "Magnolia",
    category: "landscaping",
    palette: {
      bg: "#FBF7EE", surface: "#FFFFFF", band: "#F2EADB", text: "#2A2A24", muted: "#5A5850", heading: "#3F5A2A",
      link: "#7A3346", primary: "#5E7A3A", secondary: "#7A3346", accent: "#E8C9CF", heroBg: "#F2EADB", onHero: "#2A2A24",
      barBg: "#3F5A2A", onBar: "#FFFFFF", footerBg: "#3F5A2A", onFooter: "#F2EADB", open: "#3F6B2A", closed: "#9E3324",
    },
    fonts: { heading: f("dm-serif-display", [400]), body: f("libre-franklin", [400, 700]) },
    headingWeight: 400,
    radius: 18,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "shadow", badge: "seal", priceList: "leaders", spacing: "airy" },
    photoDirection: "Southern front yards: magnolias, boxwoods and azaleas framing brick porches in soft warm light.",
  },
  "landscaping.hayloft": {
    id: "landscaping.hayloft",
    layout: "poster",
    name: "Hayloft",
    category: "landscaping",
    palette: {
      bg: "#F4EBDD", surface: "#FFF9F0", band: "#EADBC4", text: "#2B201A", muted: "#5C4B3F", heading: "#2B201A",
      link: "#A5321F", primary: "#B83A2A", secondary: "#2C4A6B", accent: "#E2B04A", heroBg: "#2C4A6B", onHero: "#F4EBDD",
      barBg: "#2B201A", onBar: "#F4EBDD", footerBg: "#2B201A", onFooter: "#EADBC4", open: "#3F6B2A", closed: "#A5321F",
    },
    fonts: { heading: f("patua-one", [400]), body: f("cabin", [400, 700]) },
    headingWeight: 400,
    radius: 8,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Rural acreage, barns and gravel drives, bush-hogging and fence-line clearing; honest working light.",
  },
  "landscaping.lime_mower": {
    id: "landscaping.lime_mower",
    layout: "minimal",
    name: "Lime Mower",
    category: "landscaping",
    palette: {
      bg: "#DDF27A", surface: "#F5FCD9", band: "#CBE85A", text: "#14200A", muted: "#33421C", heading: "#14200A",
      link: "#1F4E0F", primary: "#14200A", secondary: "#FFFFFF", accent: "#2F7A1F", heroBg: "#24561A", onHero: "#F5FCD9",
      barBg: "#14200A", onBar: "#DDF27A", footerBg: "#14200A", onFooter: "#DDF27A", open: "#23661A", closed: "#A3261E",
    },
    fonts: { heading: f("bebas-neue", [400]), body: f("chivo", [400, 700]) },
    headingWeight: 400,
    radius: 4,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "dense" },
    photoDirection: "Punchy saturated shots of fresh stripes and equipment in full sun, tight crops, bold color.",
  },
  "landscaping.tangerine_truck": {
    id: "landscaping.tangerine_truck",
    layout: "split",
    name: "Tangerine Truck",
    category: "landscaping",
    palette: {
      bg: "#FFF4E8", surface: "#FFFFFF", band: "#FFE2C6", text: "#1F1408", muted: "#5A3F22", heading: "#1F1408",
      link: "#A33F00", primary: "#1F1408", secondary: "#F26A1B", accent: "#F26A1B", heroBg: "#F26A1B", onHero: "#1F1408",
      barBg: "#1F1408", onBar: "#FFF4E8", footerBg: "#1F1408", onFooter: "#FFE2C6", open: "#1F6B2A", closed: "#B3261E",
    },
    fonts: { heading: f("league-spartan", [800]), body: f("dm-sans", [400, 700]) },
    headingWeight: 800,
    radius: 16,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "standard" },
    photoDirection: "The branded truck and trailer on the job, crew in bright shirts, cheerful high-key daylight.",
  },
  "landscaping.sunflower_row": {
    id: "landscaping.sunflower_row",
    layout: "overlap",
    name: "Sunflower Row",
    category: "landscaping",
    palette: {
      bg: "#FFD84A", surface: "#FFF6D1", band: "#FFE58A", text: "#1E1A0C", muted: "#4A3F14", heading: "#1E1A0C",
      link: "#6B3A00", primary: "#1E1A0C", secondary: "#2F6B2F", accent: "#2F6B2F", heroBg: "#FFE58A", onHero: "#1E1A0C",
      barBg: "#1E1A0C", onBar: "#FFD84A", footerBg: "#1E1A0C", onFooter: "#FFE58A", open: "#2B5E1F", closed: "#A3261E",
    },
    fonts: { heading: f("rubik", [800]), body: f("public-sans", [400, 700]) },
    headingWeight: 800,
    radius: 20,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "flat", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Flower beds and seasonal color in full bloom, sunflowers and marigolds, warm saturated sun.",
  },
  "landscaping.cobalt_crew": {
    id: "landscaping.cobalt_crew",
    layout: "classic",
    name: "Cobalt Crew",
    category: "landscaping",
    palette: {
      bg: "#1B3FA6", surface: "#2148B8", band: "#16358C", text: "#FFFFFF", muted: "#C9D6FF", heading: "#FFFFFF",
      link: "#FFD23F", primary: "#FFD23F", secondary: "#FFFFFF", accent: "#7CE0A3", heroBg: "#12307F", onHero: "#FFFFFF",
      barBg: "#0E2566", onBar: "#FFFFFF", footerBg: "#0E2566", onFooter: "#DCE5FF", open: "#9CF0B8", closed: "#FFC2B8",
    },
    fonts: { heading: f("unbounded", [700]), body: f("manrope", [400, 700]) },
    headingWeight: 700,
    radius: 12,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "flat", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Crew portraits in matching shirts, clean trucks lined up, crisp clear-sky daylight.",
  },
  "landscaping.fresh_mint": {
    id: "landscaping.fresh_mint",
    layout: "editorial",
    name: "Fresh Mint",
    category: "landscaping",
    palette: {
      bg: "#BDF0D3", surface: "#EFFCF4", band: "#A6E8C2", text: "#0B2A1C", muted: "#1F4A35", heading: "#0B2A1C",
      link: "#6A1B4D", primary: "#0B2A1C", secondary: "#C8441F", accent: "#F7A072", heroBg: "#A6E8C2", onHero: "#0B2A1C",
      barBg: "#0B2A1C", onBar: "#EFFCF4", footerBg: "#0B2A1C", onFooter: "#BDF0D3", open: "#13603A", closed: "#A3261E",
    },
    fonts: { heading: f("syne", [600]), body: f("inter", [400, 700]) },
    headingWeight: 600,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Modern plantings and clean lawns against white walls, graphic shadows, fresh cool color.",
  },
};
