import { f } from "../look-kit.ts";
import type { LookDef } from "../themes.ts";

/** More print and sign shop looks (colors + fonts). Contrast is checked at build by resolveTheme; see test/designs.test.ts. */
export const PRINT_LOOKS: Record<string, LookDef> = {
  "print.darkroom": {
    id: "print.darkroom",
    layout: "split",
    name: "Darkroom",
    category: "print",
    palette: {
      bg: "#0E0E10", surface: "#18181C", band: "#1C1C21", text: "#F2F2F2", muted: "#B4B4BC", heading: "#FFFFFF",
      link: "#FF6FB5", primary: "#FF3EA5", secondary: "#3EDBFF", accent: "#FFE14D", heroBg: "#17171B", onHero: "#FFFFFF",
      barBg: "#000000", onBar: "#FFFFFF", footerBg: "#000000", onFooter: "#D0D0D6", open: "#6EE7A0", closed: "#FF8A9A",
    },
    fonts: { heading: f("space-grotesk", [700]), body: f("inter", [400, 700]) },
    headingWeight: 700,
    radius: 12,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "flat", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Prints under the drying rack lights, neon ink on black shirts, moody low-key studio shots.",
  },
  "print.night_press": {
    id: "print.night_press",
    layout: "poster",
    name: "Night Press",
    category: "print",
    palette: {
      bg: "#0F1A2E", surface: "#16243D", band: "#142139", text: "#EAF0F8", muted: "#AFBDD0", heading: "#FFC93C",
      link: "#FFC93C", primary: "#FFC93C", secondary: "#EAF0F8", accent: "#E8473C", heroBg: "#0A1222", onHero: "#EAF0F8",
      barBg: "#0A1222", onBar: "#EAF0F8", footerBg: "#08101D", onFooter: "#C9D4E3", open: "#7EE0A6", closed: "#FF9C94",
    },
    fonts: { heading: f("bebas-neue", [400]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 400,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "Lit signs and channel letters after dark, storefronts glowing against a navy evening sky.",
  },
  "print.plum_ink": {
    id: "print.plum_ink",
    layout: "editorial",
    name: "Plum Ink",
    category: "print",
    palette: {
      bg: "#24122B", surface: "#2E1A37", band: "#331D3D", text: "#F6ECF4", muted: "#CDB6CA", heading: "#FFFFFF",
      link: "#FFB17A", primary: "#FF8A3D", secondary: "#F6ECF4", accent: "#E85DA3", heroBg: "#1A0C20", onHero: "#F6ECF4",
      barBg: "#1A0C20", onBar: "#F6ECF4", footerBg: "#1A0C20", onFooter: "#E2D2DF", open: "#86E0A8", closed: "#FFA3B0",
    },
    fonts: { heading: f("abril-fatface", [400]), body: f("lato", [400, 700]) },
    headingWeight: 400,
    radius: 10,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "small_caps", card: "flat", badge: "seal", priceList: "cards", spacing: "airy" },
    photoDirection: "Invitations, foil and specialty stock in dramatic side light on dark surfaces.",
  },
  "print.graphite": {
    id: "print.graphite",
    layout: "overlap",
    name: "Graphite",
    category: "print",
    palette: {
      bg: "#212325", surface: "#2A2D30", band: "#2E3134", text: "#EDEDED", muted: "#B5B8BB", heading: "#FFFFFF",
      link: "#C6F432", primary: "#C6F432", secondary: "#EDEDED", accent: "#C6F432", heroBg: "#17181A", onHero: "#EDEDED",
      barBg: "#17181A", onBar: "#EDEDED", footerBg: "#17181A", onFooter: "#C9CCCF", open: "#8FE3A6", closed: "#FF9E94",
    },
    fonts: { heading: f("archivo-black", [400]), body: f("archivo", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "dense" },
    photoDirection: "The press floor: squeegees, screens and flash dryers, shirts stacked high, gritty shop light.",
  },
  "print.neon_sign": {
    id: "print.neon_sign",
    layout: "minimal",
    name: "Neon Sign",
    category: "print",
    palette: {
      bg: "#0B1C20", surface: "#10272C", band: "#12292F", text: "#E4F5F3", muted: "#A6C4C1", heading: "#5CF2D0",
      link: "#5CF2D0", primary: "#5CF2D0", secondary: "#FF6FA8", accent: "#FF6FA8", heroBg: "#071417", onHero: "#E4F5F3",
      barBg: "#071417", onBar: "#E4F5F3", footerBg: "#071417", onFooter: "#BFD8D5", open: "#7EE8A6", closed: "#FF9EA8",
    },
    fonts: { heading: f("righteous", [400]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 400,
    radius: 22,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "none", card: "bordered", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Glowing neon and LED signs in dim rooms, reflections and color spill, long-exposure night shots.",
  },
  "print.registration_mark": {
    id: "print.registration_mark",
    layout: "classic",
    name: "Registration Mark",
    category: "print",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F1F3F5", text: "#111418", muted: "#4A5059", heading: "#111418",
      link: "#0074A8", primary: "#00A0DC", secondary: "#111418", accent: "#EC008C", heroBg: "#F1F3F5", onHero: "#111418",
      barBg: "#111418", onBar: "#FFFFFF", footerBg: "#111418", onFooter: "#E6E8EB", open: "#1F7A4D", closed: "#C0003A",
    },
    fonts: { heading: f("work-sans", [800]), body: f("karla", [400, 700]) },
    headingWeight: 800,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "ruled", badge: "plain", priceList: "leaders", spacing: "standard" },
    photoDirection: "Clean overhead shots of press sheets with crop marks and color bars on a white table.",
  },
  "print.index_card": {
    id: "print.index_card",
    layout: "classic",
    name: "Index Card",
    category: "print",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F0F4FB", text: "#1E2430", muted: "#4D5566", heading: "#1E2430",
      link: "#2B59C3", primary: "#C8102E", secondary: "#2B59C3", accent: "#C8102E", heroBg: "#F0F4FB", onHero: "#1E2430",
      barBg: "#1E2430", onBar: "#FFFFFF", footerBg: "#1E2430", onFooter: "#E4E9F2", open: "#2E6B3A", closed: "#B00E2A",
    },
    fonts: { heading: f("libre-baskerville", [700]), body: f("public-sans", [400, 700]) },
    headingWeight: 700,
    radius: 4,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "shadow", badge: "stamp", priceList: "leaders", spacing: "airy" },
    photoDirection: "Business cards, letterhead and forms neatly fanned on a desk in soft daylight.",
  },
  "print.spot_color": {
    id: "print.spot_color",
    layout: "soft",
    name: "Spot Color",
    category: "print",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#FFF1E8", text: "#1D1D1B", muted: "#525250", heading: "#1D1D1B",
      link: "#C23B00", primary: "#FF4F00", secondary: "#1D1D1B", accent: "#FF4F00", heroBg: "#1D1D1B", onHero: "#FFFFFF",
      barBg: "#1D1D1B", onBar: "#FFFFFF", footerBg: "#1D1D1B", onFooter: "#F2F2F0", open: "#1F7A4D", closed: "#B3261E",
    },
    fonts: { heading: f("outfit", [800]), body: f("dm-sans", [400, 700]) },
    headingWeight: 800,
    radius: 14,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Single bold color on white: orange ink swatches, stickers and merch shot against plain backdrops.",
  },
  "print.crisp_stock": {
    id: "print.crisp_stock",
    layout: "minimal",
    name: "Crisp Stock",
    category: "print",
    palette: {
      bg: "#FFFFFF", surface: "#FAFAFA", band: "#F2F2F2", text: "#161616", muted: "#525252", heading: "#161616",
      link: "#0047BB", primary: "#161616", secondary: "#0047BB", accent: "#0047BB", heroBg: "#F2F2F2", onHero: "#161616",
      barBg: "#161616", onBar: "#FFFFFF", footerBg: "#F2F2F2", onFooter: "#161616", open: "#1F7A4D", closed: "#B3261E",
    },
    fonts: { heading: f("instrument-serif", [400]), body: f("instrument-sans", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "none", label: "none", card: "ruled", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Minimal still lifes of paper stock, envelopes and booklets, lots of white space, even light.",
  },
  "print.process_magenta": {
    id: "print.process_magenta",
    layout: "poster",
    name: "Process Magenta",
    category: "print",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#FCEAF2", text: "#12203A", muted: "#475672", heading: "#12203A",
      link: "#A3084A", primary: "#D00A54", secondary: "#12203A", accent: "#FFD400", heroBg: "#12203A", onHero: "#FFFFFF",
      barBg: "#12203A", onBar: "#FFFFFF", footerBg: "#12203A", onFooter: "#DCE4F2", open: "#1F7A4D", closed: "#B3261E",
    },
    fonts: { heading: f("ibm-plex-sans", [700]), body: f("hind", [400, 700]) },
    headingWeight: 700,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "seal", priceList: "cards", spacing: "standard" },
    photoDirection: "Banners and posters fresh off the wide-format printer, saturated color, straight-on product shots.",
  },
  "print.kraft_paper": {
    id: "print.kraft_paper",
    layout: "overlap",
    name: "Kraft Paper",
    category: "print",
    palette: {
      bg: "#E9D8B9", surface: "#F6ECD9", band: "#DEC9A3", text: "#2B1D12", muted: "#54402C", heading: "#2B1D12",
      link: "#7A2E12", primary: "#2B1D12", secondary: "#C2410C", accent: "#E3B04B", heroBg: "#1F4E79", onHero: "#F6ECD9",
      barBg: "#2B1D12", onBar: "#F6ECD9", footerBg: "#2B1D12", onFooter: "#DEC9A3", open: "#2E5E2A", closed: "#9E2A12",
    },
    fonts: { heading: f("ultra", [400]), body: f("arvo", [400, 700]) },
    headingWeight: 400,
    radius: 4,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Kraft boxes, stamped tags and hangtags on butcher paper and wood, warm handmade feel.",
  },
  "print.letterpress": {
    id: "print.letterpress",
    layout: "editorial",
    name: "Letterpress",
    category: "print",
    palette: {
      bg: "#F6F0E3", surface: "#FFFBF2", band: "#ECE3D0", text: "#22201C", muted: "#57524A", heading: "#22201C",
      link: "#8B1E2D", primary: "#8B1E2D", secondary: "#22201C", accent: "#B89650", heroBg: "#ECE3D0", onHero: "#22201C",
      barBg: "#22201C", onBar: "#F6F0E3", footerBg: "#22201C", onFooter: "#ECE3D0", open: "#2E6B3A", closed: "#8B1E2D",
    },
    fonts: { heading: f("old-standard-tt", [700]), body: f("crimson-pro", [400, 700]) },
    headingWeight: 700,
    radius: 2,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "ruled", badge: "seal", priceList: "leaders", spacing: "airy" },
    photoDirection: "Raking light across debossed cotton paper, lead type in the drawer, close and tactile.",
  },
  "print.blueprint": {
    id: "print.blueprint",
    layout: "split",
    name: "Blueprint",
    category: "print",
    palette: {
      bg: "#E6EEF7", surface: "#FFFFFF", band: "#D6E3F1", text: "#102A4C", muted: "#3E5573", heading: "#102A4C",
      link: "#1D4E89", primary: "#F2B705", secondary: "#1D4E89", accent: "#F2B705", heroBg: "#1D4E89", onHero: "#FFFFFF",
      barBg: "#102A4C", onBar: "#FFFFFF", footerBg: "#102A4C", onFooter: "#D6E3F1", open: "#1F6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("saira-condensed", [700]), body: f("barlow", [400, 700]) },
    headingWeight: 700,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "cards", spacing: "dense" },
    photoDirection: "Sign mockups on building fronts, measured drawings and installs on ladders, clear daylight.",
  },
  "print.stitch_room": {
    id: "print.stitch_room",
    layout: "soft",
    name: "Stitch Room",
    category: "print",
    palette: {
      bg: "#F8E8E4", surface: "#FFFFFF", band: "#F1D9D3", text: "#2B2233", muted: "#5A4C5E", heading: "#2E3A59",
      link: "#A3184F", primary: "#2E3A59", secondary: "#C2185B", accent: "#E9A23B", heroBg: "#F1D9D3", onHero: "#2B2233",
      barBg: "#2E3A59", onBar: "#FFFFFF", footerBg: "#2E3A59", onFooter: "#F8E8E4", open: "#2E6B3A", closed: "#A3184F",
    },
    fonts: { heading: f("fraunces", [700]), body: f("mulish", [400, 700]) },
    headingWeight: 700,
    radius: 20,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "shadow", badge: "seal", priceList: "cards", spacing: "airy" },
    photoDirection: "Embroidery hoops and thread spools, monogrammed towels and caps, soft window light.",
  },
  "print.mint_plate": {
    id: "print.mint_plate",
    layout: "classic",
    name: "Mint Plate",
    category: "print",
    palette: {
      bg: "#E3F2EA", surface: "#FFFFFF", band: "#D2EADD", text: "#13261E", muted: "#3F5A4D", heading: "#0F5E4A",
      link: "#0F5E4A", primary: "#FF6B4A", secondary: "#0F5E4A", accent: "#FF6B4A", heroBg: "#0F5E4A", onHero: "#FFFFFF",
      barBg: "#13261E", onBar: "#FFFFFF", footerBg: "#13261E", onFooter: "#D2EADD", open: "#1F6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("josefin-sans", [700]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 700,
    radius: 10,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Friendly counter shots of flyers, menus and postcards, a smiling owner at the copier, bright light.",
  },
  "print.peach_stock": {
    id: "print.peach_stock",
    layout: "poster",
    name: "Peach Stock",
    category: "print",
    palette: {
      bg: "#FCE9DA", surface: "#FFF8F2", band: "#F6D5BC", text: "#1B1B1B", muted: "#4F3F33", heading: "#1B1B1B",
      link: "#A1361A", primary: "#1B1B1B", secondary: "#3A5BD9", accent: "#FF7A59", heroBg: "#F6D5BC", onHero: "#1B1B1B",
      barBg: "#1B1B1B", onBar: "#FCE9DA", footerBg: "#1B1B1B", onFooter: "#F6D5BC", open: "#2E6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("bricolage-grotesque", [800]), body: f("figtree", [400, 700]) },
    headingWeight: 800,
    radius: 8,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Stickers, zines and art prints in playful flat-lay piles, warm pastel backdrops.",
  },
  "print.cyan_flood": {
    id: "print.cyan_flood",
    layout: "poster",
    name: "Cyan Flood",
    category: "print",
    palette: {
      bg: "#00B4E6", surface: "#E5F8FD", band: "#4FCDEE", text: "#06232E", muted: "#0F3A47", heading: "#06232E",
      link: "#5A0A3A", primary: "#FF2D8A", secondary: "#06232E", accent: "#FFE600", heroBg: "#06232E", onHero: "#E5F8FD",
      barBg: "#06232E", onBar: "#FFFFFF", footerBg: "#06232E", onFooter: "#B8ECFA", open: "#0B6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("staatliches", [400]), body: f("rubik", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "dense" },
    photoDirection: "Bold CMYK color: cyan and magenta shirts, ink buckets and fresh pulls, hard flash, flat backgrounds.",
  },
  "print.magenta_run": {
    id: "print.magenta_run",
    layout: "soft",
    name: "Magenta Run",
    category: "print",
    palette: {
      bg: "#FFE3F0", surface: "#FFFFFF", band: "#FFC6E0", text: "#2A0A1C", muted: "#5E2347", heading: "#B0005E",
      link: "#9E0055", primary: "#2A0A1C", secondary: "#C8006E", accent: "#FFE600", heroBg: "#C8006E", onHero: "#FFFFFF",
      barBg: "#2A0A1C", onBar: "#FFE3F0", footerBg: "#2A0A1C", onFooter: "#FFC6E0", open: "#1F6B3A", closed: "#A3001E",
    },
    fonts: { heading: f("teko", [600]), body: f("poppins", [400, 700]) },
    headingWeight: 600,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Team uniforms and event tees on people, color-blocked backgrounds, energetic action shots.",
  },
  "print.safety_yellow": {
    id: "print.safety_yellow",
    layout: "split",
    name: "Safety Yellow",
    category: "print",
    palette: {
      bg: "#FFE14D", surface: "#FFF7CC", band: "#FFD21F", text: "#141414", muted: "#3D3500", heading: "#141414",
      link: "#0B3D91", primary: "#141414", secondary: "#0050B5", accent: "#141414", heroBg: "#0050B5", onHero: "#FFE14D",
      barBg: "#141414", onBar: "#FFE14D", footerBg: "#141414", onFooter: "#FFF7CC", open: "#1F5E1F", closed: "#A3261E",
    },
    fonts: { heading: f("fjalla-one", [400]), body: f("asap", [400, 700]) },
    headingWeight: 400,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "Vehicle lettering, yard signs and site banners in hard noon sun, straight-on and legible.",
  },
  "print.tangerine_press": {
    id: "print.tangerine_press",
    layout: "overlap",
    name: "Tangerine Press",
    category: "print",
    palette: {
      bg: "#FF7A2F", surface: "#FFF1E8", band: "#FF9050", text: "#151515", muted: "#3A1A08", heading: "#151515",
      link: "#3A0F5C", primary: "#151515", secondary: "#FFFFFF", accent: "#FFE14D", heroBg: "#2B2BD9", onHero: "#FFFFFF",
      barBg: "#151515", onBar: "#FFFFFF", footerBg: "#151515", onFooter: "#FFD2B5", open: "#1F6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("big-shoulders-display", [900]), body: f("work-sans", [400, 700]) },
    headingWeight: 900,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Loud poster-style shots: hoodies and tees hung on orange walls, hard light, big graphic crops.",
  },
  "print.periwinkle_riso": {
    id: "print.periwinkle_riso",
    layout: "editorial",
    name: "Periwinkle Riso",
    category: "print",
    palette: {
      bg: "#A9C1FF", surface: "#EEF2FF", band: "#94B0FF", text: "#1A1450", muted: "#2E2A6B", heading: "#1A1450",
      link: "#7A0A2E", primary: "#FF4A3D", secondary: "#1A1450", accent: "#FF4A3D", heroBg: "#1A1450", onHero: "#A9C1FF",
      barBg: "#1A1450", onBar: "#EEF2FF", footerBg: "#1A1450", onFooter: "#C9D7FF", open: "#1F6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("kanit", [700]), body: f("manrope", [400, 700]) },
    headingWeight: 700,
    radius: 18,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "none", card: "flat", badge: "sticker", priceList: "cards", spacing: "airy" },
    photoDirection: "Two-color riso prints and grainy art posters pinned up, overprint textures, soft even light.",
  },
};
