import { f } from "../look-kit.ts";
import type { LookDef } from "../themes.ts";

/** More restaurant looks (colors + fonts). Contrast is checked at build by resolveTheme; see test/designs.test.ts. */
export const RESTAURANT_LOOKS: Record<string, LookDef> = {
  // ---- dark ----
  "restaurant.cast_iron": {
    id: "restaurant.cast_iron",
    name: "Cast Iron",
    category: "restaurant",
    layout: "poster",
    palette: {
      bg: "#1C1B1A", surface: "#262422", band: "#2F2C29", text: "#F3EDE4", muted: "#C2B8AB", heading: "#F7E6CF",
      link: "#F4A462", primary: "#E8833A", secondary: "#F3EDE4", accent: "#C9572B", heroBg: "#121110", onHero: "#F3EDE4",
      barBg: "#121110", onBar: "#F3EDE4", footerBg: "#121110", onFooter: "#C2B8AB", open: "#93D69A", closed: "#F4978E",
    },
    fonts: { heading: f("oswald", [600]), body: f("lato", [400, 700]) },
    headingWeight: 600,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "flat", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "Moody low light, skillets and grills mid-sizzle, sparks and smoke against black.",
  },
  "restaurant.midnight_diner": {
    id: "restaurant.midnight_diner",
    name: "Midnight Diner",
    category: "restaurant",
    layout: "overlap",
    palette: {
      bg: "#121C33", surface: "#1A2744", band: "#1F2E50", text: "#EEF2FA", muted: "#AEB9D0", heading: "#FFFFFF",
      link: "#7FD3E6", primary: "#FF6B6B", secondary: "#7FD3E6", accent: "#FFC857", heroBg: "#0B1324", onHero: "#EEF2FA",
      barBg: "#0B1324", onBar: "#EEF2FA", footerBg: "#0B1324", onFooter: "#AEB9D0", open: "#8FE3A8", closed: "#FF9D9D",
    },
    fonts: { heading: f("righteous", [400]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 400,
    radius: 14,
    button: "pill",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Night shots through the front window, glowing sign, counter stools, milkshakes and late plates.",
  },
  "restaurant.hickory_night": {
    id: "restaurant.hickory_night",
    name: "Hickory Night",
    category: "restaurant",
    layout: "split",
    palette: {
      bg: "#241A14", surface: "#2E221A", band: "#36281F", text: "#F5EAD9", muted: "#CDBBA3", heading: "#F2C46B",
      link: "#F2C46B", primary: "#D9A441", secondary: "#A8432A", accent: "#A8432A", heroBg: "#17100C", onHero: "#F5EAD9",
      barBg: "#17100C", onBar: "#F5EAD9", footerBg: "#17100C", onFooter: "#CDBBA3", open: "#9ED59A", closed: "#F29A85",
    },
    fonts: { heading: f("ultra", [400]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 400,
    radius: 4,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "small_caps", card: "ruled", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "Firelight and dusk: the smoker at sundown, sliced brisket on butcher paper, warm amber grade.",
  },
  "restaurant.supper_club": {
    id: "restaurant.supper_club",
    name: "Supper Club",
    category: "restaurant",
    layout: "editorial",
    palette: {
      bg: "#10241D", surface: "#163029", band: "#1A372E", text: "#EEF0E8", muted: "#B4C2B8", heading: "#E9C46A",
      link: "#E9C46A", primary: "#E9C46A", secondary: "#EEF0E8", accent: "#C79A3B", heroBg: "#0A1813", onHero: "#EEF0E8",
      barBg: "#0A1813", onBar: "#EEF0E8", footerBg: "#0A1813", onFooter: "#B4C2B8", open: "#9FDDB0", closed: "#F2A08F",
    },
    fonts: { heading: f("playfair-display", [700]), body: f("libre-franklin", [400, 700]) },
    headingWeight: 700,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "small_caps", card: "bordered", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Candlelit tables, white plates on dark wood, a steak or a cocktail in a pool of warm light.",
  },
  "restaurant.plum_evening": {
    id: "restaurant.plum_evening",
    name: "Plum Evening",
    category: "restaurant",
    layout: "soft",
    palette: {
      bg: "#2A1830", surface: "#34203B", band: "#3B2543", text: "#F7EEF5", muted: "#CDB8CC", heading: "#F7EEF5",
      link: "#F5B3C8", primary: "#F5B3C8", secondary: "#8FC9B9", accent: "#D98AA6", heroBg: "#1E1023", onHero: "#F7EEF5",
      barBg: "#1E1023", onBar: "#F7EEF5", footerBg: "#1E1023", onFooter: "#CDB8CC", open: "#A6E3B8", closed: "#FFB0A8",
    },
    fonts: { heading: f("dm-serif-display", [400]), body: f("karla", [400, 700]) },
    headingWeight: 400,
    radius: 20,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "none", card: "flat", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Evening glow, string lights, desserts and glasses close up with soft bokeh behind.",
  },

  // ---- crisp white ----
  "restaurant.lunch_counter": {
    id: "restaurant.lunch_counter",
    name: "Lunch Counter",
    category: "restaurant",
    layout: "classic",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F1F4F8", text: "#1D2433", muted: "#4E5768", heading: "#1D3557",
      link: "#C1121F", primary: "#D62839", secondary: "#1D3557", accent: "#F4D35E", heroBg: "#1D3557", onHero: "#FFFFFF",
      barBg: "#1D3557", onBar: "#FFFFFF", footerBg: "#1D2433", onFooter: "#F1F4F8", open: "#1F7A3E", closed: "#B3192A",
    },
    fonts: { heading: f("rubik", [700]), body: f("work-sans", [400, 700]) },
    headingWeight: 700,
    radius: 8,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Bright and straight-on: plate lunches, meat-and-three trays, the counter and the regulars.",
  },
  "restaurant.fresh_basil": {
    id: "restaurant.fresh_basil",
    name: "Fresh Basil",
    category: "restaurant",
    layout: "minimal",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F2F6EF", text: "#1E2A22", muted: "#4F5D53", heading: "#1F5136",
      link: "#1F6B45", primary: "#2D6A4F", secondary: "#E76F51", accent: "#E76F51", heroBg: "#F2F6EF", onHero: "#1E2A22",
      barBg: "#1E2A22", onBar: "#FFFFFF", footerBg: "#1E2A22", onFooter: "#F2F6EF", open: "#1F6B45", closed: "#B23A23",
    },
    fonts: { heading: f("josefin-sans", [700]), body: f("open-sans", [400, 700]) },
    headingWeight: 700,
    radius: 6,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Clean daylight on white, fresh herbs and tomatoes, pizza and pasta shot from above.",
  },
  "restaurant.lime_salt": {
    id: "restaurant.lime_salt",
    name: "Lime & Salt",
    category: "restaurant",
    layout: "split",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EAF7F6", text: "#13302F", muted: "#3F5958", heading: "#0B4F4C",
      link: "#0B6E69", primary: "#0B7A75", secondary: "#C6F06A", accent: "#C6F06A", heroBg: "#13302F", onHero: "#FFFFFF",
      barBg: "#13302F", onBar: "#FFFFFF", footerBg: "#13302F", onFooter: "#EAF7F6", open: "#11744A", closed: "#B3261E",
    },
    fonts: { heading: f("kanit", [700]), body: f("dm-sans", [400, 700]) },
    headingWeight: 700,
    radius: 12,
    button: "pill",
    knobs: { hero: "dark", divider: "rule", label: "none", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Crisp midday light, citrus and fresh garnish, bowls and plates on a bright tabletop.",
  },
  "restaurant.morning_paper": {
    id: "restaurant.morning_paper",
    name: "Morning Paper",
    category: "restaurant",
    layout: "editorial",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F4F1EA", text: "#141414", muted: "#555049", heading: "#141414",
      link: "#A3141F", primary: "#141414", secondary: "#A3141F", accent: "#A3141F", heroBg: "#F4F1EA", onHero: "#141414",
      barBg: "#A3141F", onBar: "#FFFFFF", footerBg: "#141414", onFooter: "#F4F1EA", open: "#1E6B37", closed: "#A3141F",
    },
    fonts: { heading: f("newsreader", [700]), body: f("literata", [400, 700]) },
    headingWeight: 700,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "ruled", badge: "plain", priceList: "leaders", spacing: "standard" },
    photoDirection: "Early light on a breakfast table: coffee, biscuits, eggs, the paper folded alongside.",
  },
  "restaurant.sunny_side": {
    id: "restaurant.sunny_side",
    name: "Sunny Side",
    category: "restaurant",
    layout: "soft",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#FFF5D6", text: "#3A2E2A", muted: "#625650", heading: "#3A2E2A",
      link: "#A44A0E", primary: "#F4A300", secondary: "#3A2E2A", accent: "#F4A300", heroBg: "#FFF5D6", onHero: "#3A2E2A",
      barBg: "#3A2E2A", onBar: "#FFF5D6", footerBg: "#3A2E2A", onFooter: "#FFF5D6", open: "#2E6B2F", closed: "#A8322A",
    },
    fonts: { heading: f("quicksand", [700]), body: f("figtree", [400, 700]) },
    headingWeight: 700,
    radius: 24,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Cheerful morning sun, pancakes and eggs over easy, bright mugs, smiling staff.",
  },

  // ---- warm / tinted light ----
  "restaurant.sweet_tea": {
    id: "restaurant.sweet_tea",
    name: "Sweet Tea",
    category: "restaurant",
    layout: "overlap",
    palette: {
      bg: "#FBF3E4", surface: "#FFFDF8", band: "#F2E4CB", text: "#2C231D", muted: "#5C4F44", heading: "#6E2E1F",
      link: "#8C3B2A", primary: "#8C3B2A", secondary: "#3E5641", accent: "#D9A04A", heroBg: "#F2E4CB", onHero: "#2C231D",
      barBg: "#2C231D", onBar: "#FFFDF8", footerBg: "#2C231D", onFooter: "#F2E4CB", open: "#2F6B35", closed: "#8C3B2A",
    },
    fonts: { heading: f("yeseva-one", [400]), body: f("mulish", [400, 700]) },
    headingWeight: 400,
    radius: 10,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "shadow", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "Golden afternoon light, sweating glasses of tea, fried chicken and sides family-style.",
  },
  "restaurant.biscuit_honey": {
    id: "restaurant.biscuit_honey",
    name: "Biscuit & Honey",
    category: "restaurant",
    layout: "classic",
    palette: {
      bg: "#FFF7E0", surface: "#FFFFFF", band: "#FBE9B7", text: "#33261A", muted: "#5E4A36", heading: "#4A3426",
      link: "#8A4B0F", primary: "#9C5416", secondary: "#4A3426", accent: "#E8B04B", heroBg: "#4A3426", onHero: "#FFF7E0",
      barBg: "#4A3426", onBar: "#FFF7E0", footerBg: "#33261A", onFooter: "#FBE9B7", open: "#2F6B2F", closed: "#A33A1E",
    },
    fonts: { heading: f("bree-serif", [400]), body: f("cabin", [400, 700]) },
    headingWeight: 400,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Warm window light on flour-dusted counters, split biscuits, honey and jam, trays fresh from the oven.",
  },
  "restaurant.sage_kitchen": {
    id: "restaurant.sage_kitchen",
    name: "Sage Kitchen",
    category: "restaurant",
    layout: "classic",
    palette: {
      bg: "#EEF2E8", surface: "#FBFCF8", band: "#E0E8D6", text: "#232B22", muted: "#4D584A", heading: "#2F4A32",
      link: "#3E5F3A", primary: "#4F6D4A", secondary: "#232B22", accent: "#C98B6B", heroBg: "#E0E8D6", onHero: "#232B22",
      barBg: "#2F4A32", onBar: "#FBFCF8", footerBg: "#2F4A32", onFooter: "#E0E8D6", open: "#2F6B35", closed: "#9E3A2A",
    },
    fonts: { heading: f("spectral", [600]), body: f("hind", [400, 700]) },
    headingWeight: 600,
    radius: 16,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Soft natural light, salads, soups and sandwiches on stoneware, greenery in the background.",
  },
  "restaurant.peach_cobbler": {
    id: "restaurant.peach_cobbler",
    name: "Peach Cobbler",
    category: "restaurant",
    layout: "split",
    palette: {
      bg: "#FDEEE6", surface: "#FFFFFF", band: "#F9DCCD", text: "#3B2A2E", muted: "#66525A", heading: "#8E3B2C",
      link: "#A0412D", primary: "#F29E7E", secondary: "#3B2A2E", accent: "#F2B880", heroBg: "#F9DCCD", onHero: "#3B2A2E",
      barBg: "#3B2A2E", onBar: "#FDEEE6", footerBg: "#3B2A2E", onFooter: "#F9DCCD", open: "#2E6B3A", closed: "#A33A2A",
    },
    fonts: { heading: f("sanchez", [400]), body: f("asap", [400, 700]) },
    headingWeight: 400,
    radius: 18,
    button: "pill",
    knobs: { hero: "light", divider: "thick_rule", label: "none", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Warm, rosy light on pies, cobblers and cakes; a slice lifted out, crumbs on the plate.",
  },
  "restaurant.sorghum_mill": {
    id: "restaurant.sorghum_mill",
    name: "Sorghum Mill",
    category: "restaurant",
    layout: "poster",
    palette: {
      bg: "#F1E6D2", surface: "#FAF4E8", band: "#E5D5B8", text: "#2A2118", muted: "#574634", heading: "#2A2118",
      link: "#7A3E14", primary: "#7A3E14", secondary: "#4F6A23", accent: "#C28A2C", heroBg: "#E5D5B8", onHero: "#2A2118",
      barBg: "#2A2118", onBar: "#F1E6D2", footerBg: "#2A2118", onFooter: "#E5D5B8", open: "#3D6B22", closed: "#8E2A16",
    },
    fonts: { heading: f("zilla-slab", [700]), body: f("barlow", [400, 700]) },
    headingWeight: 700,
    radius: 2,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "Rustic and earthy: cornbread in cast iron, beans and greens, barn wood and burlap textures.",
  },
  "restaurant.porch_swing": {
    id: "restaurant.porch_swing",
    name: "Porch Swing",
    category: "restaurant",
    layout: "minimal",
    palette: {
      bg: "#EAF3F8", surface: "#FFFFFF", band: "#DCEAF2", text: "#1B2A36", muted: "#48596A", heading: "#1F5F8B",
      link: "#1F5F8B", primary: "#1F5F8B", secondary: "#F2B134", accent: "#F2B134", heroBg: "#DCEAF2", onHero: "#1B2A36",
      barBg: "#1B2A36", onBar: "#FFFFFF", footerBg: "#1B2A36", onFooter: "#DCEAF2", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("lexend", [600]), body: f("public-sans", [400, 700]) },
    headingWeight: 600,
    radius: 10,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "bordered", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Airy blue-sky daylight, patio tables, lemonade and burgers, relaxed people outside.",
  },

  // ---- bold / pastel ----
  "restaurant.brick_oven": {
    id: "restaurant.brick_oven",
    name: "Brick Oven",
    category: "restaurant",
    layout: "poster",
    palette: {
      bg: "#B3261E", surface: "#9A1F18", band: "#8F1C16", text: "#FFF4E6", muted: "#F6D3C4", heading: "#FFF4E6",
      link: "#FFE08A", primary: "#FFD23F", secondary: "#1A1210", accent: "#FFD23F", heroBg: "#7E1812", onHero: "#FFF4E6",
      barBg: "#1A1210", onBar: "#FFF4E6", footerBg: "#1A1210", onFooter: "#F6D3C4", open: "#D4F5C9", closed: "#FFE2E0",
    },
    fonts: { heading: f("anton", [400]), body: f("archivo", [400, 700]) },
    headingWeight: 400,
    radius: 4,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "dense" },
    photoDirection: "Hot and punchy: pies coming out of the oven, cheese pulls, flour and flame up close.",
  },
  "restaurant.mustard_wagon": {
    id: "restaurant.mustard_wagon",
    name: "Mustard Wagon",
    category: "restaurant",
    layout: "overlap",
    palette: {
      bg: "#F2C14E", surface: "#FFF6DA", band: "#E9B235", text: "#1E1A14", muted: "#3D3424", heading: "#1E1A14",
      link: "#6B1D0E", primary: "#B83A22", secondary: "#1E1A14", accent: "#B83A22", heroBg: "#1E1A14", onHero: "#F2C14E",
      barBg: "#1E1A14", onBar: "#F2C14E", footerBg: "#1E1A14", onFooter: "#FFF6DA", open: "#1E6B2A", closed: "#A3261A",
    },
    fonts: { heading: f("bungee", [400]), body: f("ibm-plex-sans", [400, 700]) },
    headingWeight: 400,
    radius: 8,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "bordered", badge: "stamp", priceList: "cards", spacing: "standard" },
    photoDirection: "Street-level energy: the truck window, hands passing food out, hot dogs and fries in paper boats.",
  },
  "restaurant.mint_parlor": {
    id: "restaurant.mint_parlor",
    name: "Mint Parlor",
    category: "restaurant",
    layout: "soft",
    palette: {
      bg: "#DDF3EA", surface: "#FFFFFF", band: "#C9EBDD", text: "#1C3530", muted: "#3F5A53", heading: "#1C3530",
      link: "#A12759", primary: "#F59ABB", secondary: "#1C3530", accent: "#F59ABB", heroBg: "#C9EBDD", onHero: "#1C3530",
      barBg: "#1C3530", onBar: "#DDF3EA", footerBg: "#1C3530", onFooter: "#DDF3EA", open: "#1C6B44", closed: "#A12759",
    },
    fonts: { heading: f("unbounded", [600]), body: f("outfit", [400, 700]) },
    headingWeight: 600,
    radius: 28,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "flat", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Playful pastel sets: scoops, cupcakes and shakes against mint and pink backdrops.",
  },
  "restaurant.lilac_frosting": {
    id: "restaurant.lilac_frosting",
    name: "Lilac Frosting",
    category: "restaurant",
    layout: "editorial",
    palette: {
      bg: "#EFE7F7", surface: "#FFFFFF", band: "#E2D5F0", text: "#2A2236", muted: "#554A63", heading: "#4A2C7A",
      link: "#5B3A8C", primary: "#8250B8", secondary: "#F2C6A0", accent: "#F2C6A0", heroBg: "#2A2236", onHero: "#FFFFFF",
      barBg: "#2A2236", onBar: "#FFFFFF", footerBg: "#2A2236", onFooter: "#E2D5F0", open: "#2E6B3A", closed: "#A3304A",
    },
    fonts: { heading: f("gloock", [400]), body: f("urbanist", [400, 700]) },
    headingWeight: 400,
    radius: 12,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "small_caps", card: "shadow", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "Elegant bakery still lifes: layer cakes, macarons and cookies on cake stands, soft diffuse light.",
  },
  "restaurant.citrus_stand": {
    id: "restaurant.citrus_stand",
    name: "Citrus Stand",
    category: "restaurant",
    layout: "minimal",
    palette: {
      bg: "#FF8A3D", surface: "#FFF1E4", band: "#FFA366", text: "#1B1410", muted: "#3E2A1C", heading: "#1B1410",
      link: "#6A1B05", primary: "#1B1410", secondary: "#FFF1E4", accent: "#FFE15C", heroBg: "#FFF1E4", onHero: "#1B1410",
      barBg: "#FFF1E4", onBar: "#1B1410", footerBg: "#1B1410", onFooter: "#FFF1E4", open: "#1E6B2A", closed: "#A3261A",
    },
    fonts: { heading: f("league-spartan", [800]), body: f("inter", [400, 700]) },
    headingWeight: 800,
    radius: 16,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "dense" },
    photoDirection: "Hard sunshine and bold color: smoothies, iced coffee and tacos against bright walls.",
  },
};
