import { f } from "../look-kit.ts";
import type { LookDef } from "../themes.ts";

/** More retail looks (colors + fonts). Contrast is checked at build by resolveTheme; see test/designs.test.ts. */
export const RETAIL_LOOKS: Record<string, LookDef> = {
  // ---- dark ----
  "retail.velvet_rack": {
    id: "retail.velvet_rack",
    name: "Velvet Rack",
    category: "retail",
    layout: "editorial",
    palette: {
      bg: "#141414", surface: "#1E1E1E", band: "#242424", text: "#F2EEE8", muted: "#B8B2AA", heading: "#F2EEE8",
      link: "#E8C9A9", primary: "#E8C9A9", secondary: "#F2EEE8", accent: "#E8C9A9", heroBg: "#0A0A0A", onHero: "#F2EEE8",
      barBg: "#0A0A0A", onBar: "#F2EEE8", footerBg: "#0A0A0A", onFooter: "#B8B2AA", open: "#9ADBA8", closed: "#F2A09A",
    },
    fonts: { heading: f("bodoni-moda", [600]), body: f("jost", [400, 700]) },
    headingWeight: 600,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "flat", badge: "plain", priceList: "cards", spacing: "airy" },
    photoDirection: "Fashion-editorial: single garments on dark backdrops, dramatic side light, rich fabric texture.",
  },
  "retail.barn_board": {
    id: "retail.barn_board",
    name: "Barn Board",
    category: "retail",
    layout: "split",
    palette: {
      bg: "#1E2B22", surface: "#26352B", band: "#2B3C30", text: "#F1EEE2", muted: "#BFC4B4", heading: "#F1EEE2",
      link: "#F0B95A", primary: "#E3A73B", secondary: "#F1EEE2", accent: "#B5462B", heroBg: "#141D17", onHero: "#F1EEE2",
      barBg: "#141D17", onBar: "#F1EEE2", footerBg: "#141D17", onFooter: "#BFC4B4", open: "#A3DDA5", closed: "#F4A38F",
    },
    fonts: { heading: f("bitter", [800]), body: f("barlow", [400, 700]) },
    headingWeight: 800,
    radius: 4,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "Feed sacks, tack and tools in a weathered barn, low golden light through the doors.",
  },
  "retail.blue_hour": {
    id: "retail.blue_hour",
    name: "Blue Hour",
    category: "retail",
    layout: "overlap",
    palette: {
      bg: "#172238", surface: "#1F2D48", band: "#233352", text: "#EEF1F7", muted: "#B2BCD0", heading: "#FFFFFF",
      link: "#F7A58A", primary: "#F48C6A", secondary: "#EEF1F7", accent: "#F48C6A", heroBg: "#0F1727", onHero: "#EEF1F7",
      barBg: "#0F1727", onBar: "#EEF1F7", footerBg: "#0F1727", onFooter: "#B2BCD0", open: "#95E0B0", closed: "#FFA8A0",
    },
    fonts: { heading: f("prata", [400]), body: f("lato", [400, 700]) },
    headingWeight: 400,
    radius: 12,
    button: "pill",
    knobs: { hero: "dark", divider: "rule", label: "small_caps", card: "bordered", badge: "seal", priceList: "cards", spacing: "standard" },
    photoDirection: "The shop lit up at dusk, candles and glassware glowing, gifts wrapped on a dark counter.",
  },
  "retail.walnut_showroom": {
    id: "retail.walnut_showroom",
    name: "Walnut Showroom",
    category: "retail",
    layout: "minimal",
    palette: {
      bg: "#2B1F18", surface: "#352820", band: "#3B2C23", text: "#F4ECE2", muted: "#CDBDAA", heading: "#F4ECE2",
      link: "#E2BC8A", primary: "#D8B07A", secondary: "#7E9C8A", accent: "#D8B07A", heroBg: "#1E1510", onHero: "#F4ECE2",
      barBg: "#1E1510", onBar: "#F4ECE2", footerBg: "#1E1510", onFooter: "#CDBDAA", open: "#A8D9A0", closed: "#F2A28E",
    },
    fonts: { heading: f("libre-baskerville", [700]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 700,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Room settings with warm lamps, wood grain and upholstery close-ups, wide showroom views.",
  },
  "retail.night_garden": {
    id: "retail.night_garden",
    name: "Night Garden",
    category: "retail",
    layout: "soft",
    palette: {
      bg: "#102A2C", surface: "#15363A", band: "#193D41", text: "#ECF4F1", muted: "#AFC6C1", heading: "#ECF4F1",
      link: "#F3B6C9", primary: "#F3B6C9", secondary: "#ECF4F1", accent: "#E7C46A", heroBg: "#0A1E20", onHero: "#ECF4F1",
      barBg: "#0A1E20", onBar: "#ECF4F1", footerBg: "#0A1E20", onFooter: "#AFC6C1", open: "#A9E2B6", closed: "#FFB3AB",
    },
    fonts: { heading: f("instrument-serif", [400]), body: f("instrument-sans", [400, 700]) },
    headingWeight: 400,
    radius: 22,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "small_caps", card: "flat", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Blooms against deep green shadows, dramatic florals lit from one side, moody and lush.",
  },

  // ---- crisp white ----
  "retail.gallery_wall": {
    id: "retail.gallery_wall",
    name: "Gallery Wall",
    category: "retail",
    layout: "minimal",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F3F3F1", text: "#111111", muted: "#555555", heading: "#111111",
      link: "#C0301A", primary: "#111111", secondary: "#FF5A36", accent: "#FF5A36", heroBg: "#F3F3F1", onHero: "#111111",
      barBg: "#F3F3F1", onBar: "#111111", footerBg: "#111111", onFooter: "#F3F3F1", open: "#1E6B3A", closed: "#C0301A",
    },
    fonts: { heading: f("syne", [700]), body: f("inter", [400, 700]) },
    headingWeight: 700,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "bordered", badge: "plain", priceList: "cards", spacing: "airy" },
    photoDirection: "Gallery-clean: one object per frame on white, lots of negative space, even daylight.",
  },
  "retail.linen_closet": {
    id: "retail.linen_closet",
    name: "Linen Closet",
    category: "retail",
    layout: "classic",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EEF2F6", text: "#22303C", muted: "#50606E", heading: "#2C4A66",
      link: "#2C5A85", primary: "#3B5B7A", secondary: "#D9B99B", accent: "#D9B99B", heroBg: "#EEF2F6", onHero: "#22303C",
      barBg: "#22303C", onBar: "#FFFFFF", footerBg: "#22303C", onFooter: "#EEF2F6", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("raleway", [700]), body: f("open-sans", [400, 700]) },
    headingWeight: 700,
    radius: 8,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "shadow", badge: "pill", priceList: "leaders", spacing: "standard" },
    photoDirection: "Bright, calm home-goods styling: folded linens, candles and soaps on pale wood in window light.",
  },
  "retail.tag_sale": {
    id: "retail.tag_sale",
    name: "Tag Sale",
    category: "retail",
    layout: "poster",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#FFF2C2", text: "#1A1A1A", muted: "#4D4A40", heading: "#1A1A1A",
      link: "#C8102E", primary: "#D7192F", secondary: "#1A1A1A", accent: "#FFD23F", heroBg: "#1A1A1A", onHero: "#FFFFFF",
      barBg: "#1A1A1A", onBar: "#FFFFFF", footerBg: "#1A1A1A", onFooter: "#FFF2C2", open: "#1E6B2A", closed: "#B3121F",
    },
    fonts: { heading: f("staatliches", [400]), body: f("archivo", [400, 700]) },
    headingWeight: 400,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "cards", spacing: "dense" },
    photoDirection: "Racks and bins full of finds, price tags in focus, bright flash-style energy.",
  },
  "retail.paper_goods": {
    id: "retail.paper_goods",
    name: "Paper Goods",
    category: "retail",
    layout: "split",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F6F1E9", text: "#2A2826", muted: "#5A554F", heading: "#2F6F5E",
      link: "#2F6F5E", primary: "#2F6F5E", secondary: "#E8A8A0", accent: "#E8A8A0", heroBg: "#F6F1E9", onHero: "#2A2826",
      barBg: "#2A2826", onBar: "#FFFFFF", footerBg: "#2F6F5E", onFooter: "#FFFFFF", open: "#2F6F5E", closed: "#A8322A",
    },
    fonts: { heading: f("domine", [700]), body: f("karla", [400, 700]) },
    headingWeight: 700,
    radius: 14,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "flat", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "Overhead flat-lays of cards, ribbon, notebooks and small gifts on a light table.",
  },
  "retail.bright_aisle": {
    id: "retail.bright_aisle",
    name: "Bright Aisle",
    category: "retail",
    layout: "overlap",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#EEF1FF", text: "#141833", muted: "#4B5070", heading: "#141833",
      link: "#2D4BFF", primary: "#2D4BFF", secondary: "#FFC94D", accent: "#FFC94D", heroBg: "#EEF1FF", onHero: "#141833",
      barBg: "#141833", onBar: "#FFFFFF", footerBg: "#141833", onFooter: "#EEF1FF", open: "#1E7040", closed: "#C0262D",
    },
    fonts: { heading: f("space-grotesk", [700]), body: f("dm-sans", [400, 700]) },
    headingWeight: 700,
    radius: 16,
    button: "pill",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Crisp, colorful product shots on plain backgrounds; a well-lit aisle with full shelves.",
  },

  // ---- warm / tinted light ----
  "retail.feed_seed": {
    id: "retail.feed_seed",
    name: "Feed & Seed",
    category: "retail",
    layout: "classic",
    palette: {
      bg: "#F2E9D8", surface: "#FBF6EC", band: "#E6D9BF", text: "#29251D", muted: "#554D3E", heading: "#33571F",
      link: "#33571F", primary: "#3F6B2A", secondary: "#7A2E1E", accent: "#D9A03A", heroBg: "#29251D", onHero: "#FBF6EC",
      barBg: "#29251D", onBar: "#FBF6EC", footerBg: "#29251D", onFooter: "#E6D9BF", open: "#33571F", closed: "#7A2E1E",
    },
    fonts: { heading: f("patua-one", [400]), body: f("cabin", [400, 700]) },
    headingWeight: 400,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Seed racks, chicks under the lamp, pallets of feed and the loading dock in daylight.",
  },
  "retail.garden_gate": {
    id: "retail.garden_gate",
    name: "Garden Gate",
    category: "retail",
    layout: "soft",
    palette: {
      bg: "#EDF1E7", surface: "#FFFFFF", band: "#E0E8D7", text: "#232B22", muted: "#4D584A", heading: "#3E5A3C",
      link: "#8E3553", primary: "#A03E5E", secondary: "#3E5A3C", accent: "#C7A6B3", heroBg: "#E0E8D7", onHero: "#232B22",
      barBg: "#232B22", onBar: "#FFFFFF", footerBg: "#232B22", onFooter: "#E0E8D7", open: "#2F6B35", closed: "#A03E5E",
    },
    fonts: { heading: f("playfair-display", [600]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 600,
    radius: 20,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "shadow", badge: "seal", priceList: "cards", spacing: "airy" },
    photoDirection: "Garden-fresh: bouquets in buckets, potted plants on the porch, soft overcast light.",
  },
  "retail.rose_quartz": {
    id: "retail.rose_quartz",
    name: "Rose Quartz",
    category: "retail",
    layout: "editorial",
    palette: {
      bg: "#FBEDEA", surface: "#FFFFFF", band: "#F5DAD4", text: "#2A1E21", muted: "#5E4A4F", heading: "#2A1E21",
      link: "#A3334F", primary: "#B23A5A", secondary: "#2A1E21", accent: "#D9A3A0", heroBg: "#F5DAD4", onHero: "#2A1E21",
      barBg: "#2A1E21", onBar: "#FBEDEA", footerBg: "#2A1E21", onFooter: "#F5DAD4", open: "#2E6B3A", closed: "#A3334F",
    },
    fonts: { heading: f("abril-fatface", [400]), body: f("work-sans", [400, 700]) },
    headingWeight: 400,
    radius: 6,
    button: "pill",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "flat", badge: "plain", priceList: "cards", spacing: "airy" },
    photoDirection: "Soft blush tones, outfits on models in natural light, accessories and jewelry close up.",
  },
  "retail.attic_finds": {
    id: "retail.attic_finds",
    name: "Attic Finds",
    category: "retail",
    layout: "classic",
    palette: {
      bg: "#F4ECDD", surface: "#FBF7EE", band: "#E8DCC5", text: "#2B2420", muted: "#5A4D42", heading: "#2B2420",
      link: "#6A3A1F", primary: "#6A3A1F", secondary: "#2F3E46", accent: "#B08A4A", heroBg: "#E8DCC5", onHero: "#2B2420",
      barBg: "#2B2420", onBar: "#F4ECDD", footerBg: "#2B2420", onFooter: "#E8DCC5", open: "#2E6B3A", closed: "#8F2F16",
    },
    fonts: { heading: f("eb-garamond", [600]), body: f("libre-franklin", [400, 700]) },
    headingWeight: 600,
    radius: 3,
    button: "square",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "ruled", badge: "seal", priceList: "leaders", spacing: "standard" },
    photoDirection: "Collector's detail: old china, quilts, clocks and crates in warm, slightly faded light.",
  },
  "retail.quilt_square": {
    id: "retail.quilt_square",
    name: "Quilt Square",
    category: "retail",
    layout: "classic",
    palette: {
      bg: "#E8F0F6", surface: "#FFFFFF", band: "#D7E4EE", text: "#1E2A35", muted: "#475766", heading: "#234A6B",
      link: "#234A6B", primary: "#B4472B", secondary: "#234A6B", accent: "#E6B655", heroBg: "#1A3550", onHero: "#FFFFFF",
      barBg: "#1A3550", onBar: "#FFFFFF", footerBg: "#1E2A35", onFooter: "#D7E4EE", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("vollkorn", [700]), body: f("public-sans", [400, 700]) },
    headingWeight: 700,
    radius: 10,
    button: "rounded",
    knobs: { hero: "dark", divider: "thick_rule", label: "none", card: "bordered", badge: "sticker", priceList: "leaders", spacing: "standard" },
    photoDirection: "Handmade goods in cheerful daylight: quilts, crafts, local jams and pottery on tables.",
  },
  "retail.honey_jar": {
    id: "retail.honey_jar",
    name: "Honey Jar",
    category: "retail",
    layout: "split",
    palette: {
      bg: "#FFF5DB", surface: "#FFFFFF", band: "#FBE6A9", text: "#2E2A24", muted: "#5C5244", heading: "#2E2A24",
      link: "#8A5A12", primary: "#8A5A12", secondary: "#2E2A24", accent: "#E8B030", heroBg: "#FBE6A9", onHero: "#2E2A24",
      barBg: "#2E2A24", onBar: "#FFF5DB", footerBg: "#2E2A24", onFooter: "#FBE6A9", open: "#2E6B2A", closed: "#A33A1E",
    },
    fonts: { heading: f("arvo", [700]), body: f("hind", [400, 700]) },
    headingWeight: 700,
    radius: 12,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Golden, sunny shelves of local goods: honey, candles, jams and baskets in warm light.",
  },

  // ---- bold / pastel ----
  "retail.cherry_pop": {
    id: "retail.cherry_pop",
    name: "Cherry Pop",
    category: "retail",
    layout: "poster",
    palette: {
      bg: "#FF6B9A", surface: "#FFE6EE", band: "#FF85AC", text: "#1F0A14", muted: "#3D1426", heading: "#1F0A14",
      link: "#4A0E2A", primary: "#1F0A14", secondary: "#FFE6EE", accent: "#FFE45C", heroBg: "#B0124F", onHero: "#FFFFFF",
      barBg: "#B0124F", onBar: "#FFFFFF", footerBg: "#1F0A14", onFooter: "#FFE6EE", open: "#1E6B3A", closed: "#A3123C",
    },
    fonts: { heading: f("poppins", [800]), body: f("outfit", [400, 700]) },
    headingWeight: 800,
    radius: 18,
    button: "pill",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Fun and poppy: bright outfits and accessories against solid color walls, hard light.",
  },
  "retail.clover_field": {
    id: "retail.clover_field",
    name: "Clover Field",
    category: "retail",
    layout: "poster",
    palette: {
      bg: "#23663F", surface: "#1B5232", band: "#194C2E", text: "#F7F5EC", muted: "#D6EBDD", heading: "#F6E7C1",
      link: "#F6E7C1", primary: "#F6E7C1", secondary: "#12341F", accent: "#E2B44A", heroBg: "#12341F", onHero: "#F7F5EC",
      barBg: "#12341F", onBar: "#F7F5EC", footerBg: "#12341F", onFooter: "#D6EBDD", open: "#CFF5C8", closed: "#FFD0C7",
    },
    fonts: { heading: f("teko", [600]), body: f("asap", [400, 700]) },
    headingWeight: 600,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "flat", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "Green fields and garden centers, flats of plants and seedlings, bright open-air daylight.",
  },
  "retail.mint_condition": {
    id: "retail.mint_condition",
    name: "Mint Condition",
    category: "retail",
    layout: "soft",
    palette: {
      bg: "#D7F2E6", surface: "#FFFFFF", band: "#C2EAD8", text: "#16302A", muted: "#3C5850", heading: "#16302A",
      link: "#B03A26", primary: "#C2402A", secondary: "#16302A", accent: "#F2A33A", heroBg: "#C2EAD8", onHero: "#16302A",
      barBg: "#16302A", onBar: "#D7F2E6", footerBg: "#16302A", onFooter: "#D7F2E6", open: "#17663E", closed: "#B03A26",
    },
    fonts: { heading: f("righteous", [400]), body: f("figtree", [400, 700]) },
    headingWeight: 400,
    radius: 14,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "none", card: "bordered", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Retro finds styled in pastel corners: vintage tees, records, lamps and kitsch, cheerful light.",
  },
  "retail.periwinkle_porch": {
    id: "retail.periwinkle_porch",
    name: "Periwinkle Porch",
    category: "retail",
    layout: "overlap",
    palette: {
      bg: "#E3E8FB", surface: "#FFFFFF", band: "#D2DAF6", text: "#1D2240", muted: "#4A5072", heading: "#2F3E8F",
      link: "#2F3E8F", primary: "#F4B9A6", secondary: "#2F3E8F", accent: "#F4B9A6", heroBg: "#2F3E8F", onHero: "#FFFFFF",
      barBg: "#2F3E8F", onBar: "#FFFFFF", footerBg: "#1D2240", onFooter: "#D2DAF6", open: "#22693F", closed: "#A8323A",
    },
    fonts: { heading: f("josefin-slab", [700]), body: f("red-hat-text", [400, 700]) },
    headingWeight: 700,
    radius: 24,
    button: "pill",
    knobs: { hero: "dark", divider: "rule", label: "small_caps", card: "shadow", badge: "seal", priceList: "leaders", spacing: "airy" },
    photoDirection: "Cottage charm: painted porches, wreaths, baby gifts and home decor in cool, soft light.",
  },
  "retail.terracotta_pot": {
    id: "retail.terracotta_pot",
    name: "Terracotta Pot",
    category: "retail",
    layout: "minimal",
    palette: {
      bg: "#9A3F1A", surface: "#8E3918", band: "#873616", text: "#FFF3E6", muted: "#F3D6C4", heading: "#FFF3E6",
      link: "#FFDCA8", primary: "#F7D9A8", secondary: "#2B1A12", accent: "#E9B872", heroBg: "#2B1A12", onHero: "#FFF3E6",
      barBg: "#2B1A12", onBar: "#FFF3E6", footerBg: "#2B1A12", onFooter: "#F3D6C4", open: "#D4F2C4", closed: "#FFE0D6",
    },
    fonts: { heading: f("noto-serif-display", [600]), body: f("ibm-plex-sans", [400, 700]) },
    headingWeight: 600,
    radius: 10,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "small_caps", card: "bordered", badge: "seal", priceList: "cards", spacing: "airy" },
    photoDirection: "Sun-baked warmth: clay pots, succulents, woven baskets and pottery against plaster walls.",
  },
};
