import { f } from "../look-kit.ts";
import type { LookDef } from "../themes.ts";

/** More salon looks (colors + fonts). Contrast is checked at build by resolveTheme; see test/designs.test.ts. */
export const SALON_LOOKS: Record<string, LookDef> = {
  // ── Dark ──────────────────────────────────────────────────────────────
  "salon.black_velvet": {
    id: "salon.black_velvet",
    name: "Black Velvet",
    category: "salon",
    layout: "editorial",
    palette: {
      bg: "#0E0C0D", surface: "#1C1819", band: "#161213", text: "#F3ECE8", muted: "#B9ADA8", heading: "#F3ECE8",
      link: "#E8B8A4", primary: "#D9A08A", secondary: "#F3ECE8", accent: "#B87E6A", heroBg: "#0E0C0D", onHero: "#F3ECE8",
      barBg: "#050404", onBar: "#F3ECE8", footerBg: "#050404", onFooter: "#D8CCC6", open: "#8FDCA6", closed: "#F5A3A3",
    },
    fonts: { heading: f("bodoni-moda", [500]), body: f("jost", [400, 700]) },
    headingWeight: 500,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Low-key studio light on black, glossy finished styles and rose-gold tools, lots of shadow.",
  },
  "salon.plum_parlor": {
    id: "salon.plum_parlor",
    name: "Plum Parlor",
    category: "salon",
    layout: "overlap",
    palette: {
      bg: "#2A1530", surface: "#3A2142", band: "#321A39", text: "#F6EAF2", muted: "#CDB6C8", heading: "#F9D9E4",
      link: "#F4B6CB", primary: "#F2B3C6", secondary: "#E9C46A", accent: "#E9C46A", heroBg: "#1F0F24", onHero: "#F6EAF2",
      barBg: "#1F0F24", onBar: "#F6EAF2", footerBg: "#1A0C1F", onFooter: "#E6D3E0", open: "#9BE3B4", closed: "#FFB0B8",
    },
    fonts: { heading: f("playfair-display", [700]), body: f("lato", [400, 700]) },
    headingWeight: 700,
    radius: 20,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "small_caps", card: "flat", badge: "seal", priceList: "cards", spacing: "standard" },
    photoDirection: "Warm lamplight, velvet chairs and mirrors, jewel-tone color work, a little glamour.",
  },
  "salon.barber_pole": {
    id: "salon.barber_pole",
    name: "Barber Pole",
    category: "salon",
    layout: "poster",
    palette: {
      bg: "#101A2E", surface: "#1A2740", band: "#15213A", text: "#F2F4F8", muted: "#AEB8C9", heading: "#FFFFFF",
      link: "#FF9C9C", primary: "#D7263D", secondary: "#F2F4F8", accent: "#D7263D", heroBg: "#0A1222", onHero: "#FFFFFF",
      barBg: "#0A1222", onBar: "#FFFFFF", footerBg: "#0A1222", onFooter: "#D5DBE6", open: "#8EE0A8", closed: "#FF9C9C",
    },
    fonts: { heading: f("bebas-neue", [400]), body: f("barlow", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "Classic chairs and the striped pole, hot towels and straight razors, crisp and slightly cool.",
  },
  "salon.forest_spa": {
    id: "salon.forest_spa",
    name: "Forest Spa",
    category: "salon",
    layout: "soft",
    palette: {
      bg: "#17261F", surface: "#21332A", band: "#1C2D25", text: "#EEF2EA", muted: "#B4C2B6", heading: "#E7EFDF",
      link: "#C9DDB0", primary: "#B8CFA6", secondary: "#E7D6B8", accent: "#8FAF86", heroBg: "#12201A", onHero: "#EEF2EA",
      barBg: "#0F1B15", onBar: "#EEF2EA", footerBg: "#0F1B15", onFooter: "#D4DED2", open: "#A6E3B4", closed: "#F6B3A6",
    },
    fonts: { heading: f("cormorant-garamond", [600]), body: f("mulish", [400, 700]) },
    headingWeight: 600,
    radius: 24,
    button: "pill",
    knobs: { hero: "dark", divider: "none", label: "small_caps", card: "flat", badge: "plain", priceList: "cards", spacing: "airy" },
    photoDirection: "Dim, calm rooms: folded towels, stones, candles, greenery, hands at work. Soft and unhurried.",
  },
  "salon.espresso_fade": {
    id: "salon.espresso_fade",
    name: "Espresso Fade",
    category: "salon",
    layout: "split",
    palette: {
      bg: "#231914", surface: "#31241D", band: "#2B1F19", text: "#F4EAE0", muted: "#C2B1A2", heading: "#F4EAE0",
      link: "#F0B27A", primary: "#E08E45", secondary: "#F4EAE0", accent: "#E08E45", heroBg: "#1A120E", onHero: "#F4EAE0",
      barBg: "#1A120E", onBar: "#F4EAE0", footerBg: "#140E0B", onFooter: "#DCCBBC", open: "#9EDDAA", closed: "#F7A99A",
    },
    fonts: { heading: f("anton", [400]), body: f("rubik", [400, 700]) },
    headingWeight: 400,
    radius: 6,
    button: "rounded",
    knobs: { hero: "dark", divider: "rule", label: "uppercase", card: "bordered", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Warm tungsten light, leather and wood, sharp fades and beard work shot close with a dark backdrop.",
  },

  // ── Crisp white ───────────────────────────────────────────────────────
  "salon.paper_white": {
    id: "salon.paper_white",
    name: "Paper White",
    category: "salon",
    layout: "minimal",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#F4F4F2", text: "#141414", muted: "#5C5C5C", heading: "#141414",
      link: "#8A5A44", primary: "#141414", secondary: "#E9E4DC", accent: "#C8B8A6", heroBg: "#F4F4F2", onHero: "#141414",
      barBg: "#F4F4F2", onBar: "#141414", footerBg: "#141414", onFooter: "#EDEDED", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("instrument-serif", [400]), body: f("inter", [400, 700]) },
    headingWeight: 400,
    radius: 0,
    button: "square",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "flat", badge: "plain", priceList: "leaders", spacing: "airy" },
    photoDirection: "Editorial portraits on plain white or gray seamless, natural texture, minimal props.",
  },
  "salon.gloss_pink": {
    id: "salon.gloss_pink",
    name: "Gloss Pink",
    category: "salon",
    layout: "split",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#FFEAF2", text: "#2A1320", muted: "#6B4A5B", heading: "#2A1320",
      link: "#B0185A", primary: "#CC2E66", secondary: "#2A1320", accent: "#FFB3CD", heroBg: "#FFEAF2", onHero: "#2A1320",
      barBg: "#2A1320", onBar: "#FFFFFF", footerBg: "#2A1320", onFooter: "#FFEAF2", open: "#1F6B4A", closed: "#B0233F",
    },
    fonts: { heading: f("unbounded", [600]), body: f("outfit", [400, 700]) },
    headingWeight: 600,
    radius: 28,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "uppercase", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Bright, glossy nail and lash close-ups on clean pastel backdrops, polish bottles in rows.",
  },
  "salon.steel_comb": {
    id: "salon.steel_comb",
    name: "Steel Comb",
    category: "salon",
    layout: "classic",
    palette: {
      bg: "#FFFFFF", surface: "#F7F8FA", band: "#ECEFF3", text: "#1B1F24", muted: "#4F5763", heading: "#1B1F24",
      link: "#2557A7", primary: "#C8102E", secondary: "#1B1F24", accent: "#C8102E", heroBg: "#1B1F24", onHero: "#FFFFFF",
      barBg: "#1B1F24", onBar: "#FFFFFF", footerBg: "#1B1F24", onFooter: "#E3E7EC", open: "#1F6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("saira-condensed", [700]), body: f("ibm-plex-sans", [400, 700]) },
    headingWeight: 700,
    radius: 2,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "leaders", spacing: "dense" },
    photoDirection: "Clean modern barbershop, chrome and black chairs, profile shots of tapers, cool neutral grade.",
  },
  "salon.pearl_studio": {
    id: "salon.pearl_studio",
    name: "Pearl Studio",
    category: "salon",
    layout: "editorial",
    palette: {
      bg: "#FFFFFF", surface: "#FBF9F7", band: "#F3EEE9", text: "#2F2925", muted: "#675C55", heading: "#3D332D",
      link: "#7A5C4A", primary: "#7A5C4A", secondary: "#E8DDD3", accent: "#CBB8A6", heroBg: "#F3EEE9", onHero: "#2F2925",
      barBg: "#3D332D", onBar: "#FFFFFF", footerBg: "#F3EEE9", onFooter: "#2F2925", open: "#2E6B3A", closed: "#9E3B2C",
    },
    fonts: { heading: f("marcellus", [400]), body: f("albert-sans", [400, 700]) },
    headingWeight: 400,
    radius: 10,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "small_caps", card: "flat", badge: "seal", priceList: "leaders", spacing: "airy" },
    photoDirection: "Airy and neutral: linen, pale wood, soft blowouts and balayage in diffused daylight.",
  },
  "salon.happy_paws": {
    id: "salon.happy_paws",
    name: "Happy Paws",
    category: "salon",
    layout: "soft",
    palette: {
      bg: "#FFFFFF", surface: "#FFFFFF", band: "#E6F7F8", text: "#1D2B3A", muted: "#4C5B6B", heading: "#1D2B3A",
      link: "#0B6E85", primary: "#FFB547", secondary: "#0B6E85", accent: "#FF7F6B", heroBg: "#E6F7F8", onHero: "#1D2B3A",
      barBg: "#1D2B3A", onBar: "#FFFFFF", footerBg: "#0B4F60", onFooter: "#E6F7F8", open: "#1F6B4A", closed: "#B0362A",
    },
    fonts: { heading: f("quicksand", [700]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 700,
    radius: 22,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Happy freshly groomed pets at eye level, bright daylight, bandanas and bows, clean tubs and tables.",
  },

  // ── Warm and tinted light ─────────────────────────────────────────────
  "salon.blush_hour": {
    id: "salon.blush_hour",
    name: "Blush Hour",
    category: "salon",
    layout: "overlap",
    palette: {
      bg: "#FBEDEA", surface: "#FFFFFF", band: "#F6DCD6", text: "#3A2128", muted: "#6A4C52", heading: "#7A2E45",
      link: "#8E2F4C", primary: "#8E2F4C", secondary: "#E7B4A8", accent: "#D98C8C", heroBg: "#F6DCD6", onHero: "#3A2128",
      barBg: "#3A2128", onBar: "#FBEDEA", footerBg: "#3A2128", onFooter: "#F6DCD6", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("yeseva-one", [400]), body: f("work-sans", [400, 700]) },
    headingWeight: 400,
    radius: 16,
    button: "rounded",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "flat", badge: "seal", priceList: "cards", spacing: "airy" },
    photoDirection: "Golden-hour warmth, soft curls and updos, bridal and prom styling, flowers in the frame.",
  },
  "salon.sage_room": {
    id: "salon.sage_room",
    name: "Sage Room",
    category: "salon",
    layout: "classic",
    palette: {
      bg: "#EEF2EA", surface: "#FAFBF8", band: "#E1E8DC", text: "#22302A", muted: "#4E5D55", heading: "#2F4A3A",
      link: "#3C6A4E", primary: "#3C6A4E", secondary: "#D9C7A7", accent: "#A7BFA0", heroBg: "#E1E8DC", onHero: "#22302A",
      barBg: "#22302A", onBar: "#FFFFFF", footerBg: "#22302A", onFooter: "#E1E8DC", open: "#2E6B3A", closed: "#9E3B2C",
    },
    fonts: { heading: f("lora", [600]), body: f("karla", [400, 700]) },
    headingWeight: 600,
    radius: 12,
    button: "pill",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "bordered", badge: "plain", priceList: "leaders", spacing: "standard" },
    photoDirection: "Plants, clay and linen, natural-light color work and massage rooms, muted green grade.",
  },
  "salon.lavender_haze": {
    id: "salon.lavender_haze",
    name: "Lavender Haze",
    category: "salon",
    layout: "split",
    palette: {
      bg: "#F4F0FA", surface: "#FFFFFF", band: "#E7DFF4", text: "#2A2140", muted: "#5B5070", heading: "#4A2F7A",
      link: "#5E3B9A", primary: "#5E3B9A", secondary: "#2A2140", accent: "#C7B4EC", heroBg: "#2A2140", onHero: "#F4F0FA",
      barBg: "#2A2140", onBar: "#FFFFFF", footerBg: "#2A2140", onFooter: "#E7DFF4", open: "#1F6B4A", closed: "#A8322A",
    },
    fonts: { heading: f("josefin-sans", [600]), body: f("figtree", [400, 700]) },
    headingWeight: 600,
    radius: 8,
    button: "rounded",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "shadow", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Cool pastel light, vivid fashion color and silver blondes, clean pale-wall backdrops.",
  },
  "salon.sand_dollar": {
    id: "salon.sand_dollar",
    name: "Sand Dollar",
    category: "salon",
    layout: "minimal",
    palette: {
      bg: "#F5ECDF", surface: "#FFFAF2", band: "#EADCC8", text: "#2B2A26", muted: "#5A554C", heading: "#1F3B3E",
      link: "#1F5A5E", primary: "#C98A5A", secondary: "#1F3B3E", accent: "#C98A5A", heroBg: "#1F3B3E", onHero: "#F5ECDF",
      barBg: "#1F3B3E", onBar: "#F5ECDF", footerBg: "#2B2A26", onFooter: "#EADCC8", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("gloock", [400]), body: f("hind", [400, 700]) },
    headingWeight: 400,
    radius: 4,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "small_caps", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "standard" },
    photoDirection: "Sun-warmed neutrals, beachy waves and bronze tones, rattan and terracotta in the background.",
  },
  "salon.mint_julep": {
    id: "salon.mint_julep",
    name: "Mint Julep",
    category: "salon",
    layout: "classic",
    palette: {
      bg: "#EAF6F0", surface: "#FFFFFF", band: "#D6EFE3", text: "#1A2E28", muted: "#48605A", heading: "#1A2E28",
      link: "#146B57", primary: "#146B57", secondary: "#F4A896", accent: "#F4A896", heroBg: "#D6EFE3", onHero: "#1A2E28",
      barBg: "#1A2E28", onBar: "#FFFFFF", footerBg: "#1A2E28", onFooter: "#D6EFE3", open: "#146B57", closed: "#A8322A",
    },
    fonts: { heading: f("prata", [400]), body: f("hanken-grotesk", [400, 700]) },
    headingWeight: 400,
    radius: 18,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "small_caps", card: "shadow", badge: "pill", priceList: "cards", spacing: "airy" },
    photoDirection: "Fresh and breezy: pedicure chairs, facials, mint and coral accents, soft daylight.",
  },
  "salon.peach_fuzz": {
    id: "salon.peach_fuzz",
    name: "Peach Fuzz",
    category: "salon",
    layout: "editorial",
    palette: {
      bg: "#FFF1E8", surface: "#FFFFFF", band: "#FFE0CC", text: "#2E1E17", muted: "#634A3E", heading: "#2E1E17",
      link: "#A3402A", primary: "#E2704F", secondary: "#2E1E17", accent: "#FFB38A", heroBg: "#FFE0CC", onHero: "#2E1E17",
      barBg: "#2E1E17", onBar: "#FFF1E8", footerBg: "#5A2A1E", onFooter: "#FFE0CC", open: "#2E6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("abril-fatface", [400]), body: f("poppins", [400, 700]) },
    headingWeight: 400,
    radius: 14,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "flat", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Warm, sunny and playful: copper and strawberry color, big smiles, peach-toned walls.",
  },

  // ── Bold and pastel ───────────────────────────────────────────────────
  "salon.lemon_drop": {
    id: "salon.lemon_drop",
    name: "Lemon Drop",
    category: "salon",
    layout: "poster",
    palette: {
      bg: "#FFE14D", surface: "#FFFFFF", band: "#FFF0A3", text: "#1A1A1A", muted: "#4A4420", heading: "#1A1A1A",
      link: "#5B23A3", primary: "#6A2BB5", secondary: "#1A1A1A", accent: "#6A2BB5", heroBg: "#FFE14D", onHero: "#1A1A1A",
      barBg: "#1A1A1A", onBar: "#FFE14D", footerBg: "#1A1A1A", onFooter: "#FFE14D", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("syne", [700]), body: f("space-grotesk", [400, 700]) },
    headingWeight: 700,
    radius: 12,
    button: "rounded",
    knobs: { hero: "light", divider: "thick_rule", label: "uppercase", card: "bordered", badge: "sticker", priceList: "leaders", spacing: "dense" },
    photoDirection: "Punchy flash photos on bright paper backdrops, bold color and graphic nail art.",
  },
  "salon.cobalt_chair": {
    id: "salon.cobalt_chair",
    name: "Cobalt Chair",
    category: "salon",
    layout: "minimal",
    palette: {
      bg: "#F0F3FF", surface: "#FFFFFF", band: "#DCE3FF", text: "#121A3D", muted: "#46507A", heading: "#1B2FB8",
      link: "#1B2FB8", primary: "#FF8A3D", secondary: "#1B2FB8", accent: "#FF8A3D", heroBg: "#1B2FB8", onHero: "#FFFFFF",
      barBg: "#121A3D", onBar: "#FFFFFF", footerBg: "#121A3D", onFooter: "#DCE3FF", open: "#1F6B3A", closed: "#B3261E",
    },
    fonts: { heading: f("league-spartan", [800]), body: f("public-sans", [400, 700]) },
    headingWeight: 800,
    radius: 6,
    button: "square",
    knobs: { hero: "dark", divider: "none", label: "uppercase", card: "flat", badge: "pill", priceList: "cards", spacing: "standard" },
    photoDirection: "Graphic and modern: strong side light, clean cuts against blue walls, one orange accent prop.",
  },
  "salon.bubblegum": {
    id: "salon.bubblegum",
    name: "Bubblegum",
    category: "salon",
    layout: "soft",
    palette: {
      bg: "#FFE4EF", surface: "#FFFFFF", band: "#D9F5EC", text: "#2D1B4E", muted: "#5C4A78", heading: "#2D1B4E",
      link: "#8A1F6B", primary: "#2D1B4E", secondary: "#FF6FA8", accent: "#7ED9C3", heroBg: "#FFC9DE", onHero: "#2D1B4E",
      barBg: "#8A1F6B", onBar: "#FFFFFF", footerBg: "#2D1B4E", onFooter: "#FFE4EF", open: "#1F6B4A", closed: "#A8322A",
    },
    fonts: { heading: f("righteous", [400]), body: f("nunito-sans", [400, 700]) },
    headingWeight: 400,
    radius: 26,
    button: "pill",
    knobs: { hero: "light", divider: "none", label: "none", card: "shadow", badge: "sticker", priceList: "cards", spacing: "standard" },
    photoDirection: "Cheerful and candid: kids' cuts, fluffy pups, pastel bows and bubbles, bright even light.",
  },
  "salon.tangerine_shears": {
    id: "salon.tangerine_shears",
    name: "Tangerine Shears",
    category: "salon",
    layout: "overlap",
    palette: {
      bg: "#FF8A4C", surface: "#FFF6EF", band: "#FFA673", text: "#1F130C", muted: "#4A2A18", heading: "#1F130C",
      link: "#4A1890", primary: "#1F130C", secondary: "#FFF6EF", accent: "#FFD84D", heroBg: "#FFF6EF", onHero: "#1F130C",
      barBg: "#FFF6EF", onBar: "#1F130C", footerBg: "#1F130C", onFooter: "#FFA673", open: "#1F6B3A", closed: "#A8322A",
    },
    fonts: { heading: f("bricolage-grotesque", [800]), body: f("dm-sans", [400, 700]) },
    headingWeight: 800,
    radius: 10,
    button: "rounded",
    knobs: { hero: "light", divider: "rule", label: "uppercase", card: "flat", badge: "plain", priceList: "cards", spacing: "standard" },
    photoDirection: "Warm saturated color, energetic team shots, shears mid-cut, bold crops and big smiles.",
  },
  "salon.retro_pomade": {
    id: "salon.retro_pomade",
    name: "Retro Pomade",
    category: "salon",
    layout: "poster",
    palette: {
      bg: "#F3E6CC", surface: "#FFF8EA", band: "#E9D5AE", text: "#231A14", muted: "#57483A", heading: "#A3201F",
      link: "#1F2A44", primary: "#1F2A44", secondary: "#A3201F", accent: "#1F2A44", heroBg: "#A3201F", onHero: "#F3E6CC",
      barBg: "#A3201F", onBar: "#F3E6CC", footerBg: "#1F2A44", onFooter: "#E9D5AE", open: "#2E6B3A", closed: "#A3201F",
    },
    fonts: { heading: f("ultra", [400]), body: f("source-sans-3", [400, 700]) },
    headingWeight: 400,
    radius: 3,
    button: "square",
    knobs: { hero: "dark", divider: "thick_rule", label: "uppercase", card: "ruled", badge: "stamp", priceList: "leaders", spacing: "dense" },
    photoDirection: "Old-school shop with a vintage film tone: pompadours, tins of pomade, chrome and red leather.",
  },
};
